In [1]:
import numpy as np
import tensorflow as tf
import random as python_random
import os

SEED = 42

np.random.seed(SEED)
python_random.seed(SEED)
tf.random.set_seed(SEED)
os.environ["PYTHONHASHSEED"] = str(SEED)
os.environ['TF_DETERMINISTIC_OPS'] = '1'
os.environ['TF_CUDNN_DETERMINISTIC'] = '1'
os.environ['TF_CUDNN_USE_FRONTEND '] = '1'

tf.__version__

2023-09-06 00:05:10.480295: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-09-06 00:05:10.550473: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-09-06 00:05:11.577984: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT

'2.12.0'

In [2]:
model = tf.keras.models.load_model('./best_model.h5')

2023-09-06 00:05:13.709132: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1956] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...

In [3]:
dataset_folder ="/app/MultiModal/dataset/image/20230605_ch1_crop/test/Image/"

In [4]:
import pandas as pd 

class_names = ['A-sky', 'B-pattern', 'C-thick-dark', 'D-thick-white', 'E-veil']

df = pd.DataFrame(columns=["name"]+class_names)
df

Empty DataFrame
Columns: [name, A-sky, B-pattern, C-thick-dark, D-thick-white, E-veil]
Index: []

In [5]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
import os 
import warnings

warnings.filterwarnings(action='ignore')

img_height, img_width = 125, 125


for f in os.listdir(dataset_folder):
    img = tf.keras.utils.load_img(os.path.join(dataset_folder,f), target_size=(img_height, img_width))

    img_array = tf.keras.utils.img_to_array(img)
    img_array = tf.expand_dims(img_array, 0) # Create a batch

    predictions = model.predict(img_array)
    score = tf.nn.softmax(predictions[0])

    class_pred = tf.math.argmax(score)
    
    row = {"name":f}
    for i in range(5):
        row[class_names[i]] = score[i].numpy()*100 
        
    df= df.append(row, ignore_index=True)

2023-09-06 00:05:19.605436: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:19.605778: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 210ms/step
1/1 [==============================] - 0s 40ms/step
1/1 [==============================] - 0s 39ms/step

2023-09-06 00:05:19.890671: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:19.891014: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:19.994335: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:19.994662: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 39ms/step

2023-09-06 00:05:20.102774: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:20.103108: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:20.203776: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:20.204097: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:20.300750: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:20.301075: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:05:20.397986: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:20.398310: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:20.494231: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:20.494555: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:05:20.600387: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:20.600709: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:20.704134: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:20.704458: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:20.800382: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:20.800704: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 40ms/step
1/1 [==============================] - 0s 39ms/step

2023-09-06 00:05:20.911131: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:20.911462: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:21.017040: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:21.017371: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:05:21.112349: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:21.112681: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:21.217885: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:21.218214: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:21.311675: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:21.312039: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 37ms/step

2023-09-06 00:05:21.403513: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:21.403838: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:21.496185: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:21.496511: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:21.585931: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:21.586248: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 40ms/step

2023-09-06 00:05:21.678311: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:21.678638: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:21.788876: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:21.789208: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 39ms/step

2023-09-06 00:05:21.886364: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:21.886695: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:21.982282: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:21.982614: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:05:22.091789: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:22.092117: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:22.186243: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:22.186569: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:05:22.293105: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:22.293432: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:22.388115: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:22.388440: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:22.486478: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:22.486806: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 51ms/step
1/1 [==============================] - 0s 39ms/step

2023-09-06 00:05:22.581754: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:22.582078: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:22.705920: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:22.706251: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 39ms/step

2023-09-06 00:05:22.803254: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:22.803586: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:22.898711: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:22.899057: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 40ms/step

2023-09-06 00:05:23.004846: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:23.005171: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:23.108255: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:23.108581: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:23.205635: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:23.205961: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:05:23.305205: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:23.305529: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:23.401267: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:23.401591: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 37ms/step
1/1 [==============================] - 0s 39ms/step

2023-09-06 00:05:23.507148: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:23.507474: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:23.616796: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:23.617125: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 40ms/step
1/1 [==============================] - 0s 42ms/step

2023-09-06 00:05:23.714899: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:23.715235: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:23.822074: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:23.822407: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 39ms/step

2023-09-06 00:05:23.922414: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:23.922745: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:24.020613: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:24.020939: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:05:24.127624: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:24.127963: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:24.222768: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:24.223126: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:05:24.329083: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:24.329408: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:24.426404: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:24.426729: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 39ms/step

2023-09-06 00:05:24.538595: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:24.538938: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:24.635109: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:24.635442: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:05:24.740535: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:24.740866: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:24.846404: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:24.846734: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:05:24.942228: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:24.942558: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:25.047649: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:25.047974: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:05:25.147423: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:25.147746: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:25.241194: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:25.241519: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:25.333553: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:25.333879: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 37ms/step
1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 39ms/step

2023-09-06 00:05:25.431589: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:25.431919: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:25.523492: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:25.523823: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:25.616076: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:25.616403: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 37ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:05:25.708431: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:25.708759: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:25.799609: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:25.799937: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:25.904786: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:25.905111: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:05:26.010171: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:26.010497: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:26.114074: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:26.114399: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:26.210891: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:26.211220: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 40ms/step
1/1 [==============================] - 0s 39ms/step

2023-09-06 00:05:26.312470: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:26.312804: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:26.410737: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:26.411088: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:26.510977: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:26.511314: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:05:26.608541: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:26.608871: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:26.704366: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:26.704694: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:05:26.811386: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:26.811709: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:26.916279: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:26.916608: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:05:27.014729: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:27.015066: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:27.121115: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:27.121442: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:05:27.229169: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:27.229503: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:27.337186: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:27.337514: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 42ms/step

2023-09-06 00:05:27.443102: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:27.443434: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:27.541993: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:27.542326: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:27.640020: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:27.640361: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:05:27.734224: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:27.734546: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:27.826994: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:27.827321: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:27.919003: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:27.919328: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 39ms/step

2023-09-06 00:05:28.012088: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:28.012411: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:28.123176: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:28.123513: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 39ms/step

2023-09-06 00:05:28.220827: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:28.221162: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:28.316861: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:28.317190: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:28.414333: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:28.414664: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:05:28.508640: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:28.508965: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:28.602774: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:28.603115: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:28.706279: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:28.706605: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:05:28.801952: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:28.802276: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:28.907315: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:28.907644: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 39ms/step

2023-09-06 00:05:29.010034: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:29.010374: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:29.107720: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:29.108054: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:29.203269: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:29.203600: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:05:29.300041: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:29.300374: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:29.402808: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:29.403145: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:29.496285: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:29.496610: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:05:29.601724: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:29.602051: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:29.698769: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:29.699109: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:29.796880: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:29.797207: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 39ms/step

2023-09-06 00:05:29.908839: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:29.909179: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:30.007017: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:30.007355: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 40ms/step
1/1 [==============================] - 0s 39ms/step

2023-09-06 00:05:30.113320: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:30.113663: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:30.220650: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:30.220975: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:30.313413: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:30.313740: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:05:30.404964: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:30.405288: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:30.496246: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:30.496571: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:30.588433: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:30.588756: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 39ms/step

2023-09-06 00:05:30.679457: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:30.679794: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:30.790967: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:30.791307: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 39ms/step

2023-09-06 00:05:30.887229: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:30.887563: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:30.991266: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:30.991595: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:31.086578: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:31.086916: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 37ms/step

2023-09-06 00:05:31.183596: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:31.183921: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:31.275616: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:31.275942: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:31.367317: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:31.367644: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 37ms/step

2023-09-06 00:05:31.461279: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:31.461614: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:31.553831: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:31.554156: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:31.652068: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:31.652406: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 39ms/step

2023-09-06 00:05:31.745524: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:31.745860: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:31.838439: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:31.838770: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:31.933099: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:31.933431: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 37ms/step
1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:05:32.036512: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:32.036837: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:32.132333: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:32.132657: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:32.228201: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:32.228528: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:05:32.327110: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:32.327435: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:32.428500: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:32.428824: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 39ms/step

2023-09-06 00:05:32.532728: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:32.533067: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:32.635912: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:32.636247: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:32.731891: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:32.732221: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:05:32.826306: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:32.826703: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:32.931738: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:32.932087: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:05:33.037054: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:33.037380: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:33.132857: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:33.133181: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:33.224689: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:33.225014: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 37ms/step
1/1 [==============================] - 0s 39ms/step

2023-09-06 00:05:33.329342: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:33.329729: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:33.438785: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:33.439136: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 42ms/step
1/1 [==============================] - 0s 41ms/step

2023-09-06 00:05:33.711191: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:33.711559: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:33.820654: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:33.821014: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 40ms/step
1/1 [==============================] - 0s 40ms/step

2023-09-06 00:05:33.919815: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:33.920170: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:34.018466: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:34.018834: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:34.117951: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:34.118305: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 41ms/step
1/1 [==============================] - 0s 40ms/step
1/1 [==============================] - 0s 39ms/step

2023-09-06 00:05:34.226677: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:34.227037: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:34.332322: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:34.332669: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 39ms/step

2023-09-06 00:05:34.428892: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:34.429232: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:34.526219: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:34.526556: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 40ms/step
1/1 [==============================] - 0s 39ms/step

2023-09-06 00:05:34.631579: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:34.631930: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:34.739450: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:34.739802: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 40ms/step
1/1 [==============================] - 0s 39ms/step

2023-09-06 00:05:34.847790: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:34.848134: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:34.947348: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:34.947687: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 40ms/step
1/1 [==============================] - 0s 39ms/step

2023-09-06 00:05:35.053776: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:35.054116: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:35.155384: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:35.155719: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:05:35.265066: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:35.265392: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:35.361780: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:35.362108: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:35.465896: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:35.466218: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 40ms/step
1/1 [==============================] - 0s 40ms/step

2023-09-06 00:05:35.567931: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:35.568284: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:35.666675: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:35.667025: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:35.763475: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:35.763808: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:05:35.860974: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:35.861305: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:35.957070: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:35.957397: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:36.049988: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:36.050315: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 37ms/step

2023-09-06 00:05:36.143116: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:36.143442: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:36.248172: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:36.248499: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 40ms/step

2023-09-06 00:05:36.344135: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:36.344461: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:36.451143: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:36.451481: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 39ms/step

2023-09-06 00:05:36.550574: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:36.550923: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:36.646826: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:36.647162: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:05:36.753353: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:36.753683: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:36.858415: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:36.858743: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:36.954698: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:36.955039: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:05:37.058209: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:37.058534: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:37.162883: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:37.163208: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:37.258972: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:37.259302: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:05:37.360426: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:37.360760: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:37.453446: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:37.453789: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:37.557542: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:37.557873: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 37ms/step
1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:05:37.664412: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:37.664751: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:37.769274: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:37.769601: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:37.863413: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:37.863738: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 37ms/step
1/1 [==============================] - 0s 37ms/step

2023-09-06 00:05:37.968226: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:37.968602: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:38.062439: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:38.062763: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:38.163094: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:38.163418: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 39ms/step

2023-09-06 00:05:38.262789: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:38.263134: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:38.361385: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:38.361717: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:38.458168: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:38.458496: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:05:38.564357: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:38.564687: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:38.658152: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:38.658480: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:38.752166: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:38.752494: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 37ms/step
1/1 [==============================] - 0s 37ms/step
1/1 [==============================] - 0s 37ms/step

2023-09-06 00:05:38.854680: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:38.855019: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:38.947654: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:38.947984: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:39.042279: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:39.042604: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 37ms/step
1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 39ms/step

2023-09-06 00:05:39.140988: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:39.141322: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:39.234901: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:39.235236: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:39.327442: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:39.327770: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 37ms/step

2023-09-06 00:05:39.419145: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:39.419473: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:39.510652: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:39.510985: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:39.602145: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:39.602470: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 37ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:05:39.693919: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:39.694248: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:39.785226: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:39.785547: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:39.890357: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:39.890684: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:05:40.001337: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:40.001672: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:40.098308: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:40.098643: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:40.193188: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:40.193520: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 50ms/step

2023-09-06 00:05:40.288759: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:40.289091: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:40.393823: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:40.394151: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 37ms/step
1/1 [==============================] - 0s 37ms/step

2023-09-06 00:05:40.503571: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:40.503898: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:40.605745: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:40.606072: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:40.698336: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:40.698660: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 36ms/step
1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:05:40.800797: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:40.801124: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:40.904001: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:40.904337: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:40.996238: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:40.996574: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:05:41.088192: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:41.088522: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:41.180362: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:41.180690: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:41.271481: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:41.271806: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:05:41.361778: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:41.362103: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:41.452548: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:41.452875: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:41.543929: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:41.544252: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:05:41.635647: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:41.635971: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:41.733702: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:41.734042: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:41.825168: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:41.825500: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 37ms/step
1/1 [==============================] - 0s 37ms/step

2023-09-06 00:05:41.928814: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:41.929143: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:42.022041: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:42.022367: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:42.115357: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:42.115686: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 36ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:05:42.211482: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:42.211807: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:42.303661: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:42.303987: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:42.397124: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:42.397449: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 39ms/step

2023-09-06 00:05:42.489815: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:42.490139: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:42.588951: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:42.589288: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:42.682525: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:42.682868: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:05:42.776037: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:42.776366: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:42.867986: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:42.868316: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:42.959427: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:42.959756: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:05:43.051406: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:43.051733: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:43.158218: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:43.158542: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:05:43.263920: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:43.264243: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:43.367472: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:43.367809: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 40ms/step
1/1 [==============================] - 0s 39ms/step

2023-09-06 00:05:43.468727: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:43.469073: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:43.566383: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:43.566727: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:43.665698: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:43.666036: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:05:43.762872: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:43.763212: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:43.857936: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:43.858271: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:05:43.963812: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:43.964139: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:44.067746: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:44.068071: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:44.160952: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:44.161277: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 39ms/step

2023-09-06 00:05:44.254039: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:44.254363: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:44.353311: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:44.353651: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:44.447336: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:44.447671: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:05:44.542250: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:44.542580: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:44.636530: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:44.636862: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:44.728780: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:44.729105: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 37ms/step

2023-09-06 00:05:44.821072: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:44.821399: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:44.913627: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:44.913952: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:45.017967: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:45.018315: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 39ms/step

2023-09-06 00:05:45.115976: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:45.116341: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:45.226459: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:45.226801: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 39ms/step

2023-09-06 00:05:45.322914: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:45.323251: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:45.431101: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:45.431432: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:05:45.528923: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:45.529254: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:45.627341: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:45.627671: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:45.724981: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:45.725305: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:05:45.821128: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:45.821455: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:45.917338: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:45.917665: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:46.012486: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:46.012808: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 39ms/step

2023-09-06 00:05:46.125837: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:46.126179: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:46.226529: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:46.226900: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:05:46.332830: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:46.333154: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:46.428690: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:46.429020: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:46.523659: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:46.523983: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 37ms/step
1/1 [==============================] - 0s 37ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:05:46.617863: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:46.618187: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:46.721019: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:46.721344: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:05:46.826317: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:46.826645: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:46.921114: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:46.921439: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:47.022972: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:47.023312: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 40ms/step
1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 39ms/step

2023-09-06 00:05:47.131615: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:47.131954: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:47.236314: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:47.236643: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:05:47.340527: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:47.340859: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:47.437532: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:47.437860: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:47.533051: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:47.533377: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 37ms/step
1/1 [==============================] - 0s 37ms/step

2023-09-06 00:05:47.637385: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:47.637708: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:47.738977: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:47.739304: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:47.834606: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:47.834946: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:05:47.936651: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:47.936990: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:48.034484: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:48.034824: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:48.130387: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:48.130712: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:05:48.234792: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:48.235129: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:48.328280: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:48.328607: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:48.422866: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:48.423193: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:05:48.516327: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:48.516651: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:48.608340: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:48.608664: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:48.698767: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:48.699101: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 39ms/step

2023-09-06 00:05:48.802705: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:48.803065: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:48.895860: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:48.896190: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:48.988272: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:48.988599: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 37ms/step

2023-09-06 00:05:49.091950: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:49.092279: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:49.189367: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:49.189690: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:49.283156: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:49.283480: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:05:49.377874: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:49.378196: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:49.470052: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:49.470380: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:49.574452: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:49.574777: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 39ms/step

2023-09-06 00:05:49.675994: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:49.676337: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:49.780998: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:49.781331: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:05:49.879615: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:49.879941: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:49.985511: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:49.985840: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:05:50.081283: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:50.081612: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:50.185630: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:50.185958: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:05:50.290088: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:50.290419: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:50.386657: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:50.387029: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:50.482722: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:50.483105: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:05:50.586561: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:50.586922: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:50.684963: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:50.685299: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:50.780638: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:50.780968: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 37ms/step
1/1 [==============================] - 0s 37ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:05:50.875764: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:50.876093: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:50.978641: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:50.978976: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 37ms/step
1/1 [==============================] - 0s 37ms/step

2023-09-06 00:05:51.082859: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:51.083185: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:51.178101: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:51.178425: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:51.270089: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:51.270416: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 37ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:05:51.362408: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:51.362795: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:51.459979: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:51.460319: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:51.552842: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:51.553174: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 41ms/step
1/1 [==============================] - 0s 40ms/step

2023-09-06 00:05:51.661166: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:51.661521: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:51.769302: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:51.769642: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:05:51.872011: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:51.872337: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:51.978253: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:51.978583: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:05:52.074575: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:52.074920: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:52.173841: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:52.174171: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:52.271146: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:52.271471: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 40ms/step

2023-09-06 00:05:52.376238: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:52.376583: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:52.484503: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:52.484847: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:05:52.583204: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:52.583533: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:52.681355: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:52.681688: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:52.780659: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:52.780989: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 39ms/step

2023-09-06 00:05:52.888261: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:52.888589: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:52.993727: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:52.994055: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 53ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:05:53.105304: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:53.105675: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:53.220520: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:53.220851: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 47ms/step
1/1 [==============================] - 0s 41ms/step

2023-09-06 00:05:53.335322: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:53.335667: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:53.462311: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:53.462677: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 39ms/step

2023-09-06 00:05:53.574016: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:53.574347: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:53.671885: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:53.672224: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:53.773985: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:53.774314: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:05:53.872669: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:53.872992: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:53.971974: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:53.972301: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:54.070062: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:54.070384: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 39ms/step

2023-09-06 00:05:54.166055: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:54.166381: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:54.271074: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:54.271420: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 40ms/step

2023-09-06 00:05:54.369447: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:54.369787: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:54.477618: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:54.477949: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 40ms/step
1/1 [==============================] - 0s 39ms/step

2023-09-06 00:05:54.589021: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:54.589384: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:54.700324: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:54.700658: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 39ms/step

2023-09-06 00:05:54.810397: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:54.810724: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:54.920653: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:54.920980: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 55ms/step
1/1 [==============================] - 0s 39ms/step

2023-09-06 00:05:55.028950: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:55.029274: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:55.164802: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:55.165159: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 41ms/step
1/1 [==============================] - 0s 40ms/step

2023-09-06 00:05:55.293877: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:55.294229: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:55.407764: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:55.408105: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 40ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:05:55.511204: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:55.511533: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:55.622186: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:55.622521: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 39ms/step

2023-09-06 00:05:55.731372: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:55.731698: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:55.840383: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:55.840709: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 39ms/step

2023-09-06 00:05:55.954103: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:55.954433: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:56.066364: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:56.066703: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 39ms/step

2023-09-06 00:05:56.164117: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:56.164444: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:56.278349: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:56.278691: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 40ms/step
1/1 [==============================] - 0s 40ms/step

2023-09-06 00:05:56.378142: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:56.378482: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:56.483621: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:56.483953: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 39ms/step

2023-09-06 00:05:56.585388: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:56.585720: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:56.694467: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:56.694796: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 39ms/step

2023-09-06 00:05:56.804045: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:56.804376: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:56.903899: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:56.904228: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:05:57.010783: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:57.011123: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:57.108465: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:57.108793: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 45ms/step
1/1 [==============================] - 0s 39ms/step

2023-09-06 00:05:57.217497: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:57.217840: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:57.340769: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:57.341140: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:05:57.437978: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:57.438344: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:57.531812: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:57.532146: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:57.626868: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:57.627215: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 36ms/step

2023-09-06 00:05:57.720174: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:57.720559: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:57.826765: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:57.827095: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 43ms/step

2023-09-06 00:05:57.930023: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:57.930352: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:58.027640: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:58.027967: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 40ms/step
1/1 [==============================] - 0s 39ms/step

2023-09-06 00:05:58.142476: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:58.142838: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:58.242706: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:58.243058: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:58.342432: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:58.342763: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 39ms/step

2023-09-06 00:05:58.448042: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:58.448374: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:58.555064: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:58.555393: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:05:58.653008: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:58.653336: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:58.748595: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:58.748923: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 43ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:05:58.864680: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:58.865026: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:58.972997: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:58.973324: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:05:59.087528: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:59.087873: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:59.183875: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:59.184208: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:59.276801: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:59.277128: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 36ms/step

2023-09-06 00:05:59.370331: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:59.370721: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:59.476894: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:59.477220: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:59.568300: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:59.568626: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 37ms/step
1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 37ms/step

2023-09-06 00:05:59.661863: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:59.662190: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:59.756341: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:59.756667: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:59.862333: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:59.862661: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 39ms/step

2023-09-06 00:05:59.968384: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:05:59.968724: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:00.067469: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:00.067803: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:00.167287: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:00.167618: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:06:00.276592: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:00.276923: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:00.385205: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:00.385531: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 37ms/step

2023-09-06 00:06:00.492032: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:00.492354: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:00.589216: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:00.589543: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:00.684198: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:00.684523: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 37ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:06:00.791561: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:00.791929: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:00.893946: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:00.894318: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 44ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:06:01.000969: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:01.001305: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:01.100341: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:01.100670: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:01.194628: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:01.194971: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 37ms/step
1/1 [==============================] - 0s 37ms/step

2023-09-06 00:06:01.288355: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:01.288685: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:01.381274: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:01.381599: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:01.474987: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:01.475311: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 37ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:06:01.569129: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:01.569454: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:01.675205: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:01.675528: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:06:01.775594: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:01.776010: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:01.879868: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:01.880209: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:06:01.987779: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:01.988108: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:02.084932: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:02.085263: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:06:02.190933: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:02.191259: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:02.288305: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:02.288628: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:06:02.393767: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:02.394094: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:02.499575: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:02.499898: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 39ms/step

2023-09-06 00:06:02.598501: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:02.598841: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:02.701564: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:02.701905: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 40ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:06:02.800776: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:02.801109: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:02.911808: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:02.912141: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:06:03.010404: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:03.010739: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:03.109412: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:03.109743: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 37ms/step

2023-09-06 00:06:03.216899: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:03.217224: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:03.314625: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:03.314962: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:06:03.422849: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:03.423178: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:03.520251: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:03.520577: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 40ms/step
1/1 [==============================] - 0s 39ms/step

2023-09-06 00:06:03.627402: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:03.627742: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:03.726432: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:03.726767: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:03.826701: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:03.827048: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:06:03.925098: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:03.925429: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:04.023978: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:04.024304: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:06:04.131005: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:04.131336: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:04.228707: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:04.229032: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:06:04.335256: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:04.335579: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:04.431778: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:04.432102: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:04.532951: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:04.533289: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:06:04.638124: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:04.638463: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:04.743263: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:04.743591: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:04.838845: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:04.839179: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:06:04.944573: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:04.944902: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:05.046848: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:05.047181: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:05.144235: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:05.144562: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:06:05.235440: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:05.235762: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:05.327936: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:05.328261: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:05.426769: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:05.427120: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:06:05.519972: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:05.520310: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:05.623155: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:05.623487: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:05.717711: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:05.718043: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:06:05.808773: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:05.809102: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:05.900100: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:05.900427: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:06.003696: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:06.004025: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:06:06.100056: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:06.100384: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:06.195294: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:06.195620: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:06.297939: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:06.298281: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 39ms/step

2023-09-06 00:06:06.395822: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:06.396158: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:06.491294: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:06.491624: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:06.589825: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:06.590157: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 39ms/step

2023-09-06 00:06:06.694403: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:06.694729: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:06.798623: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:06.798962: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:06.894355: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:06.894681: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:06:06.999183: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:06.999513: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:07.102540: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:07.102904: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 40ms/step
1/1 [==============================] - 0s 39ms/step

2023-09-06 00:06:07.214825: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:07.215170: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:07.309118: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:07.309456: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:07.402341: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:07.402676: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 41ms/step
1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:06:07.501476: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:07.501807: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:07.606595: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:07.606931: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:07.701264: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:07.701587: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:06:07.797115: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:07.797441: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:07.902345: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:07.902673: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:07.996906: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:07.997234: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:06:08.100823: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:08.101237: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:08.198547: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:08.198900: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:08.296590: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:08.296918: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:06:08.401997: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:08.402326: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:08.507523: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:08.507849: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:06:08.603734: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:08.604064: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:08.700717: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:08.701039: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:08.795785: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:08.796111: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 40ms/step

2023-09-06 00:06:08.892719: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:08.893043: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:08.993721: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:08.994065: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:09.089533: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:09.089866: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:06:09.194446: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:09.194777: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:09.292761: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:09.293093: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 51ms/step

2023-09-06 00:06:09.399470: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:09.399799: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:09.494266: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:09.494596: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:06:09.604268: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:09.604593: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:09.710290: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:09.710617: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 39ms/step

2023-09-06 00:06:09.807102: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:09.807428: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:09.909982: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:09.910323: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:10.006467: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:10.006803: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:06:10.099235: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:10.099563: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:10.191598: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:10.191927: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:10.283251: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:10.283575: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 37ms/step

2023-09-06 00:06:10.389342: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:10.389672: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:10.485462: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:10.485792: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:10.581707: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:10.582043: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 37ms/step
1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 40ms/step

2023-09-06 00:06:10.687740: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:10.688065: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:10.790137: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:10.790477: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 39ms/step

2023-09-06 00:06:10.900100: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:10.900438: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:10.997093: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:10.997422: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 39ms/step

2023-09-06 00:06:11.105123: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:11.105456: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:11.201935: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:11.202262: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:11.298121: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:11.298447: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:06:11.394758: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:11.395101: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:11.499839: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:11.500164: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:11.594669: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:11.595010: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 40ms/step
1/1 [==============================] - 0s 39ms/step

2023-09-06 00:06:11.705716: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:11.706060: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:11.803745: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:11.804078: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:11.902458: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:11.902791: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:06:12.009342: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:12.009674: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:12.109459: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:12.109786: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 40ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:06:12.214784: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:12.215136: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:12.323075: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:12.323400: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:06:12.421470: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:12.421795: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:12.528644: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:12.528970: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 39ms/step

2023-09-06 00:06:12.639996: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:12.640340: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:12.746448: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:12.746782: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:06:12.844544: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:12.844871: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:12.941175: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:12.941505: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:13.036149: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:13.036477: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 37ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:06:13.130350: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:13.130678: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:13.222092: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:13.222417: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:13.314847: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:13.315183: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 39ms/step

2023-09-06 00:06:13.421392: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:13.421730: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:13.523913: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:13.524265: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:13.620423: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:13.620768: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:06:13.719104: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:13.719446: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:13.824751: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:13.825092: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:06:13.929620: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:13.929946: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:14.034646: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:14.034982: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:14.130293: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:14.130621: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:06:14.234264: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:14.234590: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:14.331029: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:14.331357: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 39ms/step

2023-09-06 00:06:14.442395: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:14.442739: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:14.540625: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:14.540957: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:06:14.648730: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:14.649082: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:14.747001: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:14.747333: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:06:14.851327: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:14.851651: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:14.945895: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:14.946220: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:15.042036: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:15.042358: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:06:15.145416: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:15.145740: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:15.240245: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:15.240567: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 39ms/step

2023-09-06 00:06:15.353526: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:15.353871: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:15.452536: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:15.452871: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 39ms/step

2023-09-06 00:06:15.560078: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:15.560450: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:15.654766: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:15.655136: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:15.748724: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:15.749051: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 37ms/step
1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:06:15.839619: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:15.839945: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:15.930686: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:15.931022: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:16.023564: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:16.023891: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 37ms/step
1/1 [==============================] - 0s 37ms/step
1/1 [==============================] - 0s 39ms/step

2023-09-06 00:06:16.115702: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:16.116025: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:16.225031: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:16.225371: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 39ms/step

2023-09-06 00:06:16.322103: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:16.322441: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:16.430395: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:16.430724: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:06:16.527261: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:16.527589: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:16.625871: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:16.626198: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:16.723457: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:16.723782: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 39ms/step

2023-09-06 00:06:16.831380: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:16.831704: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:16.937914: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:16.938237: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 39ms/step

2023-09-06 00:06:17.044570: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:17.044894: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:17.147388: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:17.147728: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:06:17.253886: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:17.254222: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:17.351829: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:17.352156: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:17.447593: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:17.447923: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:06:17.545503: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:17.545829: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:17.642736: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:17.643079: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:06:17.748411: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:17.748737: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:17.853161: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:17.853488: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 39ms/step

2023-09-06 00:06:17.950652: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:17.950995: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:18.053714: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:18.054058: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 37ms/step

2023-09-06 00:06:18.153286: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:18.153620: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:18.252080: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:18.252412: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:18.347610: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:18.347940: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 37ms/step
1/1 [==============================] - 0s 37ms/step
1/1 [==============================] - 0s 36ms/step

2023-09-06 00:06:18.444936: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:18.445261: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:18.538580: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:18.538923: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:18.633743: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:18.634069: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 37ms/step
1/1 [==============================] - 0s 37ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:06:18.729847: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:18.730173: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:18.834551: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:18.834883: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 40ms/step
1/1 [==============================] - 0s 39ms/step

2023-09-06 00:06:18.940884: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:18.941225: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:19.049807: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:19.050143: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 52ms/step

2023-09-06 00:06:19.150874: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:19.151205: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:19.250166: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:19.250496: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 54ms/step

2023-09-06 00:06:19.371927: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:19.372259: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:19.478293: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:19.478618: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:06:19.590627: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:19.590964: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:19.684492: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:19.684817: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:19.777376: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:19.777700: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 37ms/step
1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 39ms/step

2023-09-06 00:06:19.876495: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:19.876834: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:19.971006: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:19.971343: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:06:20.077610: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:20.077941: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:20.175255: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:20.175582: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:20.271503: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:20.271827: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:06:20.377751: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:20.378078: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:20.473384: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:20.473708: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:20.569377: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:20.569699: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 39ms/step

2023-09-06 00:06:20.668744: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:20.669063: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:20.782437: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:20.782783: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 39ms/step

2023-09-06 00:06:20.890664: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:20.891009: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:20.997611: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:20.997941: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:06:21.105391: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:21.105719: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:21.204692: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:21.205015: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:06:21.312369: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:21.312695: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:21.418955: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:21.419284: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 37ms/step

2023-09-06 00:06:21.518956: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:21.519283: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:21.623925: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:21.624253: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 40ms/step
1/1 [==============================] - 0s 39ms/step

2023-09-06 00:06:21.726622: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:21.726979: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:21.835476: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:21.835809: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 39ms/step
1/1 [==============================] - 0s 38ms/step

2023-09-06 00:06:21.934343: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:21.934672: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:22.032201: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:22.032530: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:22.128188: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:22.128513: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 37ms/step
1/1 [==============================] - 0s 38ms/step
1/1 [==============================] - 0s 37ms/step

2023-09-06 00:06:22.232920: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:22.233243: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:22.327935: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:22.328258: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:22.423227: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]
2023-09-06 00:06:22.423551: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_10' with dtype float and shape [1,125,125,3]
	 [[{{node Placeholder/_10}}]]

1/1 [==============================] - 0s 37ms/step

In [6]:
# 모든 행 출력
pd.set_option('display.max_rows', None)

df

,name,A-sky,B-pattern,C-thick-dark,D-thick-white,E-veil
0,panel1_NVR_ch1_jpg_20230322164400.jpg,4.424425e-06,1.453420e-03,12.288953,85.415357,2.294232
1,panel1_NVR_ch1_jpg_20230322164800.jpg,1.774776e-08,5.227813e-03,1.871882,97.819990,0.302909
2,panel1_NVR_ch1_jpg_20230322165200.jpg,1.740531e-09,3.397775e-02,39.807442,58.484578,1.673997
3,panel1_NVR_ch1_jpg_20230322165600.jpg,3.556563e-11,4.018900e-01,0.855924,98.492891,0.249288
4,panel1_NVR_ch1_jpg_20230322170200.jpg,2.254395e-18,3.120831e-02,52.248859,47.716528,0.003402
5,panel1_NVR_ch1_jpg_20230329091700.jpg,2.822049e-02,1.796948e-04,14.607355,0.442075,84.922165
6,panel1_NVR_ch1_jpg_20230329092100.jpg,2.369767e-03,3.498847e-05,20.090453,0.339599,79.567534
7,panel1_NVR_ch1_jpg_20230329092500.jpg,1.896276e-03,2.181109e-04,29.134721,0.314629,70.548540
8,panel1_NVR_ch1_jpg_20230329092900.jpg,6.471734e-05,1.116257e-04,49.240392,0.063785,50.695640
9,panel1_NVR_ch1_jpg_20230329093300.jpg,3.099385e-05,1.818397e-04,74.216068,0.032860,25.750858
10,panel1_NVR_ch1_jpg_20230329093700.jpg,9.338147e-06,1.163263e-03,86.476457,0.059971,13.462400
11,panel1_NVR_ch1_jpg_20230329094200.jpg,4.871554e-06,7.781656e-04,39.441219,0.033145,60.524851
12,panel1_NVR_ch1_jpg_20230329141400.jpg,3.838499e-03,1.216008e+00,15.698999,4.774864,78.306288
13,panel1_NVR_ch1_jpg_20230329141800.jpg,2.876131e-03,1.135739e+00,13.572277,3.274671,82.014436
14,panel1_NVR_ch1_jpg_20230329142200.jpg,6.751944e-03,1.182922e+00,15.731281,3.081800,79.997247
15,panel1_NVR_ch1_jpg_20230329142600.jpg,9.952065e-03,1.467593e+00,12.762883,3.229250,82.530314
16,panel1_NVR_ch1_jpg_20230329143000.jpg,4.263642e-02,2.935632e+00,10.866613,3.301825,82.853287
17,panel1_NVR_ch1_jpg_20230329143400.jpg,5.119003e-02,3.626727e+00,11.182767,2.817329,82.321990
18,panel1_NVR_ch1_jpg_20230329144200.jpg,5.187550e-01,4.000583e+00,14.370240,4.274743,76.835668
19,panel1_NVR_ch1_jpg_20230329143800.jpg,1.703914e-01,3.232540e+00,12.238962,2.874035,81.484067
20,panel1_NVR_ch1_jpg_20230329144600.jpg,3.598477e-01,5.864248e+00,8.056875,4.331289,81.387746
21,panel1_NVR_ch1_jpg_20230329145000.jpg,6.641469e-01,5.580687e+00,14.539328,6.038396,73.177433
22,panel1_NVR_ch1_jpg_20230329145400.jpg,2.190521e-01,4.836385e+00,20.210148,5.720355,69.014060
23,panel1_NVR_ch1_jpg_20230329145800.jpg,8.250570e-02,3.319587e+00,29.038036,5.844899,61.714971
24,panel1_NVR_ch1_jpg_20230329164100.jpg,3.519209e-03,1.105374e-01,54.112697,16.863148,28.910094
25,panel1_NVR_ch1_jpg_20230329150700.jpg,2.919647e-02,2.097867e+00,32.838190,6.272288,58.762461
26,panel1_NVR_ch1_jpg_20230329164500.jpg,1.594951e-03,7.594120e-02,52.216446,20.965084,26.740938
27,panel1_NVR_ch1_jpg_20230329164900.jpg,1.532679e-03,5.864067e-02,55.143827,20.902529,23.893471
28,panel1_NVR_ch1_jpg_20230329165300.jpg,1.444449e-03,4.859993e-02,52.134770,22.536141,25.279042
29,panel1_NVR_ch1_jpg_20230329165700.jpg,6.649193e-04,3.947956e-02,56.957668,21.182008,21.820180
30,panel1_NVR_ch1_jpg_20230329170000.jpg,3.946557e-04,3.046454e-02,57.557851,23.173979,19.237307
31,panel1_NVR_ch1_jpg_20230329170500.jpg,1.103302e-04,1.822172e-02,58.788228,23.754573,17.438869
32,panel1_NVR_ch1_jpg_20230329171000.jpg,6.610385e-05,1.245022e-02,50.003946,32.911584,17.071952
33,panel1_NVR_ch1_jpg_20230329171500.jpg,3.143502e-05,7.486861e-03,46.286893,38.984829,14.720757
34,panel1_NVR_ch1_jpg_20230329172100.jpg,1.905029e-05,4.212831e-03,47.322741,40.920568,11.752463
35,panel1_NVR_ch1_jpg_20230329172800.jpg,1.010764e-05,3.142183e-03,47.741035,42.857212,9.398597
36,panel1_NVR_ch1_jpg_20230403093600.jpg,1.791736e-02,5.780106e-04,5.633583,1.671441,92.676473
37,panel1_NVR_ch1_jpg_20230403094000.jpg,2.225627e-02,7.235465e-04,2.731198,1.491567,95.754254
38,panel1_NVR_ch1_jpg_20230403094500.jpg,6.768539e-02,3.651939e-03,3.993225,1.216308,94.719136
39,panel1_NVR_ch1_jpg_20230403094900.jpg,1.776557e-01,1.532343e-02,2.053736,1.007080,96.746206
40,panel1_NVR_ch1_jpg_20230403095300.jpg,2.602781e-02,5.130605e-02,1.416101,0.639042,97.867525
41,panel1_NVR_ch1_jpg_20230403095700.jpg,2.418870e-02,7.256549e-03,9.442911,1.148982,89.376670
42,panel1_NVR_ch1_jpg_20230403100100.jpg,5.857380e-02,1.531530e-02,4.791831,1.560253,93.574023
43,panel1_NVR_ch1_jpg_20230403100600.jpg,6.845430e-03,1.217546e-01,62.464148,1.556262,35.850996
44,panel1_NVR_ch1_jpg_20230403101100.jpg,8.742585e-03,1.410379e+00,47.415704,1.939661,49.225512
45,panel1_NVR_ch1_jpg_20230403101500.jpg,5.170496e-03,1.063354e+00,74.121261,6.877874,17.932339
46,panel1_NVR_ch1_jpg_20230403135000.jpg,3.083083e-04,2.112794e-01,19.256917,0.638821,79.892677
47,panel1_NVR_ch1_jpg_20230403135400.jpg,4.911980e-04,3.249156e-01,17.862567,0.754493,81.057537
48,panel1_NVR_ch1_jpg_20230403135800.jpg,4.400047e-04,2.613639e-01,19.705711,0.671070,79.361403
49,panel1_NVR_ch1_jpg_20230403140200.jpg,3.592013e-04,2.608912e-01,15.691625,0.619963,83.427161
50,panel1_NVR_ch1_jpg_20230403140600.jpg,5.600901e-04,4.748003e-01,16.647460,1.124523,81.752664
51,panel1_NVR_ch1_jpg_20230403141000.jpg,4.223438e-04,5.981638e-01,11.971211,1.482599,85.947609
52,panel1_NVR_ch1_jpg_20230403141400.jpg,6.361059e-04,7.630698e-01,13.093534,1.543350,84.599411
53,panel1_NVR_ch1_jpg_20230403141800.jpg,6.882036e-04,8.739987e-01,11.289545,2.106412,85.729355
54,panel1_NVR_ch1_jpg_20230403142200.jpg,4.596823e-04,7.572423e-01,14.941551,2.114229,82.186520
55,panel1_NVR_ch1_jpg_20230403142600.jpg,6.000389e-04,7.741673e-01,9.525012,1.818221,87.882006
56,panel1_NVR_ch1_jpg_20230403144400.jpg,1.461675e-03,1.509868e+00,9.099022,3.458317,85.931325
57,panel1_NVR_ch1_jpg_20230403144800.jpg,2.965355e-03,1.811991e+00,8.270880,3.116184,86.797976
58,panel1_NVR_ch1_jpg_20230403145200.jpg,2.450753e-03,1.688382e+00,11.669382,4.538660,82.101119
59,panel1_NVR_ch1_jpg_20230403145600.jpg,2.914597e-03,2.079710e+00,9.885771,5.127930,82.903671
60,panel1_NVR_ch1_jpg_20230403150000.jpg,1.968342e-03,2.231079e+00,8.927087,6.527214,82.312649
61,panel1_NVR_ch1_jpg_20230403150400.jpg,1.904530e-03,1.696621e+00,10.178253,5.894491,82.228738
62,panel1_NVR_ch1_jpg_20230403150800.jpg,4.326362e-03,2.542258e+00,7.794107,4.394719,85.264575
63,panel1_NVR_ch1_jpg_20230403151200.jpg,4.009394e-03,1.663582e+00,11.018854,4.833310,82.480240
64,panel1_NVR_ch1_jpg_20230403151600.jpg,7.189852e-03,1.911006e+00,8.551525,3.551120,85.979158
65,panel1_NVR_ch1_jpg_20230403152000.jpg,7.739892e-03,1.705130e+00,10.771186,4.441151,83.074790
66,panel1_NVR_ch1_jpg_20230403164700.jpg,1.639883e-01,1.325867e-01,14.544374,31.100151,54.058897
67,panel1_NVR_ch1_jpg_20230403165100.jpg,1.070737e-01,5.371594e-02,14.785816,42.428339,42.625058
68,panel1_NVR_ch1_jpg_20230403165500.jpg,6.832765e-02,2.359692e-02,16.293219,48.364031,35.250825
69,panel1_NVR_ch1_jpg_20230403165900.jpg,1.053826e-01,2.919897e-02,14.567219,54.204184,31.094015
70,panel1_NVR_ch1_jpg_20230403170300.jpg,7.364426e-02,1.597292e-02,10.999168,64.048642,24.862579
71,panel1_NVR_ch1_jpg_20230403170700.jpg,3.573952e-02,5.404059e-03,7.541744,77.347225,15.069886
72,panel1_NVR_ch1_jpg_20230403171200.jpg,4.708691e-02,6.463388e-03,6.921506,74.534184,18.490760
73,panel1_NVR_ch1_jpg_20230403171800.jpg,2.299533e-02,3.004873e-03,7.937783,77.091306,14.944910
74,panel1_NVR_ch1_jpg_20230403172300.jpg,2.699021e-02,4.006873e-03,6.265026,80.717373,12.986612
75,panel1_NVR_ch1_jpg_20230403172700.jpg,2.107287e-02,2.265674e-03,4.066035,86.321539,9.589091
76,panel1_NVR_ch1_jpg_20230403173100.jpg,8.905363e-03,1.239747e-03,3.565999,89.750397,6.673455
77,panel1_NVR_ch1_jpg_20230410091800.jpg,2.787152e-05,8.975111e-06,15.392289,0.067759,84.539920
78,panel1_NVR_ch1_jpg_20230410091900.jpg,3.369844e-05,1.126064e-05,13.496879,0.058244,86.444837
79,panel1_NVR_ch1_jpg_20230410092000.jpg,2.273913e-05,1.095795e-05,16.383708,0.057440,83.558816
80,panel1_NVR_ch1_jpg_20230410092200.jpg,1.570255e-04,5.008088e-05,5.655973,0.086672,94.257146
81,panel1_NVR_ch1_jpg_20230410092400.jpg,1.923528e-05,1.192577e-05,21.181010,0.052608,78.766346
82,panel1_NVR_ch1_jpg_20230410092300.jpg,2.011637e-05,1.235854e-05,19.649309,0.055339,80.295312
83,panel1_NVR_ch1_jpg_20230410092600.jpg,1.118217e-05,9.034185e-06,27.681848,0.066116,72.252023
84,panel1_NVR_ch1_jpg_20230410092700.jpg,1.745340e-04,4.069786e-05,4.462116,0.076143,95.461524
85,panel1_NVR_ch1_jpg_20230410092800.jpg,1.114521e-05,8.775362e-06,27.338046,0.046824,72.615117
86,panel1_NVR_ch1_jpg_20230410093000.jpg,9.890410e-05,3.477116e-05,12.081892,0.089728,87.828261
87,panel1_NVR_ch1_jpg_20230410093100.jpg,1.723800e-05,1.704627e-05,25.936046,0.054487,74.009430
88,panel1_NVR_ch1_jpg_20230410093200.jpg,1.359711e-04,3.392261e-05,9.020627,0.093982,90.885216
89,panel1_NVR_ch1_jpg_20230410093400.jpg,1.155244e-05,1.122008e-05,36.538357,0.047709,63.413906
90,panel1_NVR_ch1_jpg_20230410093500.jpg,1.054034e-05,1.077335e-05,38.518032,0.053296,61.428666
91,panel1_NVR_ch1_jpg_20230410093600.jpg,6.795920e-06,7.182400e-06,34.079725,0.049826,65.870434
92,panel1_NVR_ch1_jpg_20230410093800.jpg,1.635739e-05,1.342584e-05,27.942175,0.048861,72.008926
93,panel1_NVR_ch1_jpg_20230410093900.jpg,9.176249e-06,1.644142e-05,47.065741,0.037942,52.896297
94,panel1_NVR_ch1_jpg_20230410094000.jpg,1.561557e-05,1.251109e-05,31.887111,0.047372,68.065482
95,panel1_NVR_ch1_jpg_20230410094200.jpg,1.608052e-05,1.443476e-05,32.319564,0.058503,67.621911
96,panel1_NVR_ch1_jpg_20230410094300.jpg,8.812340e-06,1.166139e-05,54.588151,0.028902,45.382923
97,panel1_NVR_ch1_jpg_20230410094400.jpg,1.476358e-05,2.225549e-05,41.533598,0.037040,58.429331
98,panel1_NVR_ch1_jpg_20230410094600.jpg,2.229236e-05,2.097287e-05,46.142986,0.070527,53.786445
99,panel1_NVR_ch1_jpg_20230410094700.jpg,1.739259e-05,1.725684e-05,40.904599,0.053018,59.042352
100,panel1_NVR_ch1_jpg_20230410094800.jpg,2.414326e-05,1.761994e-05,58.080178,0.080087,41.839689
101,panel1_NVR_ch1_jpg_20230410095000.jpg,1.727138e-05,1.759538e-05,65.074331,0.065785,34.859842
102,panel1_NVR_ch1_jpg_20230410095100.jpg,1.574387e-05,3.529550e-05,68.664765,0.054779,31.280401
103,panel1_NVR_ch1_jpg_20230410095200.jpg,1.538699e-05,4.430265e-05,71.702397,0.054491,28.243059
104,panel1_NVR_ch1_jpg_20230410095400.jpg,6.434418e-06,3.909479e-05,69.490397,0.028961,30.480599
105,panel1_NVR_ch1_jpg_20230410095500.jpg,7.133691e-06,3.385719e-05,69.868034,0.021888,30.110034
106,panel1_NVR_ch1_jpg_20230410095600.jpg,4.412535e-06,2.908113e-05,86.435747,0.021982,13.542241
107,panel1_NVR_ch1_jpg_20230410134300.jpg,7.763706e-02,2.631747e+00,11.491217,1.933208,83.866185
108,panel1_NVR_ch1_jpg_20230410134400.jpg,4.126950e-02,1.437458e+00,9.689444,1.194669,87.637162
109,panel1_NVR_ch1_jpg_20230410134500.jpg,4.169288e-02,1.366444e+00,8.599284,1.079297,88.913274
110,panel1_NVR_ch1_jpg_20230410134700.jpg,3.405167e-02,1.592002e+00,8.799180,1.432150,88.142622
111,panel1_NVR_ch1_jpg_20230410134800.jpg,3.628306e-02,1.685452e+00,10.035538,1.628053,86.614674
112,panel1_NVR_ch1_jpg_20230410134900.jpg,4.026903e-02,1.469139e+00,8.189521,1.098789,89.202279
113,panel1_NVR_ch1_jpg_20230410135100.jpg,4.127917e-02,1.738282e+00,9.069590,1.375025,87.775820
114,panel1_NVR_ch1_jpg_20230410135200.jpg,4.863203e-02,1.801178e+00,7.226922,1.189641,89.733624
115,panel1_NVR_ch1_jpg_20230410135300.jpg,3.319642e-02,1.804859e+00,9.290229,1.497369,87.374353
116,panel1_NVR_ch1_jpg_20230410135500.jpg,3.313852e-02,1.767642e+00,7.993892,1.365658,88.839674
117,panel1_NVR_ch1_jpg_20230410135600.jpg,3.930766e-02,1.857742e+00,7.580578,1.413068,89.109302
118,panel1_NVR_ch1_jpg_20230410135700.jpg,4.563314e-02,1.769172e+00,6.795342,1.164869,90.224981
119,panel1_NVR_ch1_jpg_20230410135900.jpg,6.559048e-02,2.292997e+00,8.193190,1.591522,87.856692
120,panel1_NVR_ch1_jpg_20230410140000.jpg,6.968274e-02,2.510869e+00,8.408308,1.779691,87.231451
121,panel1_NVR_ch1_jpg_20230410140100.jpg,7.859954e-02,2.522289e+00,9.009389,1.738585,86.651134
122,panel1_NVR_ch1_jpg_20230410140300.jpg,8.368823e-02,2.798185e+00,12.630683,2.310535,82.176900
123,panel1_NVR_ch1_jpg_20230410140400.jpg,9.540973e-02,3.149823e+00,13.468838,2.845049,80.440879
124,panel1_NVR_ch1_jpg_20230410140500.jpg,8.884471e-02,3.101513e+00,12.806448,2.989034,81.014168
125,panel1_NVR_ch1_jpg_20230410140700.jpg,9.408890e-02,2.896564e+00,13.137130,2.757046,81.115168
126,panel1_NVR_ch1_jpg_20230410140800.jpg,1.126240e-01,3.057125e+00,13.767304,2.851900,80.211049
127,panel1_NVR_ch1_jpg_20230410140900.jpg,1.075300e-01,3.467121e+00,15.545081,3.197251,77.683014
128,panel1_NVR_ch1_jpg_20230410141100.jpg,1.588466e-01,3.377264e+00,18.259381,3.420267,74.784249
129,panel1_NVR_ch1_jpg_20230410141200.jpg,1.719958e-01,3.761055e+00,18.226188,3.818583,74.022174
130,panel1_NVR_ch1_jpg_20230410141300.jpg,1.841848e-01,3.560615e+00,18.567918,3.364401,74.322885
131,panel1_NVR_ch1_jpg_20230410141500.jpg,2.258330e-01,4.554579e+00,18.462087,4.254319,72.503179
132,panel1_NVR_ch1_jpg_20230410141600.jpg,2.417458e-01,4.346194e+00,19.194241,4.020225,72.197592
133,panel1_NVR_ch1_jpg_20230410141700.jpg,2.228340e-01,3.955650e+00,19.619705,3.787166,72.414643
134,panel1_NVR_ch1_jpg_20230410141900.jpg,2.680714e-01,4.227648e+00,19.741166,3.736722,72.026402
135,panel1_NVR_ch1_jpg_20230410142000.jpg,3.468114e-01,4.526630e+00,19.726448,3.653268,71.746844
136,panel1_NVR_ch1_jpg_20230410142100.jpg,2.756469e-01,4.926707e+00,17.825150,3.736508,73.235995
137,panel1_NVR_ch1_jpg_20230410142300.jpg,5.329127e-01,7.059247e+00,17.913549,5.638630,68.855661
138,panel1_NVR_ch1_jpg_20230410142400.jpg,4.835255e-01,6.987368e+00,16.501336,5.852120,70.175654
139,panel1_NVR_ch1_jpg_20230410142500.jpg,4.797779e-01,6.990974e+00,16.966841,5.631332,69.931078
140,panel1_NVR_ch1_jpg_20230410142700.jpg,4.587596e-01,6.642198e+00,18.435447,5.469006,68.994594
141,panel1_NVR_ch1_jpg_20230410142800.jpg,4.742520e-01,7.175308e+00,16.577865,5.634684,70.137888
142,panel1_NVR_ch1_jpg_20230410142900.jpg,5.055964e-01,6.741691e+00,17.721574,5.311909,69.719231
143,panel1_NVR_ch1_jpg_20230410143100.jpg,4.821172e-01,5.831650e+00,21.124253,4.149469,68.412519
144,panel1_NVR_ch1_jpg_20230410143200.jpg,3.621002e-01,4.643692e+00,21.258517,3.242002,70.493686
145,panel1_NVR_ch1_jpg_20230410143300.jpg,4.809887e-01,6.301842e+00,19.528635,4.429035,69.259501
146,panel1_NVR_ch1_jpg_20230410164800.jpg,2.720888e-03,3.399304e-03,44.636342,6.102423,49.255121
147,panel1_NVR_ch1_jpg_20230410164900.jpg,1.567867e-03,2.557297e-03,49.203625,6.165610,44.626641
148,panel1_NVR_ch1_jpg_20230410165200.jpg,3.902937e-03,1.289194e-03,48.624882,7.222971,44.146949
149,panel1_NVR_ch1_jpg_20230410165300.jpg,4.486883e-03,1.063645e-03,42.952618,11.318957,45.722866
150,panel1_NVR_ch1_jpg_20230410165000.jpg,1.525901e-03,1.739283e-03,51.920861,5.966140,42.109734
151,panel1_NVR_ch1_jpg_20230410165400.jpg,1.381996e-02,1.327218e-03,24.393405,17.826594,57.764858
152,panel1_NVR_ch1_jpg_20230410165700.jpg,4.220769e-03,1.850433e-03,32.300216,17.280662,50.413048
153,panel1_NVR_ch1_jpg_20230410165800.jpg,6.836222e-03,1.721200e-03,30.652842,15.731011,53.607589
154,panel1_NVR_ch1_jpg_20230410165900.jpg,5.192523e-03,1.753626e-03,34.120500,13.637243,52.235311
155,panel1_NVR_ch1_jpg_20230410170100.jpg,7.596779e-03,1.771823e-03,30.944350,14.652129,54.394144
156,panel1_NVR_ch1_jpg_20230410170200.jpg,9.385522e-03,1.783638e-03,29.463214,13.435686,57.089931
157,panel1_NVR_ch1_jpg_20230410170300.jpg,7.451421e-03,1.843572e-03,30.442896,14.950559,54.597247
158,panel1_NVR_ch1_jpg_20230410170500.jpg,5.545335e-03,1.913363e-03,34.887698,16.193829,48.911011
159,panel1_NVR_ch1_jpg_20230410170600.jpg,4.990013e-03,1.915207e-03,35.390624,16.518503,48.083964
160,panel1_NVR_ch1_jpg_20230410170700.jpg,6.736560e-03,2.058285e-03,32.567728,17.549075,49.874401
161,panel1_NVR_ch1_jpg_20230410170900.jpg,1.142657e-02,2.162022e-03,28.587022,18.372662,53.026724
162,panel1_NVR_ch1_jpg_20230410171000.jpg,1.126337e-02,2.053622e-03,27.334046,19.866012,52.786630
163,panel1_NVR_ch1_jpg_20230410171100.jpg,1.108692e-02,1.930999e-03,26.828766,20.900801,52.257413
164,panel1_NVR_ch1_jpg_20230410171300.jpg,1.786217e-02,2.200312e-03,25.121987,21.656464,53.201485
165,panel1_NVR_ch1_jpg_20230410171400.jpg,1.406122e-02,2.204748e-03,24.203900,25.172141,50.607693
166,panel1_NVR_ch1_jpg_20230410171500.jpg,1.324226e-02,2.391368e-03,24.150205,24.902396,50.931764
167,panel1_NVR_ch1_jpg_20230410171700.jpg,1.440284e-02,2.263974e-03,21.171084,31.800622,47.011626
168,panel1_NVR_ch1_jpg_20230410171800.jpg,1.223406e-02,2.273203e-03,20.355813,35.230660,44.399026
169,panel1_NVR_ch1_jpg_20230410171900.jpg,8.541473e-03,2.321752e-03,22.749703,35.729006,41.510436
170,panel1_NVR_ch1_jpg_20230410172100.jpg,7.439965e-03,2.328868e-03,20.354927,41.886300,37.749004
171,panel1_NVR_ch1_jpg_20230410172200.jpg,6.256060e-03,2.414170e-03,21.586828,43.758437,34.646055
172,panel1_NVR_ch1_jpg_20230410172300.jpg,7.787078e-03,2.314658e-03,21.031398,43.810251,35.148248
173,panel1_NVR_ch1_jpg_20230410172500.jpg,3.533492e-03,2.039532e-03,24.008714,47.948328,28.037375
174,panel1_NVR_ch1_jpg_20230410172600.jpg,2.613711e-03,2.176506e-03,25.072625,47.675753,27.246839
175,panel1_NVR_ch1_jpg_20230410172700.jpg,1.900854e-03,1.715537e-03,25.128755,50.356513,24.511105
176,panel1_NVR_ch1_jpg_20230410172900.jpg,1.895021e-03,1.357388e-03,24.473701,53.712726,21.810322
177,panel1_NVR_ch1_jpg_20230410173000.jpg,1.299343e-03,1.157042e-03,26.159167,54.609084,19.229300
178,panel1_NVR_ch1_jpg_20230410173100.jpg,1.105118e-03,1.238524e-03,26.742077,54.841489,18.414089
179,panel1_NVR_ch1_jpg_20230417092100.jpg,1.140832e-04,2.168754e-04,45.425990,0.193041,54.380631
180,panel1_NVR_ch1_jpg_20230417092200.jpg,1.861220e-04,2.288497e-04,34.198406,0.178713,65.622467
181,panel1_NVR_ch1_jpg_20230417092300.jpg,3.378884e-04,2.775289e-04,23.028643,0.184500,76.786238
182,panel1_NVR_ch1_jpg_20230417092500.jpg,1.222768e-04,3.123855e-04,43.310976,0.125666,56.562930
183,panel1_NVR_ch1_jpg_20230417092600.jpg,3.735075e-05,2.166973e-04,71.335536,0.069126,28.595084
184,panel1_NVR_ch1_jpg_20230417092700.jpg,8.700181e-05,5.721829e-04,53.093863,0.100618,46.804857
185,panel1_NVR_ch1_jpg_20230417092900.jpg,6.148397e-05,3.127134e-04,62.701905,0.093430,37.204298
186,panel1_NVR_ch1_jpg_20230417093000.jpg,8.566210e-05,3.262973e-04,59.139186,0.105751,40.754643
187,panel1_NVR_ch1_jpg_20230417093100.jpg,5.918027e-05,1.598474e-04,46.056128,0.094169,53.849488
188,panel1_NVR_ch1_jpg_20230417093300.jpg,3.695163e-05,1.929075e-04,62.702858,0.075619,37.221298
189,panel1_NVR_ch1_jpg_20230417093400.jpg,4.097476e-05,1.638401e-04,58.161283,0.077745,41.760767
190,panel1_NVR_ch1_jpg_20230417093500.jpg,4.989022e-05,2.582222e-04,51.612389,0.081975,48.305333
191,panel1_NVR_ch1_jpg_20230417093700.jpg,2.916368e-05,3.020197e-04,63.842982,0.052881,36.103806
192,panel1_NVR_ch1_jpg_20230417093800.jpg,2.953468e-05,2.845112e-04,62.551171,0.059341,37.389177
193,panel1_NVR_ch1_jpg_20230417093900.jpg,3.449283e-05,3.016678e-04,66.771406,0.052291,33.175972
194,panel1_NVR_ch1_jpg_20230417094100.jpg,1.117269e-05,1.094446e-04,83.066857,0.036115,16.896909
195,panel1_NVR_ch1_jpg_20230417094200.jpg,6.446479e-06,6.439299e-05,90.962619,0.022912,9.014403
196,panel1_NVR_ch1_jpg_20230417094300.jpg,8.619043e-06,9.683374e-05,88.063025,0.031254,11.905618
197,panel1_NVR_ch1_jpg_20230417094500.jpg,4.941639e-06,6.688279e-05,89.430302,0.023796,10.545833
198,panel1_NVR_ch1_jpg_20230417094600.jpg,4.806481e-06,4.865358e-05,89.860094,0.020257,10.119591
199,panel1_NVR_ch1_jpg_20230417094700.jpg,5.828270e-06,5.608125e-05,87.952805,0.022898,12.024233
200,panel1_NVR_ch1_jpg_20230417095000.jpg,2.996516e-05,2.076221e-04,78.710961,0.046935,21.241866
201,panel1_NVR_ch1_jpg_20230417094900.jpg,2.413142e-05,1.615713e-04,80.451351,0.040784,19.507681
202,panel1_NVR_ch1_jpg_20230417095100.jpg,4.133118e-05,2.823402e-04,76.974785,0.049020,22.975877
203,panel1_NVR_ch1_jpg_20230417095300.jpg,4.245948e-05,3.261524e-04,80.208325,0.040588,19.750713
204,panel1_NVR_ch1_jpg_20230417095400.jpg,8.529176e-06,9.454978e-05,93.693757,0.021364,6.284785
205,panel1_NVR_ch1_jpg_20230417095500.jpg,4.313020e-06,4.957880e-05,96.115983,0.014090,3.869871

In [7]:
df.to_csv(f"./classificationScore.csv")