## 일관성 있는 파일 만들기
### overview : 모든 데이터셋에서 있는 파일만 살리기

mask있는 폴더들 내에서 image와 mask 개수 통일 -> 생각해보니 할 필요없잖아..?



1. 모든 데이터들 다 불러오기
    - mask있는 폴더들은 mask따로 image따로
    - train, test, val은 합치기
1. 모든 데이터 list
    - 오염 origin 이미지
    - 오염 seg 이미지
    - 구름 origin 이미지
    - 구름 seg 이미지
    - table
    
    
table과 모든 것을 비교해서 다 없애고, table을 기준으로 나머지를 없앤다

### dataset folder 설정

In [1]:
dataset_folders = {
    "soiling" : {
        "seg":"/app/pytorch-fcn/examples/voc/logs/20230831_174351.813277/result1/",
        "origin" : "./dataset/image/20230605_ch2_crop_resize_212/"
    },
    "cloud" :{
        "seg" : "./segmentationModel/results/20230605_ch1_crop_mask/FCN/",
        "origin" : "./dataset/image/20230605_ch1_crop/test/Image/",
        "classification" : "./cloud_classification/"
    },
    "table" : "./dataset/table/",
}

### table 한 줄로 펴기

In [2]:
import pandas as pd 

# 모든 행 출력
pd.set_option('display.max_rows', None)

df_table = pd.read_csv(f'{dataset_folders["table"]}weather-addSoilingType_examine_1_upload.csv')
df_table['일시']=pd.to_datetime(df_table['일시'])
df_table

,일시,기온(°C),풍속(m/s),습도(%),누적일사(MJ/m^2),일사(MJ/m^2),패널1,패널2,패널3,패널4,패널1감소량(%),패널2감소량(%),패널3감소량(%),panel1_type,panel2_type,panel3_type,비고
0,2023-03-22 16:44:00,24.8,0.6,35.1,19.03,0.01,30.253643,24.392439,43.047188,47.617451,36.465219,48.774160,9.597874,sand,sand,-,NaN
1,2023-03-22 16:48:00,24.8,0.3,35.5,19.11,0.02,18.711142,28.045124,41.918766,45.050343,58.466150,37.747146,6.951282,sand,sand,-,NaN
2,2023-03-22 16:52:00,25.1,1.6,35.4,19.18,0.03,18.002813,17.785406,43.793674,50.285156,64.198553,64.630902,12.909340,sand,sand,-,NaN
3,2023-03-22 16:56:00,24.7,1.9,35.6,19.23,0.02,14.933952,4.243219,45.630005,47.265797,68.404315,91.022644,3.460836,sand,sand,-,NaN
4,2023-03-22 17:02:00,24.6,2.2,36.0,19.29,0.00,23.847889,0.904453,41.216297,42.699940,44.150064,97.881840,3.474578,sand,sand,-,NaN
5,2023-03-29 09:17:00,8.8,0.4,55.2,2.17,0.03,79.253433,174.313141,159.924744,234.059204,66.139578,25.526047,31.673380,shadow,pine_pollen,pine_pollen,NaN
6,2023-03-29 09:21:00,8.9,0.4,56.2,2.28,0.03,225.318741,184.460068,117.164162,239.669708,5.987810,23.035719,51.114322,-,pine_pollen,pine_pollen,NaN
7,2023-03-29 09:25:00,9.2,0.2,55.4,2.42,0.03,96.024139,174.675369,122.919571,228.208313,57.922594,23.457929,46.137120,shadow,pine_pollen,pine_pollen,NaN
8,2023-03-29 09:29:00,9.4,0.7,55.9,2.53,0.03,74.881966,145.722946,107.325569,204.925507,63.458934,28.889796,47.627032,shadow,pine_pollen,pine_pollen,NaN
9,2023-03-29 09:33:00,9.4,0.1,54.3,2.65,0.04,192.788422,135.386063,82.275703,204.972046,5.944042,33.949011,59.860037,-,pine_pollen,pine_pollen,NaN
10,2023-03-29 09:37:00,10.0,0.2,53.4,2.77,0.02,229.048126,154.943985,97.584610,235.499054,2.739258,34.206111,58.562632,-,pine_pollen,pine_pollen,NaN
11,2023-03-29 09:42:00,10.0,0.4,51.2,2.93,0.03,33.043358,160.891312,93.956619,253.687729,86.974791,36.578993,62.963672,sand,pine_pollen,pine_pollen,NaN
12,2023-03-29 14:14:00,20.1,0.8,16.1,15.80,0.05,178.110580,145.995758,79.838394,224.319367,20.599553,34.916115,64.408604,pine_pollen,pine_pollen,shadow,NaN
13,2023-03-29 14:18:00,19.7,1.5,15.4,15.97,0.04,178.198883,102.636093,79.956802,234.792801,24.103770,56.286525,65.945803,pine_pollen,pine_pollen,shadow,NaN
14,2023-03-29 14:22:00,19.8,0.8,17.2,16.17,0.05,168.060928,100.020935,73.432732,234.733124,28.403403,57.389510,68.716502,pine_pollen,pine_pollen,shadow,NaN
15,2023-03-29 14:26:00,19.7,1.5,15.0,16.34,0.05,141.794998,72.287720,71.401878,221.506882,35.986188,67.365475,67.765390,pine_pollen,pine_pollen,shadow,NaN
16,2023-03-29 14:30:00,19.9,1.3,16.5,16.52,0.06,121.387505,64.444260,72.365997,205.611221,40.962607,68.657226,64.804451,pine_pollen,pine_pollen,shadow,NaN
17,2023-03-29 14:34:00,19.6,0.3,16.9,16.69,0.06,121.984833,64.263374,75.146248,214.138626,43.034643,69.989826,64.907663,pine_pollen,pine_pollen,shadow,NaN
18,2023-03-29 14:38:00,19.4,0.4,17.5,16.86,0.05,116.493515,31.519312,81.561234,211.072876,44.808865,85.067095,61.358733,pine_pollen,pine_pollen,shadow,NaN
19,2023-03-29 14:42:00,19.7,0.6,16.9,17.03,0.05,98.613510,25.894688,78.057289,204.724411,51.831093,87.351441,61.872017,pine_pollen,pine_pollen,shadow,NaN
20,2023-03-29 14:46:00,20.2,1.2,18.0,17.20,0.05,80.496284,28.452610,78.007736,200.203888,59.792847,85.788183,61.035853,pine_pollen,pine_pollen,shadow,NaN
21,2023-03-29 14:50:00,20.0,0.9,19.8,17.37,0.05,89.190750,26.448469,81.643593,200.226502,55.455072,86.790725,59.224382,pine_pollen,pine_pollen,shadow,NaN
22,2023-03-29 14:54:00,20.0,1.7,17.5,17.54,0.04,85.380745,22.957594,77.180252,198.687927,57.027714,88.445401,61.155037,pine_pollen,pine_pollen,shadow,NaN
23,2023-03-29 14:58:00,19.7,0.9,17.0,17.70,0.05,79.182419,55.275749,114.315468,190.306076,58.392070,70.954291,39.930731,pine_pollen,pine_pollen,-,NaN
24,2023-03-29 15:07:00,19.8,1.3,18.5,18.04,0.03,106.689651,19.535252,165.862686,168.137253,36.546096,88.381366,1.352803,pine_pollen,pine_pollen,-,NaN
25,2023-03-29 16:41:00,20.7,1.7,12.8,20.78,0.02,46.068752,5.624859,52.583626,73.052254,36.937261,92.300225,28.019160,pine_pollen,pine_pollen,-,NaN
26,2023-03-29 16:45:00,20.5,1.2,12.4,20.86,0.02,43.824799,5.902875,50.784233,69.095528,36.573610,91.456936,26.501418,pine_pollen,pine_pollen,-,NaN
27,2023-03-29 16:49:00,20.7,1.2,12.8,20.94,0.02,40.007999,5.432579,47.914452,63.337311,36.833442,91.422783,24.350354,pine_pollen,pine_pollen,-,NaN
28,2023-03-29 16:53:00,20.7,2.2,13.0,21.01,0.01,35.646187,6.014531,46.459408,58.986046,39.568441,89.803468,21.236613,pine_pollen,pine_pollen,-,NaN
29,2023-03-29 16:57:00,20.7,0.5,14.2,21.07,0.01,39.205826,4.834688,44.976143,56.028286,30.024942,91.370988,19.726006,pine_pollen,pine_pollen,-,NaN
30,2023-03-29 17:00:00,20.7,0.8,14.4,21.12,0.00,37.525124,4.817391,43.630638,53.510063,29.872773,90.997224,18.462742,pine_pollen,pine_pollen,-,NaN
31,2023-03-29 17:05:00,20.6,0.4,13.9,21.20,0.00,37.223202,25.626656,41.743404,47.752029,22.048964,46.333892,12.582973,pine_pollen,pine_pollen,-,NaN
32,2023-03-29 17:10:00,20.3,1.8,15.0,21.28,0.01,36.757549,37.042969,40.363312,44.364750,17.146948,16.503601,9.019409,pine_pollen,pine_pollen,-,NaN
33,2023-03-29 17:15:00,20.1,1.1,15.2,21.35,0.01,34.742485,34.043625,36.746159,40.150124,13.468548,15.209165,8.478093,pine_pollen,pine_pollen,-,NaN
34,2023-03-29 17:21:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,-,-,NaN
35,2023-03-29 17:28:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,pine_pollen,-,NaN
36,2023-04-03 09:36:00,16.0,1.9,24.1,3.26,0.02,206.289368,153.073120,266.222534,264.755157,22.082965,42.183139,-0.554239,sand,sand,bird_dropping,NaN
37,2023-04-03 09:40:00,16.3,2.2,24.5,3.43,0.04,214.029373,72.305908,261.059296,270.704529,20.936168,73.289731,3.563011,sand,sand,bird_dropping,NaN
38,2023-04-03 09:45:00,16.3,1.9,24.1,3.61,0.04,214.596420,76.540405,258.127045,264.939239,19.001647,71.110204,2.571229,sand,sand,bird_dropping,NaN
39,2023-04-03 09:49:00,16.2,0.6,24.8,3.76,0.03,202.155746,52.871063,251.837845,268.192413,24.622869,80.286145,6.098073,sand,sand,bird_dropping,NaN
40,2023-04-03 09:53:00,16.4,2.2,24.3,3.92,0.04,167.891998,50.445000,238.518158,250.871201,33.076416,79.892072,4.924058,sand,sand,bird_dropping,NaN
41,2023-04-03 09:57:00,16.5,2.7,24.2,4.07,0.04,183.421875,55.438786,255.769608,273.907257,33.035044,79.760016,6.621821,sand,sand,bird_dropping,NaN
42,2023-04-03 10:01:00,16.4,1.9,24.4,4.23,0.04,171.224625,57.206203,256.366425,274.867310,37.706443,79.187702,6.730842,sand,sand,bird_dropping,NaN
43,2023-04-03 10:06:00,16.7,1.2,24.2,4.44,0.04,166.713898,60.113441,258.291290,289.185730,42.350579,79.212860,10.683252,sand,sand,bird_dropping,NaN
44,2023-04-03 10:11:00,16.9,1.9,24.1,4.65,0.04,164.582291,39.320206,261.955536,282.917511,41.826757,86.101883,7.409218,sand,sand,bird_dropping,NaN
45,2023-04-03 10:15:00,17.2,1.8,23.5,4.82,0.04,156.545166,34.600315,256.805450,284.130005,44.903684,87.822365,9.616920,sand,sand,bird_dropping,NaN
46,2023-04-03 13:50:00,22.1,3.0,21.4,15.39,0.04,269.012451,151.183273,245.048996,269.098663,0.032037,43.818646,8.937119,sand,-,bird_dropping,birddropping 변경 X
47,2023-04-03 13:54:00,22.7,5.2,21.4,15.60,0.04,249.808792,68.852440,241.306732,269.003052,7.135332,74.404588,10.295913,sand,shadow,bird_dropping,birddropping 변경 X
48,2023-04-03 13:58:00,22.5,3.3,22.2,15.81,0.05,258.023407,65.681808,241.061722,271.034607,4.800568,75.766265,11.058693,sand,shadow,bird_dropping,birddropping 변경 X
49,2023-04-03 14:02:00,22.9,5.5,21.2,16.02,0.05,210.209778,64.049904,238.534744,265.446564,20.809004,75.870886,10.138319,sand,shadow,bird_dropping,birddropping 변경 X
50,2023-04-03 14:06:00,22.6,4.2,21.9,16.21,0.04,243.007462,66.312416,230.713440,258.685455,6.060640,74.365619,10.813138,sand,shadow,bird_dropping,birddropping 변경 X
51,2023-04-03 14:10:00,22.6,3.9,21.2,16.42,0.05,250.312500,62.945065,230.178085,252.700607,0.945034,75.091051,8.912730,sand,shadow,bird_dropping,birddropping 변경 X
52,2023-04-03 14:14:00,22.8,3.8,21.9,16.62,0.06,228.076172,63.873138,246.875946,255.370575,10.688155,74.988059,3.326393,sand,shadow,bird_dropping,birddropping 변경 X
53,2023-04-03 14:18:00,22.8,2.7,22.5,16.81,0.04,253.270142,60.189934,225.156082,252.642029,-0.248618,76.175803,10.879404,sand,shadow,bird_dropping,birddropping 변경 X
54,2023-04-03 14:22:00,23.0,6.7,20.8,17.02,0.06,112.028999,56.904701,216.272125,244.177017,54.119761,76.695308,11.428140,sand,shadow,bird_dropping,birddropping 변경 X
55,2023-04-03 14:26:00,22.7,3.8,20.5,17.21,0.04,157.657501,57.657658,250.343155,247.592819,36.323880,76.712710,-1.110830,sand,shadow,-,NaN
56,2023-04-03 14:44:00,22.2,5.3,23.5,18.05,0.03,183.690933,58.533752,215.533981,220.991898,16.878883,73.513168,2.469736,sand,shadow,bird_dropping,NaN
57,2023-04-03 14:48:00,22.7,7.7,23.1,18.23,0.03,113.400413,55.390503,214.958206,219.941727,48.440701,74.815828,2.265837,sand,shadow,bird_dropping,NaN
58,2023-04-03 14:52:00,22.7,3.3,23.3,18.42,0.05,59.332500,54.826878,208.924255,212.498016,72.078563,74.198876,1.681786,sand,shadow,bird_dropping,NaN
59,2023-04-03 14:56:00,22.9,3.3,23.3,18.59,0.05,63.674442,52.824749,202.918823,212.315720,70.009549,75.119718,4.425907,sand,shadow,bird_dropping,NaN
60,2023-04-03 15:00:00,22.7,3.4,22.4,18.77,0.06,61.519505,53.662643,196.574905,206.548889,70.215524,74.019399,4.828873,sand,shadow,bird_dropping,NaN
61,2023-04-03 15:04:00,22.8,4.1,22.0,18.94,0.05,104.568756,50.867577,194.434692,202.907242,48.464749,74.930625,4.175578,sand,shadow,bird_dropping,NaN
62,2023-04-03 15:08:00,23.0,3.2,22.1,19.10,0.05,93.014908,49.932938,189.129288,200.316757,53.566087,75.073010,5.584889,sand,shadow,bird_dropping,NaN
63,2023-04-03 15:12:00,23.2,2.2,22.2,19.27,0.05,90.812813,51.191998,184.542053,196.286636,53.734592,73.919774,5.983384,sand,shadow,bird_dropping,NaN
64,2023-04-03 15:16:00,22.8,2.5,22.6,19.43,0.05,90.525002,51.856876,175.809387,190.542389,52.490886,72.784598,7.732139,sand,shadow,bird_dropping,NaN
65,2023-04-03 15:20:00,22.8,4.4,22.2,19.59,0.05,57.735752,52.725002,173.190094,186.818909,69.095338,71.777481,7.295201,sand,shadow,bird_dropping,NaN
66,2023-04-03 16:47:00,23.6,1.2,19.7,22.30,0.01,58.709251,31.450218,64.709068,64.723640,9.292415,51.408453,0.022514,bird_dropping,-,-,NaN
67,2023-04-03 16:51:00,23.7,3.2,19.4,22.38,0.01,51.138283,29.116499,56.560780,55.879826,8.485250,47.894435,-1.218604,bird_dropping,-,-,NaN
68,2023-04-03 16:55:00,23.7,3.0,19.1,22.46,0.01,49.954922,32.916798,56.179920,53.206875,6.111904,38.134315,-5.587709,bird_dropping,-,-,NaN
69,2023-04-03 16:59:00,23.5,3.4,19.1,22.54,0.02,41.423908,29.911875,50.079044,48.169685,14.004196,37.903114,-3.963819,bird_dropping,-,-,NaN
70,2023-04-03 17:03:00,23.3,2.1,19.3,22.61,0.02,36.135002,29.254498,42.582703,42.366001,14.707546,30.948174,-0.511499,bird_dropping,-,-,NaN
71,2023-04-03 17:07:00,23.3,3.2,19.4,22.67,0.03,31.782375,29.449406,38.377499,39.011299,18.530333,24.510574,1.624659,bird_dropping,-,-,NaN
72,2023-04-03 17:12:00,23.1,2.7,19.8,22.73,0.01,31.064907,30.044342,38.576580,38.375393,19.049931,21.709357,-0.524261,bird_dropping,-,-,NaN
73,2023-04-03 17:18:00,23.1,3.0,20.3,22.81,0.01,27.979687,28.093782,33.958408,33.237377,15.818608,15.475333,-2.169338,bird_dropping,-,-,NaN
74,2023-04-03 17:23:00,23.2,2.1,20.1,22.88,0.01,24.969000,25.293516,25.530001,29.929501,16.573951,15.489682,14.699543,bird_dropping,-,sand,NaN
75,2023-04-03 17:27:00,23.1,2.5,20.1,22.93,0.01,20.794220,24.850733,20.004749,27.288002,23.797206,8.931651,26.690311,bird_dropping,-,sand,NaN
76,2023-04-03 17:31:00,23.2,2.0,20.2,22.96,0.01,19.965611,22.495405,9.866812,23.531155,15.152440,4.401609,58.069156,bird_dropping,-,sand,NaN
77,2023-04-10 09:18:00,11.9,1.1,34.6,2.70,0.04,147.955505,193.213974,237.598419,242.179123,38.906581,20.218567,1.891453,pine_pollen,sand,bird_dropping,NaN
78,2023-04-10 09:19:00,12.0,1.4,34.8,2.73,0.03,147.289490,193.168884,239.655914,244.837692,39.841987,21.103290,2.116414,pine_pollen,sand,bird_dropping,NaN
79,2023-04-10 09:20:00,12.1,1.3,34.3,2.76,0.03,146.279068,192.367981,236.129913,245.039627,40.303913,21.495154,3.636030,pine_pollen,sand,bird_dropping,NaN
80,2023-04-10 09:22:00,12.2,0.2,34.7,2.82,0.03,137.468246,150.936752,239.218308,249.774597,44.963079,39.570815,4.226326,pine_pollen,sand,bird_dropping,NaN
81,2023-04-10 09:23:00,12.3,0.0,34.5,2.86,0.04,136.665756,153.514923,239.659164,251.630997,45.688028,38.992046,4.757694,pine_pollen,sand,bird_dropping,NaN
82,2023-04-10 09:24:00,12.5,0.3,34.7,2.90,0.04,136.937531,152.989868,244.021408,248.417114,44.875968,38.414119,1.769486,pine_pollen,sand,bird_dropping,NaN
83,2023-04-10 09:26:00,12.6,0.7,34.6,2.97,0.03,127.417503,151.897034,245.084610,249.499680,48.930795,39.119347,1.769569,pine_pollen,sand,bird_dropping,NaN
84,2023-04-10 09:27:00,12.6,1.4,34.2,3.00,0.03,129.485657,151.148804,244.785934,249.657333,48.134647,39.457495,1.951234,pine_pollen,sand,bird_dropping,NaN
85,2023-04-10 09:28:00,12.5,1.4,34.0,3.03,0.03,129.241165,153.412888,240.424408,254.358215,49.189310,39.686286,5.478025,pine_pollen,sand,bird_dropping,NaN
86,2023-04-10 09:30:00,12.4,0.9,35.1,3.11,0.04,113.333580,150.144333,241.756592,251.607529,54.956205,40.325978,3.915200,pine_pollen,sand,bird_dropping,NaN
87,2023-04-10 09:31:00,12.5,0.7,34.3,3.15,0.04,113.003433,152.583191,244.423859,255.731964,55.811768,40.334721,4.421858,pine_pollen,sand,bird_dropping,NaN
88,2023-04-10 09:32:00,12.5,0.4,34.0,3.19,0.04,113.801346,153.118118,247.248276,254.598740,55.301685,39.859043,2.887078,pine_pollen,sand,bird_dropping,NaN
89,2023-04-10 09:34:00,12.5,0.6,34.0,3.25,0.03,117.565361,154.618957,249.036575,258.911255,54.592410,40.281098,3.813924,pine_pollen,sand,bird_dropping,NaN
90,2023-04-10 09:35:00,12.6,0.5,34.3,3.29,0.04,117.416245,157.512482,254.626877,260.515137,54.929204,39.538069,2.260237,pine_pollen,sand,bird_dropping,NaN
91,2023-04-10 09:36:00,12.6,0.7,34.1,3.32,0.03,117.321747,153.917160,252.054184,265.268250,55.772413,41.976788,4.981397,pine_pollen,sand,bird_dropping,NaN
92,2023-04-10 09:38:00,12.7,0.3,34.6,3.41,0.05,101.432304,152.392212,257.014435,269.341034,62.340568,43.420351,4.576577,pine_pollen,sand,bird_dropping,NaN
93,2023-04-10 09:39:00,12.8,0.1,33.6,3.44,0.03,102.256874,155.079269,256.264313,265.511993,61.486910,41.592367,3.482962,pine_pollen,sand,bird_dropping,NaN
94,2023-04-10 09:40:00,12.9,1.1,33.7,3.48,0.04,103.227181,153.053162,257.894989,268.028900,61.486548,42.896769,3.780902,pine_pollen,sand,bird_dropping,NaN
95,2023-04-10 09:42:00,13.3,0.2,34.3,3.55,0.04,102.409737,122.300613,256.023285,271.747498,62.314377,54.994760,5.786332,pine_pollen,sand,bird_dropping,NaN
96,2023-04-10 09:43:00,13.7,0.3,33.6,3.59,0.04,102.124306,121.977379,257.343750,270.709290,62.275286,54.941561,4.937230,pine_pollen,sand,bird_dropping,NaN
97,2023-04-10 09:44:00,13.9,1.2,33.2,3.64,0.05,103.236938,124.721390,261.680206,269.966827,61.759399,53.801217,3.069496,pine_pollen,sand,bird_dropping,NaN
98,2023-04-10 09:46:00,13.6,0.6,32.1,3.71,0.04,100.647377,121.753494,261.346222,275.422424,63.457087,55.793907,5.110768,pine_pollen,sand,bird_dropping,NaN
99,2023-04-10 09:47:00,13.6,1.2,31.7,3.75,0.04,108.936188,124.750496,259.986389,273.523102,60.172948,54.391240,4.949020,pine_pollen,sand,bird_dropping,NaN
100,2023-04-10 09:48:00,13.6,1.1,32.0,3.78,0.03,108.769493,125.738434,264.585846,274.494141,60.374567,54.192671,3.609656,pine_pollen,sand,bird_dropping,NaN
101,2023-04-10 09:50:00,13.3,1.6,31.2,3.86,0.04,110.515968,123.176956,264.325989,278.841919,60.366085,55.825524,5.205792,pine_pollen,sand,bird_dropping,NaN
102,2023-04-10 09:51:00,13.3,1.6,31.4,3.91,0.05,112.818047,125.077499,268.222504,275.083099,58.987649,54.531013,2.494008,pine_pollen,sand,bird_dropping,NaN
103,2023-04-10 09:52:00,13.3,1.1,32.2,3.95,0.04,114.057136,123.858520,263.146332,280.968750,59.405757,55.917332,6.343203,pine_pollen,sand,bird_dropping,NaN
104,2023-04-10 09:54:00,13.7,2.4,31.7,4.03,0.04,113.215645,124.081863,233.110825,282.407623,59.910556,56.062849,17.455902,pine_pollen,sand,bird_dropping,NaN
105,2023-04-10 09:55:00,13.4,1.3,31.3,4.07,0.04,118.993500,137.227554,261.815613,280.403442,57.563467,51.060674,6.628959,pine_pollen,sand,bird_dropping,NaN
106,2023-04-10 09:56:00,13.2,1.0,32.3,4.11,0.04,119.286560,136.265625,266.392548,281.106415,57.565337,51.525252,5.234269,pine_pollen,sand,bird_dropping,NaN
107,2023-04-10 13:43:00,20.1,3.1,22.4,15.64,0.04,157.470749,177.723740,82.545326,272.736816,42.262746,34.836909,69.734439,pine_pollen,sand,shadow,NaN
108,2023-04-10 13:44:00,20.1,5.1,21.7,15.71,0.07,157.471130,176.669571,83.449547,273.195282,42.359499,35.332130,69.454250,pine_pollen,sand,shadow,NaN
109,2023-04-10 13:45:00,19.9,2.8,21.6,15.76,0.05,157.657501,174.676743,81.764435,273.380310,42.330338,36.104856,70.091323,pine_pollen,sand,shadow,NaN
110,2023-04-10 13:47:00,19.7,3.1,21.9,15.85,0.04,126.987663,176.073746,79.270828,270.146240,52.992993,34.822804,70.656327,pine_pollen,sand,shadow,NaN
111,2023-04-10 13:48:00,19.7,2.8,22.8,15.92,0.07,133.797089,208.775147,80.874840,270.369568,50.513259,22.781566,70.087299,pine_pollen,sand,shadow,NaN
112,2023-04-10 13:49:00,19.8,2.3,22.6,15.97,0.05,199.862045,236.066238,80.247658,275.693634,27.505745,14.373707,70.892452,pine_pollen,sand,shadow,NaN
113,2023-04-10 13:51:00,20.1,3.5,21.9,16.06,0.04,153.264008,232.059570,81.320862,270.822754,43.408002,14.313119,69.972663,pine_pollen,sand,shadow,NaN
114,2023-04-10 13:52:00,20.1,2.4,22.6,16.12,0.06,175.139252,238.120636,80.578308,270.523956,35.259245,11.977986,70.213984,pine_pollen,sand,shadow,NaN
115,2023-04-10 13:53:00,20.4,3.0,22.0,16.17,0.05,168.832871,233.506393,79.332428,268.498840,37.119702,13.032625,70.453344,pine_pollen,sand,shadow,NaN
116,2023-04-10 13:55:00,20.2,3.0,21.7,16.28,0.06,172.848053,221.804993,79.277107,269.193024,35.790293,17.603737,70.550089,pine_pollen,sand,shadow,NaN
117,2023-04-10 13:56:00,20.2,4.1,21.9,16.32,0.04,188.624481,223.688675,78.592308,267.032410,29.362701,16.231638,70.568251,pine_pollen,sand,shadow,NaN
118,2023-04-10 13:57:00,20.1,3.9,21.2,16.37,0.05,175.236328,228.645294,79.165405,266.073608,34.139906,14.066902,70.246803,pine_pollen,sand,shadow,NaN
119,2023-04-10 13:59:00,20.2,2.4,21.9,16.47,0.04,207.970047,162.700775,78.467995,267.781128,22.335809,39.241135,70.696966,pine_pollen,sand,shadow,NaN
120,2023-04-10 14:00:00,20.4,2.1,22.2,16.53,0.06,207.683426,164.068878,78.437813,264.387512,21.447339,37.943787,70.332255,pine_pollen,sand,shadow,NaN
121,2023-04-10 14:01:00,20.5,4.0,21.4,16.57,0.04,213.766296,163.852737,78.971901,266.119751,19.672893,38.428945,70.324675,pine_pollen,sand,shadow,NaN
122,2023-04-10 14:03:00,20.3,3.0,22.0,16.69,0.06,176.605179,167.226623,77.300858,260.321258,32.158757,35.761442,70.305592,pine_pollen,sand,shadow,NaN
123,2023-04-10 14:04:00,20.3,4.1,22.0,16.73,0.04,182.785690,172.898636,78.713905,262.113739,30.264743,34.036790,69.969561,pine_pollen,sand,shadow,NaN
124,2023-04-10 14:05:00,20.2,3.1,22.4,16.79,0.06,248.840530,208.908752,78.548767,263.583984,5.593456,20.743002,70.199719,pine_pollen,sand,shadow,NaN
125,2023-04-10 14:07:00,20.4,2.3,22.3,16.88,0.04,139.734757,184.953247,78.198654,260.362305,46.330650,28.963124,69.965447,pine_pollen,sand,shadow,NaN
126,2023-04-10 14:08:00,20.7,1.8,23.6,16.94,0.06,136.493912,217.346390,77.409752,254.641968,46.397716,14.646281,69.600552,pine_pollen,sand,shadow,NaN
127,2023-04-10 14:09:00,20.9,2.1,21.5,16.98,0.04,197.507812,217.503418,76.143661,260.488373,24.177878,16.501679,70.768883,pine_pollen,sand,shadow,NaN
128,2023-04-10 14:11:00,20.7,1.4,21.1,17.09,0.05,88.866844,217.541336,76.631248,256.648651,65.374124,15.237686,70.141574,pine_pollen,sand,shadow,NaN
129,2023-04-10 14:12:00,20.9,2.2,21.2,17.13,0.04,104.635971,216.340332,76.388809,255.016129,58.968881,15.166020,70.045499,pine_pollen,sand,shadow,NaN
130,2023-04-10 14:13:00,20.8,1.2,21.1,17.19,0.06,101.451935,218.674683,75.841881,254.751388,60.176101,14.161535,70.229061,pine_pollen,sand,shadow,NaN
131,2023-04-10 14:15:00,21.0,2.2,19.5,17.29,0.06,99.685219,185.067047,75.756844,251.120621,60.303850,26.303524,69.832488,pine_pollen,sand,shadow,NaN

In [3]:
df_panels = []


weather_cols = ['일시', '기온(°C)', '풍속(m/s)', '습도(%)', '일사(MJ/m^2)']

for i in range(1,4):
    panel_cols= [f'패널{i}', f'패널{i}감소량(%)', f'panel{i}_type']
    df_panels.append(df_table[weather_cols+panel_cols])

    
panel_cols= ['패널4']
df_panels.append(df_table[weather_cols+panel_cols])

In [4]:
for i in range(3):
    panel_cols= [f'패널{i+1}', f'패널{i+1}감소량(%)', f'panel{i+1}_type']
    df_panels[i].rename(columns = {f'패널{i+1}' : 'power generation',
                                  f'패널{i+1}감소량(%)' : 'reduction amount(%)',
                                  f'panel{i+1}_type' : 'soiling type'}, inplace = True)
    df_panels[i].insert(6,'panel number', [i+1 for _ in range(len(df_panels[i]))])
    
df_panels[3].rename(columns = {f'패널{4}' : 'power generation'},inplace = True)
df_panels[3].insert(6,'panel number',[4 for _ in range(len(df_panels[i]))])
df_panels[3]['soiling type'] = ['clean' for _ in range(len(df_panels[i]))]

/usr/local/lib/python3.8/dist-packages/pandas/core/frame.py:4441: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(
/tmp/ipykernel_43240/719428071.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_panels[3]['soiling type'] = ['clean' for _ in range(len(df_panels[i]))]

In [5]:
df= pd.concat(df_panels)
df

                     일시  기온(°C)  풍속(m/s)  습도(%)  일사(MJ/m^2)  power generation  \
0   2023-03-22 16:44:00    24.8      0.6   35.1        0.01         30.253643
1   2023-03-22 16:48:00    24.8      0.3   35.5        0.02         18.711142
2   2023-03-22 16:52:00    25.1      1.6   35.4        0.03         18.002813
3   2023-03-22 16:56:00    24.7      1.9   35.6        0.02         14.933952
4   2023-03-22 17:02:00    24.6      2.2   36.0        0.00         23.847889
5   2023-03-29 09:17:00     8.8      0.4   55.2        0.03         79.253433
6   2023-03-29 09:21:00     8.9      0.4   56.2        0.03        225.318741
7   2023-03-29 09:25:00     9.2      0.2   55.4        0.03         96.024139
8   2023-03-29 09:29:00     9.4      0.7   55.9        0.03         74.881966
9   2023-03-29 09:33:00     9.4      0.1   54.3        0.04        192.788422
10  2023-03-29 09:37:00    10.0      0.2   53.4        0.02        229.048126
11  2023-03-29 09:42:00    10.0      0.4   51.2        0.03         33.043358
12  2023-03-29 14:14:00    20.1      0.8   16.1        0.05        178.110580
13  2023-03-29 14:18:00    19.7      1.5   15.4        0.04        178.198883
14  2023-03-29 14:22:00    19.8      0.8   17.2        0.05        168.060928
15  2023-03-29 14:26:00    19.7      1.5   15.0        0.05        141.794998
16  2023-03-29 14:30:00    19.9      1.3   16.5        0.06        121.387505
17  2023-03-29 14:34:00    19.6      0.3   16.9        0.06        121.984833
18  2023-03-29 14:38:00    19.4      0.4   17.5        0.05        116.493515
19  2023-03-29 14:42:00    19.7      0.6   16.9        0.05         98.613510
20  2023-03-29 14:46:00    20.2      1.2   18.0        0.05         80.496284
21  2023-03-29 14:50:00    20.0      0.9   19.8        0.05         89.190750
22  2023-03-29 14:54:00    20.0      1.7   17.5        0.04         85.380745
23  2023-03-29 14:58:00    19.7      0.9   17.0        0.05         79.182419
24  2023-03-29 15:07:00    19.8      1.3   18.5        0.03        106.689651
25  2023-03-29 16:41:00    20.7      1.7   12.8        0.02         46.068752
26  2023-03-29 16:45:00    20.5      1.2   12.4        0.02         43.824799
27  2023-03-29 16:49:00    20.7      1.2   12.8        0.02         40.007999
28  2023-03-29 16:53:00    20.7      2.2   13.0        0.01         35.646187
29  2023-03-29 16:57:00    20.7      0.5   14.2        0.01         39.205826
30  2023-03-29 17:00:00    20.7      0.8   14.4        0.00         37.525124
31  2023-03-29 17:05:00    20.6      0.4   13.9        0.00         37.223202
32  2023-03-29 17:10:00    20.3      1.8   15.0        0.01         36.757549
33  2023-03-29 17:15:00    20.1      1.1   15.2        0.01         34.742485
34  2023-03-29 17:21:00     NaN      NaN    NaN         NaN               NaN
35  2023-03-29 17:28:00     NaN      NaN    NaN         NaN               NaN
36  2023-04-03 09:36:00    16.0      1.9   24.1        0.02        206.289368
37  2023-04-03 09:40:00    16.3      2.2   24.5        0.04        214.029373
38  2023-04-03 09:45:00    16.3      1.9   24.1        0.04        214.596420
39  2023-04-03 09:49:00    16.2      0.6   24.8        0.03        202.155746
40  2023-04-03 09:53:00    16.4      2.2   24.3        0.04        167.891998
41  2023-04-03 09:57:00    16.5      2.7   24.2        0.04        183.421875
42  2023-04-03 10:01:00    16.4      1.9   24.4        0.04        171.224625
43  2023-04-03 10:06:00    16.7      1.2   24.2        0.04        166.713898
44  2023-04-03 10:11:00    16.9      1.9   24.1        0.04        164.582291
45  2023-04-03 10:15:00    17.2      1.8   23.5        0.04        156.545166
46  2023-04-03 13:50:00    22.1      3.0   21.4        0.04        269.012451
47  2023-04-03 13:54:00    22.7      5.2   21.4        0.04        249.808792
48  2023-04-03 13:58:00    22.5      3.3   22.2        0.05        258.023407
49  2023-04-03 14:02:00    22.9      5.5   21.2        0.05        210.209778
50  2023-04-03 14:06:00    22.6      4.2   21.9        0.04        243.007462
51  2023-04-03 14:10:00    22.6      3.9   21.2        0.05        250.312500
52  2023-04-03 14:14:00    22.8      3.8   21.9        0.06        228.076172
53  2023-04-03 14:18:00    22.8      2.7   22.5        0.04        253.270142
54  2023-04-03 14:22:00    23.0      6.7   20.8        0.06        112.028999
55  2023-04-03 14:26:00    22.7      3.8   20.5        0.04        157.657501
56  2023-04-03 14:44:00    22.2      5.3   23.5        0.03        183.690933
57  2023-04-03 14:48:00    22.7      7.7   23.1        0.03        113.400413
58  2023-04-03 14:52:00    22.7      3.3   23.3        0.05         59.332500
59  2023-04-03 14:56:00    22.9      3.3   23.3        0.05         63.674442
60  2023-04-03 15:00:00    22.7      3.4   22.4        0.06         61.519505
61  2023-04-03 15:04:00    22.8      4.1   22.0        0.05        104.568756
62  2023-04-03 15:08:00    23.0      3.2   22.1        0.05         93.014908
63  2023-04-03 15:12:00    23.2      2.2   22.2        0.05         90.812813
64  2023-04-03 15:16:00    22.8      2.5   22.6        0.05         90.525002
65  2023-04-03 15:20:00    22.8      4.4   22.2        0.05         57.735752
66  2023-04-03 16:47:00    23.6      1.2   19.7        0.01         58.709251
67  2023-04-03 16:51:00    23.7      3.2   19.4        0.01         51.138283
68  2023-04-03 16:55:00    23.7      3.0   19.1        0.01         49.954922
69  2023-04-03 16:59:00    23.5      3.4   19.1        0.02         41.423908
70  2023-04-03 17:03:00    23.3      2.1   19.3        0.02         36.135002
71  2023-04-03 17:07:00    23.3      3.2   19.4        0.03         31.782375
72  2023-04-03 17:12:00    23.1      2.7   19.8        0.01         31.064907
73  2023-04-03 17:18:00    23.1      3.0   20.3        0.01         27.979687
74  2023-04-03 17:23:00    23.2      2.1   20.1        0.01         24.969000
75  2023-04-03 17:27:00    23.1      2.5   20.1        0.01         20.794220
76  2023-04-03 17:31:00    23.2      2.0   20.2        0.01         19.965611
77  2023-04-10 09:18:00    11.9      1.1   34.6        0.04        147.955505
78  2023-04-10 09:19:00    12.0      1.4   34.8        0.03        147.289490
79  2023-04-10 09:20:00    12.1      1.3   34.3        0.03        146.279068
80  2023-04-10 09:22:00    12.2      0.2   34.7        0.03        137.468246
81  2023-04-10 09:23:00    12.3      0.0   34.5        0.04        136.665756
82  2023-04-10 09:24:00    12.5      0.3   34.7        0.04        136.937531
83  2023-04-10 09:26:00    12.6      0.7   34.6        0.03        127.417503
84  2023-04-10 09:27:00    12.6      1.4   34.2        0.03        129.485657
85  2023-04-10 09:28:00    12.5      1.4   34.0        0.03        129.241165
86  2023-04-10 09:30:00    12.4      0.9   35.1        0.04        113.333580
87  2023-04-10 09:31:00    12.5      0.7   34.3        0.04        113.003433
88  2023-04-10 09:32:00    12.5      0.4   34.0        0.04        113.801346
89  2023-04-10 09:34:00    12.5      0.6   34.0        0.03        117.565361
90  2023-04-10 09:35:00    12.6      0.5   34.3        0.04        117.416245
91  2023-04-10 09:36:00    12.6      0.7   34.1        0.03        117.321747
92  2023-04-10 09:38:00    12.7      0.3   34.6        0.05        101.432304
93  2023-04-10 09:39:00    12.8      0.1   33.6        0.03        102.256874
94  2023-04-10 09:40:00    12.9      1.1   33.7        0.04        103.227181
95  2023-04-10 09:42:00    13.3      0.2   34.3        0.04        102.409737
96  2023-04-10 09:43:00    13.7      0.3   33.6        0.04        102.124306
97  2023-04-10 09:44:00    13.9      1.2   33.2        0.05        103.236938
98  2023-04-10 09:46:00    13.6      0.6   32.1        0.04        100.647377
99  2023-04-10 09:47:00    13.6      1.2   31.7        0.04        108.936188
100 2023-04-10 09:48:00    13.6      1.1   32.0        0.03        108.769493
101 2023-04-10 09:50:00    13.3      1.6   31.2        0.04        110.515968
102 2023-04-10 09:51:00    13.3      1.6   31.4        0.05        112.818047
103 2023-04-10 09:52:00    13.3      1.1   32.2        0.04        114.057136
104 2023-04-10 09:54:00    13.7      2.4   31.7        0.04        113.215645
105 2023-04-10 09:55:00    13.4      1.3   31.3        0.04        118.993500
106 2023-04-10 09:56:00    13.2      1.0   32.3        0.04        119.286560
107 2023-04-10 13:43:00    20.1      3.1   22.4        0.04        157.470749
108 2023-04-10 13:44:00    20.1      5.1   21.7        0.07        157.471130
109 2023-04-10 13:45:00    19.9      2.8   21.6        0.05        157.657501
110 2023-04-10 13:47:00    19.7      3.1   21.9        0.04        126.987663
111 2023-04-10 13:48:00    19.7      2.8   22.8        0.07        133.797089
112 2023-04-10 13:49:00    19.8      2.3   22.6        0.05        199.862045
113 2023-04-10 13:51:00    20.1      3.5   21.9        0.04        153.264008
114 2023-04-10 13:52:00    20.1      2.4   22.6        0.06        175.139252
115 2023-04-10 13:53:00    20.4      3.0   22.0        0.05        168.832871
116 2023-04-10 13:55:00    20.2      3.0   21.7        0.06        172.848053
117 2023-04-10 13:56:00    20.2      4.1   21.9        0.04        188.624481
118 2023-04-10 13:57:00    20.1      3.9   21.2        0.05        175.236328
119 2023-04-10 13:59:00    20.2      2.4   21.9        0.04        207.970047
120 2023-04-10 14:00:00    20.4      2.1   22.2        0.06        207.683426
121 2023-04-10 14:01:00    20.5      4.0   21.4        0.04        213.766296
122 2023-04-10 14:03:00    20.3      3.0   22.0        0.06        176.605179
123 2023-04-10 14:04:00    20.3      4.1   22.0        0.04        182.785690
124 2023-04-10 14:05:00    20.2      3.1   22.4        0.06        248.840530
125 2023-04-10 14:07:00    20.4      2.3   22.3        0.04        139.734757
126 2023-04-10 14:08:00    20.7      1.8   23.6        0.06        136.493912
127 2023-04-10 14:09:00    20.9      2.1   21.5        0.04        197.507812
128 2023-04-10 14:11:00    20.7      1.4   21.1        0.05         88.866844
129 2023-04-10 14:12:00    20.9      2.2   21.2        0.04        104.635971
130 2023-04-10 14:13:00    20.8      1.2   21.1        0.06        101.451935
131 2023-04-10 14:15:00    21.0      2.2   19.5        0.06         99.685219
132 2023-04-10 14:16:00    20.8      2.9   19.5        0.03         99.546051
133 2023-04-10 14:17:00    20.7      1.8   19.1        0.05        152.766007
134 2023-04-10 14:19:00    20.7      2.6   19.6        0.04        140.892609
135 2023-04-10 14:20:00    20.7      1.5   19.5        0.06        144.632812
136 2023-04-10 14:21:00    20.9      3.5   20.2        0.04        146.728134
137 2023-04-10 14:23:00    21.0      1.9   21.6        0.06         85.802055
138 2023-04-10 14:24:00    21.0      2.2   20.1        0.03         96.974998
139 2023-04-10 14:25:00    20.7      2.2   20.4        0.06         98.191734
140 2023-04-10 14:27:00    20.4      5.0   21.0        0.06         95.263588
141 2023-04-10 14:28:00    20.4      2.7   21.2        0.05        113.550934
142 2023-04-10 14:29:00    20.3      2.0   21.3        0.03        158.772797
143 2023-04-10 14:31:00    20.7      2.0   22.8        0.04         88.034065
144 2023-04-10 14:32:00    20.9      3.1   22.5        0.06         99.677811
145 2023-04-10 14:33:00    20.9      2.5   21.4        0.03         99.909424
146 2023-04-10 16:48:00    21.2      2.6   22.4        0.02         38.700001
147 2023-04-10 16:49:00    21.2      1.3   22.0        0.01         51.906002
148 2023-04-10 16:50:00    21.2      2.5   22.0        0.02         50.891251
149 2023-04-10 16:52:00    21.0      2.4   21.8        0.02         36.157406
150 2023-04-10 16:53:00    20.9      2.3   21.9        0.02         38.833454
151 2023-04-10 16:54:00    20.9      2.7   22.8        0.02         39.000000
152 2023-04-10 16:55:00    21.0      3.2   22.6        0.03         38.949047
153 2023-04-10 16:57:00    20.9      1.3   23.0        0.01         39.657513
154 2023-04-10 16:58:00    21.0      2.6   22.0        0.02         41.234158
155 2023-04-10 16:59:00    21.0      3.0   21.5        0.03         41.666626
156 2023-04-10 17:01:00    20.9      1.7   21.5        0.00         29.927061
157 2023-04-10 17:02:00    20.8      2.7   21.8        0.02         30.252748
158 2023-04-10 17:03:00    20.8      2.2   22.3        0.03         31.090500
159 2023-04-10 17:05:00    20.8      2.8   23.1        0.02         25.395002
160 2023-04-10 17:06:00    20.8      1.6   23.0        0.01         23.697187
161 2023-04-10 17:07:00    20.8      3.0   22.9        0.01         25.125467
162 2023-04-10 17:09:00    20.9      0.8   23.4        0.02         30.117046
163 2023-04-10 17:10:00    21.0      0.9   23.6        0.01         31.528360
164 2023-04-10 17:11:00    21.0      2.4   23.4        0.01         32.300156
165 2023-04-10 17:13:00    21.0      3.6   23.2        0.02         33.106499
166 2023-04-10 17:14:00    20.8      2.8   23.2        0.02         33.082497
167 2023-04-10 17:15:00    20.7      3.1   23.1        0.01         32.083595
168 2023-04-10 17:17:00    20.6      2.7   23.2        0.02         22.783031
169 2023-04-10 17:18:00    20.6      2.9   23.6        0.02         20.785500
170 2023-04-10 17:19:00    20.6      1.6   23.7        0.02         27.814920
171 2023-04-10 17:21:00    20.7      1.3   23.2        0.01         26.590641
172 2023-04-10 17:22:00    20.7      1.1   23.4        0.01         25.658016
173 2023-04-10 17:23:00    20.7      1.4   23.2        0.01         25.845751
174 2023-04-10 17:25:00    20.8      1.5   23.4        0.01         23.044735
175 2023-04-10 17:26:00    20.8      2.0   23.4        0.02         24.396515
176 2023-04-10 17:27:00    20.8      2.3   22.9        0.00         24.024517
177 2023-04-10 17:29:00    20.6      3.3   23.7        0.01         13.842938
178 2023-04-10 17:30:00    20.6      3.0   23.9        0.03         14.543907
179 2023-04-10 17:31:00    20.5      2.4   24.3        0.01         13.490953
180 2023-04-17 09:21:00    12.1      0.7   63.3        0.03        115.248657
181 2023-04-17 09:22:00    12.1      1.5   62.8        0.04        129.249664
182 2023-04-17 09:23:00    12.0      0.9   62.2        0.04        134.220276
183 2023-04-17 09:25:00    12.1      0.7   62.6        0.04        127.139252
184 2023-04-17 09:26:00    12.4      1.3   63.4        0.04        129.712631
185 2023-04-17 09:27:00    12.7      1.2   62.3        0.04        125.212082
186 2023-04-17 09:29:00    12.9      2.3   59.8        0.04        125.775002
187 2023-04-17 09:30:00    13.0      1.4   59.5        0.03        125.647034
188 2023-04-17 09:31:00    13.1      2.5   58.8        0.03        124.374649
189 2023-04-17 09:33:00    12.5      1.7   56.9        0.04        125.377029
190 2023-04-17 09:34:00    12.2      1.3   58.1        0.05        124.532806
191 2023-04-17 09:35:00    12.2      1.7   60.3        0.04        125.767593
192 2023-04-17 09:37:00    12.4      1.2   58.9        0.03        124.664062
193 2023-04-17 09:38:00    12.3      0.9   58.8        0.04        126.607414
194 2023-04-17 09:39:00    12.3      0.4   59.2        0.04        125.696953
195 2023-04-17 09:41:00    12.5      0.8   59.9        0.04        127.590179
196 2023-04-17 09:42:00    12.6      1.3   59.7        0.03        128.758926
197 2023-04-17 09:43:00    12.6      1.2   58.8        0.04        126.637444
198 2023-04-17 09:45:00    12.8      0.7   57.6        0.04        113.208794
199 2023-04-17 09:46:00    12.7      1.3   58.1        0.04        115.555779
200 2023-04-17 09:47:00    12.6      0.8   58.1        0.04        116.186630
201 2023-04-17 09:49:00    12.8      1.4   58.5        0.04        103.509888
202 2023-04-17 09:50:00    12.9      1.6   57.5        0.05        103.600678
203 2023-04-17 09:51:00    13.0      1.7   57.5        0.04        106.188942
204 2023-04-17 09:53:00    12.8      1.0   57.1        0.04        141.400131
205 2023-04-17 09:54:00    13.1      0.8   58.2        0.04        148.374191
206 2023-04-17 09:55:00    13.3      0.8   56.6        0.04        147.055069
207 2023-04-17 09:57:00    13.3      0.4   53.8        0.04        144.680252
208 2023-04-17 09:58:00    13.2      0.6   56.4        0.04        146.713745
209 2023-04-17 09:59:00    13.3      0.7   57.1        0.04        147.306091
210 2023-04-17 13:38:00    18.5      1.5   27.2        0.05        191.599335
211 2023-04-17 13:39:00    18.7      1.6   29.9        0.06        187.124527
212 2023-04-17 13:40:00    18.8      2.1   25.9        0.05        173.332840
213 2023-04-17 13:42:00    18.8      1.8   26.6        0.07        184.372482
214 2023-04-17 13:43:00    18.8      2.8   26.9        0.05        182.062561
215 2023-04-17 13:44:00    18.8      2.6   26.3        0.04        183.930100
216 2023-04-17 13:46:00    18.7      2.2   27.6        0.04        119.542503
217 2023-04-17 13:47:00    18.6      2.7   27.6        0.06        121.552124
218 2023-04-17 13:48:00    18.7      2.0   27.8        0.06        120.827347
219 2023-04-17 13:50:00    18.6      1.9   28.8        0.06        116.430740
220 2023-04-17 13:51:00    18.5      2.4   28.5        0.05        116.885521
221 2023-04-17 13:52:00    18.7      2.1   29.4        0.04        118.263748
222 2023-04-17 13:54:00    18.7      1.1   28.9        0.04        103.386421
223 2023-04-17 13:55:00    18.6      0.3   28.4        0.06        102.327423
224 2023-04-17 13:56:00    18.5      0.2   27.7        0.03        106.398743
225 2023-04-17 13:58:00    18.6      0.5   28.2        0.05        107.257500
226 2023-04-17 13:59:00    18.6      0.6   29.3        0.04        102.650620
227 2023-04-17 14:00:00    18.7      1.0   28.2        0.06        102.099274
228 2023-04-17 14:02:00    18.8      1.5   29.0        0.06        100.122467
229 2023-04-17 14:03:00    18.9      1.4   29.2        0.03         97.417503
230 2023-04-17 14:04:00    19.1      1.2   28.7        0.05        100.360222
231 2023-04-17 14:06:00    18.9      1.6   27.2        0.04         91.342117
232 2023-04-17 14:07:00    18.7      1.2   28.6        0.05         94.320465
233 2023-04-17 14:08:00    18.6      1.8   29.2        0.04         97.533752
234 2023-04-17 14:10:00    18.7      2.0   27.6        0.05         89.662498
235 2023-04-17 14:11:00    18.8      0.7   27.8        0.04         89.872124
236 2023-04-17 14:12:00    19.1      0.3   29.9        0.05         87.465752
237 2023-04-17 14:14:00    19.2      1.4   27.5        0.06         90.222191
238 2023-04-17 14:15:00    19.2      1.5   27.8        0.04         85.873726
239 2023-04-17 14:16:00    19.2      1.3   27.5        0.05         89.424004
240 2023-04-17 16:51:00    20.0      0.4   27.6        0.02         28.032469
241 2023-04-17 16:52:00    20.1      0.5   26.9        0.01         26.855158
242 2023-04-17 16:53:00    20.2      0.7   27.0        0.01         27.902815
243 2023-04-17 16:56:00    20.5      1.8   26.6        0.01         31.741875
244 2023-04-17 16:57:00    20.4      1.8   25.5        0.02         31.824469
245 2023-04-17 16:58:00    20.3      1.3   25.4        0.03         32.243252
246 2023-04-17 17:00:00    20.2      1.3   25.7        0.01         28.012501
247 2023-04-17 17:01:00    20.2      1.1   25.9        0.01         25.491375
248 2023-04-17 17:02:00    20.2      1.1   26.2        0.02         25.477032
249 2023-04-17 17:04:00    20.1      0.6   25.9        0.02         20.842312
250 2023-04-17 17:05:00    20.1      0.9   25.5        0.02         20.947735
251 2023-04-17 17:06:00    20.0      0.4   25.4        0.01         20.354813
252 2023-04-17 17:08:00    19.8      0.2   25.8        0.01         28.685812
253 2023-04-17 17:09:00    19.9      0.3   25.6        0.03         29.125687
254 2023-04-17 17:10:00    20.0      0.2   26.0        0.01         25.284842

In [6]:
df.keys()

Index(['일시', '기온(°C)', '풍속(m/s)', '습도(%)', '일사(MJ/m^2)', 'power generation',
       'panel number', 'reduction amount(%)', 'soiling type'],
      dtype='object')

In [7]:
df = df.reset_index(drop =True)
df = df.dropna(subset=['일시', '기온(°C)', '풍속(m/s)', '습도(%)', '일사(MJ/m^2)', 'power generation',
       'panel number'], axis=0)
df

                      일시  기온(°C)  풍속(m/s)  습도(%)  일사(MJ/m^2)  \
0    2023-03-22 16:44:00    24.8      0.6   35.1        0.01
1    2023-03-22 16:48:00    24.8      0.3   35.5        0.02
2    2023-03-22 16:52:00    25.1      1.6   35.4        0.03
3    2023-03-22 16:56:00    24.7      1.9   35.6        0.02
4    2023-03-22 17:02:00    24.6      2.2   36.0        0.00
5    2023-03-29 09:17:00     8.8      0.4   55.2        0.03
6    2023-03-29 09:21:00     8.9      0.4   56.2        0.03
7    2023-03-29 09:25:00     9.2      0.2   55.4        0.03
8    2023-03-29 09:29:00     9.4      0.7   55.9        0.03
9    2023-03-29 09:33:00     9.4      0.1   54.3        0.04
10   2023-03-29 09:37:00    10.0      0.2   53.4        0.02
11   2023-03-29 09:42:00    10.0      0.4   51.2        0.03
12   2023-03-29 14:14:00    20.1      0.8   16.1        0.05
13   2023-03-29 14:18:00    19.7      1.5   15.4        0.04
14   2023-03-29 14:22:00    19.8      0.8   17.2        0.05
15   2023-03-29 14:26:00    19.7      1.5   15.0        0.05
16   2023-03-29 14:30:00    19.9      1.3   16.5        0.06
17   2023-03-29 14:34:00    19.6      0.3   16.9        0.06
18   2023-03-29 14:38:00    19.4      0.4   17.5        0.05
19   2023-03-29 14:42:00    19.7      0.6   16.9        0.05
20   2023-03-29 14:46:00    20.2      1.2   18.0        0.05
21   2023-03-29 14:50:00    20.0      0.9   19.8        0.05
22   2023-03-29 14:54:00    20.0      1.7   17.5        0.04
23   2023-03-29 14:58:00    19.7      0.9   17.0        0.05
24   2023-03-29 15:07:00    19.8      1.3   18.5        0.03
25   2023-03-29 16:41:00    20.7      1.7   12.8        0.02
26   2023-03-29 16:45:00    20.5      1.2   12.4        0.02
27   2023-03-29 16:49:00    20.7      1.2   12.8        0.02
28   2023-03-29 16:53:00    20.7      2.2   13.0        0.01
29   2023-03-29 16:57:00    20.7      0.5   14.2        0.01
30   2023-03-29 17:00:00    20.7      0.8   14.4        0.00
31   2023-03-29 17:05:00    20.6      0.4   13.9        0.00
32   2023-03-29 17:10:00    20.3      1.8   15.0        0.01
33   2023-03-29 17:15:00    20.1      1.1   15.2        0.01
36   2023-04-03 09:36:00    16.0      1.9   24.1        0.02
37   2023-04-03 09:40:00    16.3      2.2   24.5        0.04
38   2023-04-03 09:45:00    16.3      1.9   24.1        0.04
39   2023-04-03 09:49:00    16.2      0.6   24.8        0.03
40   2023-04-03 09:53:00    16.4      2.2   24.3        0.04
41   2023-04-03 09:57:00    16.5      2.7   24.2        0.04
42   2023-04-03 10:01:00    16.4      1.9   24.4        0.04
43   2023-04-03 10:06:00    16.7      1.2   24.2        0.04
44   2023-04-03 10:11:00    16.9      1.9   24.1        0.04
45   2023-04-03 10:15:00    17.2      1.8   23.5        0.04
46   2023-04-03 13:50:00    22.1      3.0   21.4        0.04
47   2023-04-03 13:54:00    22.7      5.2   21.4        0.04
48   2023-04-03 13:58:00    22.5      3.3   22.2        0.05
49   2023-04-03 14:02:00    22.9      5.5   21.2        0.05
50   2023-04-03 14:06:00    22.6      4.2   21.9        0.04
51   2023-04-03 14:10:00    22.6      3.9   21.2        0.05
52   2023-04-03 14:14:00    22.8      3.8   21.9        0.06
53   2023-04-03 14:18:00    22.8      2.7   22.5        0.04
54   2023-04-03 14:22:00    23.0      6.7   20.8        0.06
55   2023-04-03 14:26:00    22.7      3.8   20.5        0.04
56   2023-04-03 14:44:00    22.2      5.3   23.5        0.03
57   2023-04-03 14:48:00    22.7      7.7   23.1        0.03
58   2023-04-03 14:52:00    22.7      3.3   23.3        0.05
59   2023-04-03 14:56:00    22.9      3.3   23.3        0.05
60   2023-04-03 15:00:00    22.7      3.4   22.4        0.06
61   2023-04-03 15:04:00    22.8      4.1   22.0        0.05
62   2023-04-03 15:08:00    23.0      3.2   22.1        0.05
63   2023-04-03 15:12:00    23.2      2.2   22.2        0.05
64   2023-04-03 15:16:00    22.8      2.5   22.6        0.05
65   2023-04-03 15:20:00    22.8      4.4   22.2        0.05
66   2023-04-03 16:47:00    23.6      1.2   19.7        0.01
67   2023-04-03 16:51:00    23.7      3.2   19.4        0.01
68   2023-04-03 16:55:00    23.7      3.0   19.1        0.01
69   2023-04-03 16:59:00    23.5      3.4   19.1        0.02
70   2023-04-03 17:03:00    23.3      2.1   19.3        0.02
71   2023-04-03 17:07:00    23.3      3.2   19.4        0.03
72   2023-04-03 17:12:00    23.1      2.7   19.8        0.01
73   2023-04-03 17:18:00    23.1      3.0   20.3        0.01
74   2023-04-03 17:23:00    23.2      2.1   20.1        0.01
75   2023-04-03 17:27:00    23.1      2.5   20.1        0.01
76   2023-04-03 17:31:00    23.2      2.0   20.2        0.01
77   2023-04-10 09:18:00    11.9      1.1   34.6        0.04
78   2023-04-10 09:19:00    12.0      1.4   34.8        0.03
79   2023-04-10 09:20:00    12.1      1.3   34.3        0.03
80   2023-04-10 09:22:00    12.2      0.2   34.7        0.03
81   2023-04-10 09:23:00    12.3      0.0   34.5        0.04
82   2023-04-10 09:24:00    12.5      0.3   34.7        0.04
83   2023-04-10 09:26:00    12.6      0.7   34.6        0.03
84   2023-04-10 09:27:00    12.6      1.4   34.2        0.03
85   2023-04-10 09:28:00    12.5      1.4   34.0        0.03
86   2023-04-10 09:30:00    12.4      0.9   35.1        0.04
87   2023-04-10 09:31:00    12.5      0.7   34.3        0.04
88   2023-04-10 09:32:00    12.5      0.4   34.0        0.04
89   2023-04-10 09:34:00    12.5      0.6   34.0        0.03
90   2023-04-10 09:35:00    12.6      0.5   34.3        0.04
91   2023-04-10 09:36:00    12.6      0.7   34.1        0.03
92   2023-04-10 09:38:00    12.7      0.3   34.6        0.05
93   2023-04-10 09:39:00    12.8      0.1   33.6        0.03
94   2023-04-10 09:40:00    12.9      1.1   33.7        0.04
95   2023-04-10 09:42:00    13.3      0.2   34.3        0.04
96   2023-04-10 09:43:00    13.7      0.3   33.6        0.04
97   2023-04-10 09:44:00    13.9      1.2   33.2        0.05
98   2023-04-10 09:46:00    13.6      0.6   32.1        0.04
99   2023-04-10 09:47:00    13.6      1.2   31.7        0.04
100  2023-04-10 09:48:00    13.6      1.1   32.0        0.03
101  2023-04-10 09:50:00    13.3      1.6   31.2        0.04
102  2023-04-10 09:51:00    13.3      1.6   31.4        0.05
103  2023-04-10 09:52:00    13.3      1.1   32.2        0.04
104  2023-04-10 09:54:00    13.7      2.4   31.7        0.04
105  2023-04-10 09:55:00    13.4      1.3   31.3        0.04
106  2023-04-10 09:56:00    13.2      1.0   32.3        0.04
107  2023-04-10 13:43:00    20.1      3.1   22.4        0.04
108  2023-04-10 13:44:00    20.1      5.1   21.7        0.07
109  2023-04-10 13:45:00    19.9      2.8   21.6        0.05
110  2023-04-10 13:47:00    19.7      3.1   21.9        0.04
111  2023-04-10 13:48:00    19.7      2.8   22.8        0.07
112  2023-04-10 13:49:00    19.8      2.3   22.6        0.05
113  2023-04-10 13:51:00    20.1      3.5   21.9        0.04
114  2023-04-10 13:52:00    20.1      2.4   22.6        0.06
115  2023-04-10 13:53:00    20.4      3.0   22.0        0.05
116  2023-04-10 13:55:00    20.2      3.0   21.7        0.06
117  2023-04-10 13:56:00    20.2      4.1   21.9        0.04
118  2023-04-10 13:57:00    20.1      3.9   21.2        0.05
119  2023-04-10 13:59:00    20.2      2.4   21.9        0.04
120  2023-04-10 14:00:00    20.4      2.1   22.2        0.06
121  2023-04-10 14:01:00    20.5      4.0   21.4        0.04
122  2023-04-10 14:03:00    20.3      3.0   22.0        0.06
123  2023-04-10 14:04:00    20.3      4.1   22.0        0.04
124  2023-04-10 14:05:00    20.2      3.1   22.4        0.06
125  2023-04-10 14:07:00    20.4      2.3   22.3        0.04
126  2023-04-10 14:08:00    20.7      1.8   23.6        0.06
127  2023-04-10 14:09:00    20.9      2.1   21.5        0.04
128  2023-04-10 14:11:00    20.7      1.4   21.1        0.05
129  2023-04-10 14:12:00    20.9      2.2   21.2        0.04
130  2023-04-10 14:13:00    20.8      1.2   21.1        0.06
131  2023-04-10 14:15:00    21.0      2.2   19.5        0.06
132  2023-04-10 14:16:00    20.8      2.9   19.5        0.03
133  2023-04-10 14:17:00    20.7      1.8   19.1        0.05
134  2023-04-10 14:19:00    20.7      2.6   19.6        0.04
135  2023-04-10 14:20:00    20.7      1.5   19.5        0.06
136  2023-04-10 14:21:00    20.9      3.5   20.2        0.04
137  2023-04-10 14:23:00    21.0      1.9   21.6        0.06
138  2023-04-10 14:24:00    21.0      2.2   20.1        0.03
139  2023-04-10 14:25:00    20.7      2.2   20.4        0.06
140  2023-04-10 14:27:00    20.4      5.0   21.0        0.06
141  2023-04-10 14:28:00    20.4      2.7   21.2        0.05
142  2023-04-10 14:29:00    20.3      2.0   21.3        0.03
143  2023-04-10 14:31:00    20.7      2.0   22.8        0.04
144  2023-04-10 14:32:00    20.9      3.1   22.5        0.06
145  2023-04-10 14:33:00    20.9      2.5   21.4        0.03
146  2023-04-10 16:48:00    21.2      2.6   22.4        0.02
147  2023-04-10 16:49:00    21.2      1.3   22.0        0.01
148  2023-04-10 16:50:00    21.2      2.5   22.0        0.02
149  2023-04-10 16:52:00    21.0      2.4   21.8        0.02
150  2023-04-10 16:53:00    20.9      2.3   21.9        0.02
151  2023-04-10 16:54:00    20.9      2.7   22.8        0.02
152  2023-04-10 16:55:00    21.0      3.2   22.6        0.03
153  2023-04-10 16:57:00    20.9      1.3   23.0        0.01
154  2023-04-10 16:58:00    21.0      2.6   22.0        0.02
155  2023-04-10 16:59:00    21.0      3.0   21.5        0.03
156  2023-04-10 17:01:00    20.9      1.7   21.5        0.00
157  2023-04-10 17:02:00    20.8      2.7   21.8        0.02
158  2023-04-10 17:03:00    20.8      2.2   22.3        0.03
159  2023-04-10 17:05:00    20.8      2.8   23.1        0.02
160  2023-04-10 17:06:00    20.8      1.6   23.0        0.01
161  2023-04-10 17:07:00    20.8      3.0   22.9        0.01
162  2023-04-10 17:09:00    20.9      0.8   23.4        0.02
163  2023-04-10 17:10:00    21.0      0.9   23.6        0.01
164  2023-04-10 17:11:00    21.0      2.4   23.4        0.01
165  2023-04-10 17:13:00    21.0      3.6   23.2        0.02
166  2023-04-10 17:14:00    20.8      2.8   23.2        0.02
167  2023-04-10 17:15:00    20.7      3.1   23.1        0.01
168  2023-04-10 17:17:00    20.6      2.7   23.2        0.02
169  2023-04-10 17:18:00    20.6      2.9   23.6        0.02
170  2023-04-10 17:19:00    20.6      1.6   23.7        0.02
171  2023-04-10 17:21:00    20.7      1.3   23.2        0.01
172  2023-04-10 17:22:00    20.7      1.1   23.4        0.01
173  2023-04-10 17:23:00    20.7      1.4   23.2        0.01
174  2023-04-10 17:25:00    20.8      1.5   23.4        0.01
175  2023-04-10 17:26:00    20.8      2.0   23.4        0.02
176  2023-04-10 17:27:00    20.8      2.3   22.9        0.00
177  2023-04-10 17:29:00    20.6      3.3   23.7        0.01
178  2023-04-10 17:30:00    20.6      3.0   23.9        0.03
179  2023-04-10 17:31:00    20.5      2.4   24.3        0.01
180  2023-04-17 09:21:00    12.1      0.7   63.3        0.03
181  2023-04-17 09:22:00    12.1      1.5   62.8        0.04
182  2023-04-17 09:23:00    12.0      0.9   62.2        0.04
183  2023-04-17 09:25:00    12.1      0.7   62.6        0.04
184  2023-04-17 09:26:00    12.4      1.3   63.4        0.04
185  2023-04-17 09:27:00    12.7      1.2   62.3        0.04
186  2023-04-17 09:29:00    12.9      2.3   59.8        0.04
187  2023-04-17 09:30:00    13.0      1.4   59.5        0.03
188  2023-04-17 09:31:00    13.1      2.5   58.8        0.03
189  2023-04-17 09:33:00    12.5      1.7   56.9        0.04
190  2023-04-17 09:34:00    12.2      1.3   58.1        0.05
191  2023-04-17 09:35:00    12.2      1.7   60.3        0.04
192  2023-04-17 09:37:00    12.4      1.2   58.9        0.03
193  2023-04-17 09:38:00    12.3      0.9   58.8        0.04
194  2023-04-17 09:39:00    12.3      0.4   59.2        0.04
195  2023-04-17 09:41:00    12.5      0.8   59.9        0.04
196  2023-04-17 09:42:00    12.6      1.3   59.7        0.03
197  2023-04-17 09:43:00    12.6      1.2   58.8        0.04
198  2023-04-17 09:45:00    12.8      0.7   57.6        0.04
199  2023-04-17 09:46:00    12.7      1.3   58.1        0.04
200  2023-04-17 09:47:00    12.6      0.8   58.1        0.04
201  2023-04-17 09:49:00    12.8      1.4   58.5        0.04
202  2023-04-17 09:50:00    12.9      1.6   57.5        0.05
203  2023-04-17 09:51:00    13.0      1.7   57.5        0.04
204  2023-04-17 09:53:00    12.8      1.0   57.1        0.04
205  2023-04-17 09:54:00    13.1      0.8   58.2        0.04
206  2023-04-17 09:55:00    13.3      0.8   56.6        0.04
207  2023-04-17 09:57:00    13.3      0.4   53.8        0.04
208  2023-04-17 09:58:00    13.2      0.6   56.4        0.04
209  2023-04-17 09:59:00    13.3      0.7   57.1        0.04
210  2023-04-17 13:38:00    18.5      1.5   27.2        0.05
211  2023-04-17 13:39:00    18.7      1.6   29.9        0.06
212  2023-04-17 13:40:00    18.8      2.1   25.9        0.05
213  2023-04-17 13:42:00    18.8      1.8   26.6        0.07
214  2023-04-17 13:43:00    18.8      2.8   26.9        0.05
215  2023-04-17 13:44:00    18.8      2.6   26.3        0.04
216  2023-04-17 13:46:00    18.7      2.2   27.6        0.04
217  2023-04-17 13:47:00    18.6      2.7   27.6        0.06
218  2023-04-17 13:48:00    18.7      2.0   27.8        0.06
219  2023-04-17 13:50:00    18.6      1.9   28.8        0.06
220  2023-04-17 13:51:00    18.5      2.4   28.5        0.05
221  2023-04-17 13:52:00    18.7      2.1   29.4        0.04
222  2023-04-17 13:54:00    18.7      1.1   28.9        0.04
223  2023-04-17 13:55:00    18.6      0.3   28.4        0.06
224  2023-04-17 13:56:00    18.5      0.2   27.7        0.03
225  2023-04-17 13:58:00    18.6      0.5   28.2        0.05
226  2023-04-17 13:59:00    18.6      0.6   29.3        0.04
227  2023-04-17 14:00:00    18.7      1.0   28.2        0.06
228  2023-04-17 14:02:00    18.8      1.5   29.0        0.06
229  2023-04-17 14:03:00    18.9      1.4   29.2        0.03
230  2023-04-17 14:04:00    19.1      1.2   28.7        0.05
231  2023-04-17 14:06:00    18.9      1.6   27.2        0.04
232  2023-04-17 14:07:00    18.7      1.2   28.6        0.05
233  2023-04-17 14:08:00    18.6      1.8   29.2        0.04
234  2023-04-17 14:10:00    18.7      2.0   27.6        0.05
235  2023-04-17 14:11:00    18.8      0.7   27.8        0.04
236  2023-04-17 14:12:00    19.1      0.3   29.9        0.05
237  2023-04-17 14:14:00    19.2      1.4   27.5        0.06
238  2023-04-17 14:15:00    19.2      1.5   27.8        0.04
239  2023-04-17 14:16:00    19.2      1.3   27.5        0.05
240  2023-04-17 16:51:00    20.0      0.4   27.6        0.02
241  2023-04-17 16:52:00    20.1      0.5   26.9        0.01
242  2023-04-17 16:53:00    20.2      0.7   27.0        0.01
243  2023-04-17 16:56:00    20.5      1.8   26.6        0.01
244  2023-04-17 16:57:00    20.4      1.8   25.5        0.02
245  2023-04-17 16:58:00    20.3      1.3   25.4        0.03
246  2023-04-17 17:00:00    20.2      1.3   25.7        0.01
247  2023-04-17 17:01:00    20.2      1.1   25.9        0.01
248  2023-04-17 17:02:00    20.2      1.1   26.2        0.02
249  2023-04-17 17:04:00    20.1      0.6   25.9        0.02
250  2023-04-17 17:05:00    20.1      0.9   25.5        0.02
251  2023-04-17 17:06:00    20.0      0.4   25.4        0.01
252  2023-04-17 17:08:00    19.8      0.2   25.8        0.01
253  2023-04-17 17:09:00    19.9      0.3   25.6        0.03
254  2023-04-17 17:10:00    20.0      0.2   26.0        0.01
255  2023-04-17 17:12:00    20.2      0.9   26.8        0.01
256  2023-04-17 17:13:00    20.2      1.7   26.3        0.01
257  2023-04-17 17:14:00    20.2      2.1   26.4        0.01
258  2023-04-17 17:16:00    20.1      1.7   26.6        0.02
259  2023-04-17 17:17:00    20.1      0.9   27.4        0.02
260  2023-04-17 17:18:00    20.2      0.8   26.7        0.01
261  2023-04-17 17:20:00    20.3      1.4   27.5        0.01
262  2023-04-17 17:21:00    20.3      1.7   25.6        0.01
263  2023-04-17 17:22:00    20.2      0.7   25.9        0.01
264  2023-04-17 17:24:00    20.1      1.1   25.7        0.02
265  2023-04-17 17:25:00    20.1      1.2   25.7        0.01
266  2023-04-17 17:26:00    20.1      0.9   25.9        0.00
267  2023-04-17 17:28:00    20.2      1.2   27.0        0.01
268  2023-04-17 17:29:00    20.2      1.6   26.5        0.02
269  2023-04-17 17:30:00    20.2      1.5   25.7        0.02
270  2023-04-17 17:31:00    20.1      1.2   26.1        0.01
271  2023-04-17 17:33:00    20.2      1.5   26.6        0.01
272  2023-04-17 17:34:00    20.2      1.1   26.0        0.01
273  2023-04-17 17:35:00    20.2      1.2   26.1        0.01
274  2023-04-24 09:23:00    15.3      2.4   37.9        0.03
275  2023-04-24 09:24:00    15.4      3.5   38.4        0.03
276  2023-04-24 09:25:00    15.5      3.0   37.7        0.03
277  2023-04-24 09:27:00    15.5      2.2   38.3        0.04
278  2023-04-24 09:28:00    15.4      3.1   38.7        0.02
279  2023-04-24 09:29:00    15.5      1.9   38.5        0.03
280  2023-04-24 09:31:00    15.8      4.2   38.0        0.03
281  2023-04-24 09:32:00    15.7      3.2   37.6        0.02
282  2023-04-24 09:33:00    15.6      3.8   37.6        0.04
283  2023-04-24 09:35:00    15.7      3.6   37.2        0.05
284  2023-04-24 09:36:00    15.8      3.9   37.4        0.04
285  2023-04-24 09:37:00    15.8      2.5   37.2        0.03
286  2023-04-24 09:39:00    15.9      4.1   36.9        0.03
287  2023-04-24 09:40:00    16.0      3.2   36.5        0.04
288  2023-04-24 09:41:00    16.0      3.0   36.9        0.03
289  2023-04-24 09:43:00    16.1      4.2   37.1        0.05
290  2023-04-24 09:44:00    16.2      3.9   37.0        0.03
291  2023-04-24 09:45:00    16.1      2.8   36.9        0.03
292  2023-04-24 09:47:00    15.8      3.3   37.3        0.03
293  2023-04-24 09:48:00    16.0      2.7   36.9        0.03
294  2023-04-24 09:49:00    16.1      2.7   37.0        0.03
295  2023-04-24 09:51:00    16.2      0.5   37.5        0.03
296  2023-04-24 09:52:00    16.1      2.0   37.6        0.03
297  2023-04-24 09:53:00    16.1      3.6   37.5        0.04
298  2023-04-24 09:55:00    16.5      1.4   38.3        0.03
299  2023-04-24 09:56:00    16.6      2.1   37.2        0.03
300  2023-04-24 09:57:00    16.6      2.0   36.8        0.03
301  2023-04-24 09:59:00    16.8      2.0   36.6        0.03
302  2023-04-24 10:00:00    16.7      2.9   35.9        0.03
303  2023-04-24 10:01:00    16.5      4.2   36.2        0.03
304  2023-04-24 10:03:00    16.3      3.7   37.2        0.02
305  2023-04-24 10:04:00    16.4      3.9   37.0        0.04
306  2023-04-24 10:05:00    16.4      3.4   36.5        0.04
307  2023-04-24 10:07:00    16.4      3.8   37.2        0.04
308  2023-04-24 10:08:00    16.5      4.1   37.5        0.04
309  2023-04-24 10:09:00    16.3      3.3   35.2        0.03
310  2023-04-24 10:11:00    16.1      3.6   35.8        0.03
311  2023-04-24 10:12:00    16.2      5.0   35.2        0.03
312  2023-04-24 10:13:00    16.2      4.0   35.1        0.05
313  2023-04-24 10:15:00    16.5      3.4   35.2        0.03
314  2023-04-24 10:16:00    16.6      3.6   34.8        0.04
315  2023-04-24 10:17:00    16.5      4.1   34.5        0.04
316  2023-04-24 10:19:00    16.6      4.1   34.9        0.04
317  2023-04-24 10:20:00    16.5      2.6   34.8        0.04
318  2023-04-24 10:21:00    16.4      3.0   35.7        0.04
319  2023-04-24 10:23:00    16.6      3.1   36.3        0.05
320  2023-04-24 10:24:00    16.8      3.1   36.3        0.04
321  2023-04-24 10:25:00    16.6      3.4   35.6        0.04
322  2023-04-24 10:27:00    16.3      2.9   36.8        0.02
323  2023-04-24 10:28:00    16.6      3.4   36.3        0.04
324  2023-04-24 10:29:00    16.7      2.7   35.8        0.03
325  2023-04-24 10:31:00    17.0      4.9   35.6        0.02
326  2023-04-24 10:32:00    16.7      3.7   35.2        0.04
327  2023-04-24 10:33:00    16.4      1.2   35.4        0.04

### soiling 이미지와 비교해서 없는 줄 지우기
#### seg


 "soiling" : {
        "seg":"/app/pytorch-fcn/examples/voc/logs/20230831_174351.813277/result1/",
        "origin" : "./dataset/image/20230516_ch2_crop_resize/"
    }

In [8]:
import os 

# 이름 확인
os.listdir(dataset_folders["soiling"]["seg"])[0:10]

['panel4_NVR_ch2_jpg_20230322164400.png',
 'panel4_NVR_ch2_jpg_20230322164800.png',
 'panel4_NVR_ch2_jpg_20230322165200.png',
 'panel4_NVR_ch2_jpg_20230322165600.png',
 'panel4_NVR_ch2_jpg_20230322170200.png',
 'panel4_NVR_ch2_jpg_20230329091700.png',
 'panel4_NVR_ch2_jpg_20230329092100.png',
 'panel4_NVR_ch2_jpg_20230329092500.png',
 'panel4_NVR_ch2_jpg_20230329092900.png',
 'panel4_NVR_ch2_jpg_20230329093300.png']

In [9]:
import datetime
import glob

indexs = []

for i in df.index :
    date = df.loc[i]['일시'].strftime('%Y%m%d%H%M%S')
    panel = str(df.loc[i]['panel number']) 

    if glob.glob(dataset_folders["soiling"]["seg"]+f"panel{panel}*{date}*") == [] :
        print(i, panel, date)
        indexs.append(i)
df.drop(index=indexs, inplace=True)

6 1 20230329092100
9 1 20230329093300
10 1 20230329093700
152 1 20230410165500
210 1 20230417133800
211 1 20230417133900
212 1 20230417134000
222 1 20230417135400
223 1 20230417135500
224 1 20230417135600
265 1 20230417172500
270 1 20230417173100
337 1 20230424135000
358 1 20230424141900
673 2 20230403135000
693 2 20230403164700
694 2 20230403165100
695 2 20230403165500
696 2 20230403165900
697 2 20230403170300
698 2 20230403170700
699 2 20230403171200
700 2 20230403171800
701 2 20230403172300
702 2 20230403172700
703 2 20230403173100
779 2 20230410165500
837 2 20230417133800
838 2 20230417133900
839 2 20230417134000
849 2 20230417135400
850 2 20230417135500
851 2 20230417135600
892 2 20230417172500
897 2 20230417173100
898 2 20230417173300
899 2 20230417173400
900 2 20230417173500
1254 3 20230322164400
1255 3 20230322164800
1256 3 20230322165200
1257 3 20230322165600
1258 3 20230322170200
1277 3 20230329145800
1278 3 20230329150700
1279 3 20230329164100
1280 3 20230329164500
1281 3 20230329164900
1282 3 20230329165300
1283 3 20230329165700
1284 3 20230329170000
1285 3 20230329170500
1286 3 20230329171000
1287 3 20230329171500
1309 3 20230403142600
1320 3 20230403164700
1321 3 20230403165100
1322 3 20230403165500
1323 3 20230403165900
1324 3 20230403170300
1325 3 20230403170700
1326 3 20230403171200
1327 3 20230403171800
1400 3 20230410164800
1401 3 20230410164900
1402 3 20230410165000
1403 3 20230410165200
1404 3 20230410165300
1405 3 20230410165400
1406 3 20230410165500
1407 3 20230410165700
1408 3 20230410165800
1409 3 20230410165900
1410 3 20230410170100
1411 3 20230410170200
1412 3 20230410170300
1413 3 20230410170500
1414 3 20230410170600
1415 3 20230410170700
1416 3 20230410170900
1417 3 20230410171000
1418 3 20230410171100
1419 3 20230410171300
1420 3 20230410171400
1421 3 20230410171500
1422 3 20230410171700
1423 3 20230410171800
1424 3 20230410171900
1425 3 20230410172100
1426 3 20230410172200
1427 3 20230410172300
1428 3 20230410172500
1429 3 20230410172600
1430 3 20230410172700
1431 3 20230410172900
1432 3 20230410173000
1433 3 20230410173100
1434 3 20230417092100
1435 3 20230417092200
1436 3 20230417092300
1437 3 20230417092500
1438 3 20230417092600
1439 3 20230417092700
1440 3 20230417092900
1441 3 20230417093000
1442 3 20230417093100
1443 3 20230417093300
1444 3 20230417093400
1445 3 20230417093500
1446 3 20230417093700
1447 3 20230417093800
1448 3 20230417093900
1449 3 20230417094100
1450 3 20230417094200
1451 3 20230417094300
1452 3 20230417094500
1453 3 20230417094600
1454 3 20230417094700
1455 3 20230417094900
1456 3 20230417095000
1457 3 20230417095100
1458 3 20230417095300
1459 3 20230417095400
1460 3 20230417095500
1461 3 20230417095700
1462 3 20230417095800
1463 3 20230417095900
1464 3 20230417133800
1465 3 20230417133900
1466 3 20230417134000
1476 3 20230417135400
1477 3 20230417135500
1478 3 20230417135600
1519 3 20230417172500
1524 3 20230417173100
1589 3 20230424134700
1590 3 20230424134800
1601 3 20230424140300
1609 3 20230424141400
1610 3 20230424141500
1611 3 20230424141600
1614 3 20230424142100
1617 3 20230424142500
1618 3 20230424142700
1619 3 20230424142800
1620 3 20230424142900
1621 3 20230424143100
1622 3 20230424143200
1623 3 20230424143400
1624 3 20230424143500
1625 3 20230424143600
1626 3 20230424143800
1627 3 20230424143900
1628 3 20230424144000
1629 3 20230424144200
1630 3 20230424144300
1631 3 20230424144400
1632 3 20230424144600
1633 3 20230424144700
1634 3 20230424144800
1635 3 20230424145000
1636 3 20230424145100
1637 3 20230424145200
1638 3 20230424145400
1639 3 20230424145500
1640 3 20230424145600
1641 3 20230424145800
1642 3 20230424145900
1643 3 20230424150000
1644 3 20230424150200
1645 3 20230424150300
1646 3 20230424150400
1781 3 20230501145300
2033 4 20230410165500
2091 4 20230417133800
2092 4 20230417133900
2093 4 20230417134000
2103 4 20230417135400
2104 4 20230417135500
2105 4 20230417135600
2146 4 20230417172500
2151 4 20230417173100
2218 4 20230424135000

In [10]:
df

                      일시  기온(°C)  풍속(m/s)  습도(%)  일사(MJ/m^2)  \
0    2023-03-22 16:44:00    24.8      0.6   35.1        0.01
1    2023-03-22 16:48:00    24.8      0.3   35.5        0.02
2    2023-03-22 16:52:00    25.1      1.6   35.4        0.03
3    2023-03-22 16:56:00    24.7      1.9   35.6        0.02
4    2023-03-22 17:02:00    24.6      2.2   36.0        0.00
5    2023-03-29 09:17:00     8.8      0.4   55.2        0.03
7    2023-03-29 09:25:00     9.2      0.2   55.4        0.03
8    2023-03-29 09:29:00     9.4      0.7   55.9        0.03
11   2023-03-29 09:42:00    10.0      0.4   51.2        0.03
12   2023-03-29 14:14:00    20.1      0.8   16.1        0.05
13   2023-03-29 14:18:00    19.7      1.5   15.4        0.04
14   2023-03-29 14:22:00    19.8      0.8   17.2        0.05
15   2023-03-29 14:26:00    19.7      1.5   15.0        0.05
16   2023-03-29 14:30:00    19.9      1.3   16.5        0.06
17   2023-03-29 14:34:00    19.6      0.3   16.9        0.06
18   2023-03-29 14:38:00    19.4      0.4   17.5        0.05
19   2023-03-29 14:42:00    19.7      0.6   16.9        0.05
20   2023-03-29 14:46:00    20.2      1.2   18.0        0.05
21   2023-03-29 14:50:00    20.0      0.9   19.8        0.05
22   2023-03-29 14:54:00    20.0      1.7   17.5        0.04
23   2023-03-29 14:58:00    19.7      0.9   17.0        0.05
24   2023-03-29 15:07:00    19.8      1.3   18.5        0.03
25   2023-03-29 16:41:00    20.7      1.7   12.8        0.02
26   2023-03-29 16:45:00    20.5      1.2   12.4        0.02
27   2023-03-29 16:49:00    20.7      1.2   12.8        0.02
28   2023-03-29 16:53:00    20.7      2.2   13.0        0.01
29   2023-03-29 16:57:00    20.7      0.5   14.2        0.01
30   2023-03-29 17:00:00    20.7      0.8   14.4        0.00
31   2023-03-29 17:05:00    20.6      0.4   13.9        0.00
32   2023-03-29 17:10:00    20.3      1.8   15.0        0.01
33   2023-03-29 17:15:00    20.1      1.1   15.2        0.01
36   2023-04-03 09:36:00    16.0      1.9   24.1        0.02
37   2023-04-03 09:40:00    16.3      2.2   24.5        0.04
38   2023-04-03 09:45:00    16.3      1.9   24.1        0.04
39   2023-04-03 09:49:00    16.2      0.6   24.8        0.03
40   2023-04-03 09:53:00    16.4      2.2   24.3        0.04
41   2023-04-03 09:57:00    16.5      2.7   24.2        0.04
42   2023-04-03 10:01:00    16.4      1.9   24.4        0.04
43   2023-04-03 10:06:00    16.7      1.2   24.2        0.04
44   2023-04-03 10:11:00    16.9      1.9   24.1        0.04
45   2023-04-03 10:15:00    17.2      1.8   23.5        0.04
46   2023-04-03 13:50:00    22.1      3.0   21.4        0.04
47   2023-04-03 13:54:00    22.7      5.2   21.4        0.04
48   2023-04-03 13:58:00    22.5      3.3   22.2        0.05
49   2023-04-03 14:02:00    22.9      5.5   21.2        0.05
50   2023-04-03 14:06:00    22.6      4.2   21.9        0.04
51   2023-04-03 14:10:00    22.6      3.9   21.2        0.05
52   2023-04-03 14:14:00    22.8      3.8   21.9        0.06
53   2023-04-03 14:18:00    22.8      2.7   22.5        0.04
54   2023-04-03 14:22:00    23.0      6.7   20.8        0.06
55   2023-04-03 14:26:00    22.7      3.8   20.5        0.04
56   2023-04-03 14:44:00    22.2      5.3   23.5        0.03
57   2023-04-03 14:48:00    22.7      7.7   23.1        0.03
58   2023-04-03 14:52:00    22.7      3.3   23.3        0.05
59   2023-04-03 14:56:00    22.9      3.3   23.3        0.05
60   2023-04-03 15:00:00    22.7      3.4   22.4        0.06
61   2023-04-03 15:04:00    22.8      4.1   22.0        0.05
62   2023-04-03 15:08:00    23.0      3.2   22.1        0.05
63   2023-04-03 15:12:00    23.2      2.2   22.2        0.05
64   2023-04-03 15:16:00    22.8      2.5   22.6        0.05
65   2023-04-03 15:20:00    22.8      4.4   22.2        0.05
66   2023-04-03 16:47:00    23.6      1.2   19.7        0.01
67   2023-04-03 16:51:00    23.7      3.2   19.4        0.01
68   2023-04-03 16:55:00    23.7      3.0   19.1        0.01
69   2023-04-03 16:59:00    23.5      3.4   19.1        0.02
70   2023-04-03 17:03:00    23.3      2.1   19.3        0.02
71   2023-04-03 17:07:00    23.3      3.2   19.4        0.03
72   2023-04-03 17:12:00    23.1      2.7   19.8        0.01
73   2023-04-03 17:18:00    23.1      3.0   20.3        0.01
74   2023-04-03 17:23:00    23.2      2.1   20.1        0.01
75   2023-04-03 17:27:00    23.1      2.5   20.1        0.01
76   2023-04-03 17:31:00    23.2      2.0   20.2        0.01
77   2023-04-10 09:18:00    11.9      1.1   34.6        0.04
78   2023-04-10 09:19:00    12.0      1.4   34.8        0.03
79   2023-04-10 09:20:00    12.1      1.3   34.3        0.03
80   2023-04-10 09:22:00    12.2      0.2   34.7        0.03
81   2023-04-10 09:23:00    12.3      0.0   34.5        0.04
82   2023-04-10 09:24:00    12.5      0.3   34.7        0.04
83   2023-04-10 09:26:00    12.6      0.7   34.6        0.03
84   2023-04-10 09:27:00    12.6      1.4   34.2        0.03
85   2023-04-10 09:28:00    12.5      1.4   34.0        0.03
86   2023-04-10 09:30:00    12.4      0.9   35.1        0.04
87   2023-04-10 09:31:00    12.5      0.7   34.3        0.04
88   2023-04-10 09:32:00    12.5      0.4   34.0        0.04
89   2023-04-10 09:34:00    12.5      0.6   34.0        0.03
90   2023-04-10 09:35:00    12.6      0.5   34.3        0.04
91   2023-04-10 09:36:00    12.6      0.7   34.1        0.03
92   2023-04-10 09:38:00    12.7      0.3   34.6        0.05
93   2023-04-10 09:39:00    12.8      0.1   33.6        0.03
94   2023-04-10 09:40:00    12.9      1.1   33.7        0.04
95   2023-04-10 09:42:00    13.3      0.2   34.3        0.04
96   2023-04-10 09:43:00    13.7      0.3   33.6        0.04
97   2023-04-10 09:44:00    13.9      1.2   33.2        0.05
98   2023-04-10 09:46:00    13.6      0.6   32.1        0.04
99   2023-04-10 09:47:00    13.6      1.2   31.7        0.04
100  2023-04-10 09:48:00    13.6      1.1   32.0        0.03
101  2023-04-10 09:50:00    13.3      1.6   31.2        0.04
102  2023-04-10 09:51:00    13.3      1.6   31.4        0.05
103  2023-04-10 09:52:00    13.3      1.1   32.2        0.04
104  2023-04-10 09:54:00    13.7      2.4   31.7        0.04
105  2023-04-10 09:55:00    13.4      1.3   31.3        0.04
106  2023-04-10 09:56:00    13.2      1.0   32.3        0.04
107  2023-04-10 13:43:00    20.1      3.1   22.4        0.04
108  2023-04-10 13:44:00    20.1      5.1   21.7        0.07
109  2023-04-10 13:45:00    19.9      2.8   21.6        0.05
110  2023-04-10 13:47:00    19.7      3.1   21.9        0.04
111  2023-04-10 13:48:00    19.7      2.8   22.8        0.07
112  2023-04-10 13:49:00    19.8      2.3   22.6        0.05
113  2023-04-10 13:51:00    20.1      3.5   21.9        0.04
114  2023-04-10 13:52:00    20.1      2.4   22.6        0.06
115  2023-04-10 13:53:00    20.4      3.0   22.0        0.05
116  2023-04-10 13:55:00    20.2      3.0   21.7        0.06
117  2023-04-10 13:56:00    20.2      4.1   21.9        0.04
118  2023-04-10 13:57:00    20.1      3.9   21.2        0.05
119  2023-04-10 13:59:00    20.2      2.4   21.9        0.04
120  2023-04-10 14:00:00    20.4      2.1   22.2        0.06
121  2023-04-10 14:01:00    20.5      4.0   21.4        0.04
122  2023-04-10 14:03:00    20.3      3.0   22.0        0.06
123  2023-04-10 14:04:00    20.3      4.1   22.0        0.04
124  2023-04-10 14:05:00    20.2      3.1   22.4        0.06
125  2023-04-10 14:07:00    20.4      2.3   22.3        0.04
126  2023-04-10 14:08:00    20.7      1.8   23.6        0.06
127  2023-04-10 14:09:00    20.9      2.1   21.5        0.04
128  2023-04-10 14:11:00    20.7      1.4   21.1        0.05
129  2023-04-10 14:12:00    20.9      2.2   21.2        0.04
130  2023-04-10 14:13:00    20.8      1.2   21.1        0.06
131  2023-04-10 14:15:00    21.0      2.2   19.5        0.06
132  2023-04-10 14:16:00    20.8      2.9   19.5        0.03
133  2023-04-10 14:17:00    20.7      1.8   19.1        0.05
134  2023-04-10 14:19:00    20.7      2.6   19.6        0.04
135  2023-04-10 14:20:00    20.7      1.5   19.5        0.06
136  2023-04-10 14:21:00    20.9      3.5   20.2        0.04
137  2023-04-10 14:23:00    21.0      1.9   21.6        0.06
138  2023-04-10 14:24:00    21.0      2.2   20.1        0.03
139  2023-04-10 14:25:00    20.7      2.2   20.4        0.06
140  2023-04-10 14:27:00    20.4      5.0   21.0        0.06
141  2023-04-10 14:28:00    20.4      2.7   21.2        0.05
142  2023-04-10 14:29:00    20.3      2.0   21.3        0.03
143  2023-04-10 14:31:00    20.7      2.0   22.8        0.04
144  2023-04-10 14:32:00    20.9      3.1   22.5        0.06
145  2023-04-10 14:33:00    20.9      2.5   21.4        0.03
146  2023-04-10 16:48:00    21.2      2.6   22.4        0.02
147  2023-04-10 16:49:00    21.2      1.3   22.0        0.01
148  2023-04-10 16:50:00    21.2      2.5   22.0        0.02
149  2023-04-10 16:52:00    21.0      2.4   21.8        0.02
150  2023-04-10 16:53:00    20.9      2.3   21.9        0.02
151  2023-04-10 16:54:00    20.9      2.7   22.8        0.02
153  2023-04-10 16:57:00    20.9      1.3   23.0        0.01
154  2023-04-10 16:58:00    21.0      2.6   22.0        0.02
155  2023-04-10 16:59:00    21.0      3.0   21.5        0.03
156  2023-04-10 17:01:00    20.9      1.7   21.5        0.00
157  2023-04-10 17:02:00    20.8      2.7   21.8        0.02
158  2023-04-10 17:03:00    20.8      2.2   22.3        0.03
159  2023-04-10 17:05:00    20.8      2.8   23.1        0.02
160  2023-04-10 17:06:00    20.8      1.6   23.0        0.01
161  2023-04-10 17:07:00    20.8      3.0   22.9        0.01
162  2023-04-10 17:09:00    20.9      0.8   23.4        0.02
163  2023-04-10 17:10:00    21.0      0.9   23.6        0.01
164  2023-04-10 17:11:00    21.0      2.4   23.4        0.01
165  2023-04-10 17:13:00    21.0      3.6   23.2        0.02
166  2023-04-10 17:14:00    20.8      2.8   23.2        0.02
167  2023-04-10 17:15:00    20.7      3.1   23.1        0.01
168  2023-04-10 17:17:00    20.6      2.7   23.2        0.02
169  2023-04-10 17:18:00    20.6      2.9   23.6        0.02
170  2023-04-10 17:19:00    20.6      1.6   23.7        0.02
171  2023-04-10 17:21:00    20.7      1.3   23.2        0.01
172  2023-04-10 17:22:00    20.7      1.1   23.4        0.01
173  2023-04-10 17:23:00    20.7      1.4   23.2        0.01
174  2023-04-10 17:25:00    20.8      1.5   23.4        0.01
175  2023-04-10 17:26:00    20.8      2.0   23.4        0.02
176  2023-04-10 17:27:00    20.8      2.3   22.9        0.00
177  2023-04-10 17:29:00    20.6      3.3   23.7        0.01
178  2023-04-10 17:30:00    20.6      3.0   23.9        0.03
179  2023-04-10 17:31:00    20.5      2.4   24.3        0.01
180  2023-04-17 09:21:00    12.1      0.7   63.3        0.03
181  2023-04-17 09:22:00    12.1      1.5   62.8        0.04
182  2023-04-17 09:23:00    12.0      0.9   62.2        0.04
183  2023-04-17 09:25:00    12.1      0.7   62.6        0.04
184  2023-04-17 09:26:00    12.4      1.3   63.4        0.04
185  2023-04-17 09:27:00    12.7      1.2   62.3        0.04
186  2023-04-17 09:29:00    12.9      2.3   59.8        0.04
187  2023-04-17 09:30:00    13.0      1.4   59.5        0.03
188  2023-04-17 09:31:00    13.1      2.5   58.8        0.03
189  2023-04-17 09:33:00    12.5      1.7   56.9        0.04
190  2023-04-17 09:34:00    12.2      1.3   58.1        0.05
191  2023-04-17 09:35:00    12.2      1.7   60.3        0.04
192  2023-04-17 09:37:00    12.4      1.2   58.9        0.03
193  2023-04-17 09:38:00    12.3      0.9   58.8        0.04
194  2023-04-17 09:39:00    12.3      0.4   59.2        0.04
195  2023-04-17 09:41:00    12.5      0.8   59.9        0.04
196  2023-04-17 09:42:00    12.6      1.3   59.7        0.03
197  2023-04-17 09:43:00    12.6      1.2   58.8        0.04
198  2023-04-17 09:45:00    12.8      0.7   57.6        0.04
199  2023-04-17 09:46:00    12.7      1.3   58.1        0.04
200  2023-04-17 09:47:00    12.6      0.8   58.1        0.04
201  2023-04-17 09:49:00    12.8      1.4   58.5        0.04
202  2023-04-17 09:50:00    12.9      1.6   57.5        0.05
203  2023-04-17 09:51:00    13.0      1.7   57.5        0.04
204  2023-04-17 09:53:00    12.8      1.0   57.1        0.04
205  2023-04-17 09:54:00    13.1      0.8   58.2        0.04
206  2023-04-17 09:55:00    13.3      0.8   56.6        0.04
207  2023-04-17 09:57:00    13.3      0.4   53.8        0.04
208  2023-04-17 09:58:00    13.2      0.6   56.4        0.04
209  2023-04-17 09:59:00    13.3      0.7   57.1        0.04
213  2023-04-17 13:42:00    18.8      1.8   26.6        0.07
214  2023-04-17 13:43:00    18.8      2.8   26.9        0.05
215  2023-04-17 13:44:00    18.8      2.6   26.3        0.04
216  2023-04-17 13:46:00    18.7      2.2   27.6        0.04
217  2023-04-17 13:47:00    18.6      2.7   27.6        0.06
218  2023-04-17 13:48:00    18.7      2.0   27.8        0.06
219  2023-04-17 13:50:00    18.6      1.9   28.8        0.06
220  2023-04-17 13:51:00    18.5      2.4   28.5        0.05
221  2023-04-17 13:52:00    18.7      2.1   29.4        0.04
225  2023-04-17 13:58:00    18.6      0.5   28.2        0.05
226  2023-04-17 13:59:00    18.6      0.6   29.3        0.04
227  2023-04-17 14:00:00    18.7      1.0   28.2        0.06
228  2023-04-17 14:02:00    18.8      1.5   29.0        0.06
229  2023-04-17 14:03:00    18.9      1.4   29.2        0.03
230  2023-04-17 14:04:00    19.1      1.2   28.7        0.05
231  2023-04-17 14:06:00    18.9      1.6   27.2        0.04
232  2023-04-17 14:07:00    18.7      1.2   28.6        0.05
233  2023-04-17 14:08:00    18.6      1.8   29.2        0.04
234  2023-04-17 14:10:00    18.7      2.0   27.6        0.05
235  2023-04-17 14:11:00    18.8      0.7   27.8        0.04
236  2023-04-17 14:12:00    19.1      0.3   29.9        0.05
237  2023-04-17 14:14:00    19.2      1.4   27.5        0.06
238  2023-04-17 14:15:00    19.2      1.5   27.8        0.04
239  2023-04-17 14:16:00    19.2      1.3   27.5        0.05
240  2023-04-17 16:51:00    20.0      0.4   27.6        0.02
241  2023-04-17 16:52:00    20.1      0.5   26.9        0.01
242  2023-04-17 16:53:00    20.2      0.7   27.0        0.01
243  2023-04-17 16:56:00    20.5      1.8   26.6        0.01
244  2023-04-17 16:57:00    20.4      1.8   25.5        0.02
245  2023-04-17 16:58:00    20.3      1.3   25.4        0.03
246  2023-04-17 17:00:00    20.2      1.3   25.7        0.01
247  2023-04-17 17:01:00    20.2      1.1   25.9        0.01
248  2023-04-17 17:02:00    20.2      1.1   26.2        0.02
249  2023-04-17 17:04:00    20.1      0.6   25.9        0.02
250  2023-04-17 17:05:00    20.1      0.9   25.5        0.02
251  2023-04-17 17:06:00    20.0      0.4   25.4        0.01
252  2023-04-17 17:08:00    19.8      0.2   25.8        0.01
253  2023-04-17 17:09:00    19.9      0.3   25.6        0.03
254  2023-04-17 17:10:00    20.0      0.2   26.0        0.01
255  2023-04-17 17:12:00    20.2      0.9   26.8        0.01
256  2023-04-17 17:13:00    20.2      1.7   26.3        0.01
257  2023-04-17 17:14:00    20.2      2.1   26.4        0.01
258  2023-04-17 17:16:00    20.1      1.7   26.6        0.02
259  2023-04-17 17:17:00    20.1      0.9   27.4        0.02
260  2023-04-17 17:18:00    20.2      0.8   26.7        0.01
261  2023-04-17 17:20:00    20.3      1.4   27.5        0.01
262  2023-04-17 17:21:00    20.3      1.7   25.6        0.01
263  2023-04-17 17:22:00    20.2      0.7   25.9        0.01
264  2023-04-17 17:24:00    20.1      1.1   25.7        0.02
266  2023-04-17 17:26:00    20.1      0.9   25.9        0.00
267  2023-04-17 17:28:00    20.2      1.2   27.0        0.01
268  2023-04-17 17:29:00    20.2      1.6   26.5        0.02
269  2023-04-17 17:30:00    20.2      1.5   25.7        0.02
271  2023-04-17 17:33:00    20.2      1.5   26.6        0.01
272  2023-04-17 17:34:00    20.2      1.1   26.0        0.01
273  2023-04-17 17:35:00    20.2      1.2   26.1        0.01
274  2023-04-24 09:23:00    15.3      2.4   37.9        0.03
275  2023-04-24 09:24:00    15.4      3.5   38.4        0.03
276  2023-04-24 09:25:00    15.5      3.0   37.7        0.03
277  2023-04-24 09:27:00    15.5      2.2   38.3        0.04
278  2023-04-24 09:28:00    15.4      3.1   38.7        0.02
279  2023-04-24 09:29:00    15.5      1.9   38.5        0.03
280  2023-04-24 09:31:00    15.8      4.2   38.0        0.03
281  2023-04-24 09:32:00    15.7      3.2   37.6        0.02
282  2023-04-24 09:33:00    15.6      3.8   37.6        0.04
283  2023-04-24 09:35:00    15.7      3.6   37.2        0.05
284  2023-04-24 09:36:00    15.8      3.9   37.4        0.04
285  2023-04-24 09:37:00    15.8      2.5   37.2        0.03
286  2023-04-24 09:39:00    15.9      4.1   36.9        0.03
287  2023-04-24 09:40:00    16.0      3.2   36.5        0.04
288  2023-04-24 09:41:00    16.0      3.0   36.9        0.03
289  2023-04-24 09:43:00    16.1      4.2   37.1        0.05
290  2023-04-24 09:44:00    16.2      3.9   37.0        0.03
291  2023-04-24 09:45:00    16.1      2.8   36.9        0.03
292  2023-04-24 09:47:00    15.8      3.3   37.3        0.03
293  2023-04-24 09:48:00    16.0      2.7   36.9        0.03
294  2023-04-24 09:49:00    16.1      2.7   37.0        0.03
295  2023-04-24 09:51:00    16.2      0.5   37.5        0.03
296  2023-04-24 09:52:00    16.1      2.0   37.6        0.03
297  2023-04-24 09:53:00    16.1      3.6   37.5        0.04
298  2023-04-24 09:55:00    16.5      1.4   38.3        0.03
299  2023-04-24 09:56:00    16.6      2.1   37.2        0.03
300  2023-04-24 09:57:00    16.6      2.0   36.8        0.03
301  2023-04-24 09:59:00    16.8      2.0   36.6        0.03
302  2023-04-24 10:00:00    16.7      2.9   35.9        0.03
303  2023-04-24 10:01:00    16.5      4.2   36.2        0.03
304  2023-04-24 10:03:00    16.3      3.7   37.2        0.02
305  2023-04-24 10:04:00    16.4      3.9   37.0        0.04
306  2023-04-24 10:05:00    16.4      3.4   36.5        0.04
307  2023-04-24 10:07:00    16.4      3.8   37.2        0.04
308  2023-04-24 10:08:00    16.5      4.1   37.5        0.04
309  2023-04-24 10:09:00    16.3      3.3   35.2        0.03
310  2023-04-24 10:11:00    16.1      3.6   35.8        0.03
311  2023-04-24 10:12:00    16.2      5.0   35.2        0.03
312  2023-04-24 10:13:00    16.2      4.0   35.1        0.05
313  2023-04-24 10:15:00    16.5      3.4   35.2        0.03
314  2023-04-24 10:16:00    16.6      3.6   34.8        0.04
315  2023-04-24 10:17:00    16.5      4.1   34.5        0.04
316  2023-04-24 10:19:00    16.6      4.1   34.9        0.04
317  2023-04-24 10:20:00    16.5      2.6   34.8        0.04
318  2023-04-24 10:21:00    16.4      3.0   35.7        0.04
319  2023-04-24 10:23:00    16.6      3.1   36.3        0.05
320  2023-04-24 10:24:00    16.8      3.1   36.3        0.04
321  2023-04-24 10:25:00    16.6      3.4   35.6        0.04
322  2023-04-24 10:27:00    16.3      2.9   36.8        0.02
323  2023-04-24 10:28:00    16.6      3.4   36.3        0.04
324  2023-04-24 10:29:00    16.7      2.7   35.8        0.03
325  2023-04-24 10:31:00    17.0      4.9   35.6        0.02
326  2023-04-24 10:32:00    16.7      3.7   35.2        0.04
327  2023-04-24 10:33:00    16.4      1.2   35.4        0.04
328  2023-04-24 10:35:00    16.8      2.4   36.3        0.04
329  2023-04-24 10:36:00    17.1      1.8   36.3        0.05
330  2023-04-24 10:37:00    17.1      1.9   34.9        0.04
331  2023-04-24 10:39:00    16.9      1.9   34.5        0.04
332  2023-04-24 10:40:00    16.9      1.8   33.9        0.02
333  2023-04-24 10:41:00    16.9      1.4   35.1        0.04
334  2023-04-24 13:46:00    18.1      2.6   35.2        0.07
335  2023-04-24 13:47:00    18.5      2.8   34.9        0.07
336  2023-04-24 13:48:00    18.7      3.2   31.8        0.05
338  2023-04-24 13:51:00    19.6      2.0   31.0        0.08
339  2023-04-24 13:52:00    19.3      3.4   31.7        0.05
340  2023-04-24 13:54:00    19.3      3.4   30.3        0.05

#### origin

In [11]:
# 이름 확인
os.listdir(dataset_folders["soiling"]["origin"])[0:10]

['panel1_NVR_ch2_jpg_20230322164400.jpg',
 'panel1_NVR_ch2_jpg_20230322164800.jpg',
 'panel1_NVR_ch2_jpg_20230322165200.jpg',
 'panel1_NVR_ch2_jpg_20230322165600.jpg',
 'panel1_NVR_ch2_jpg_20230322170200.jpg',
 'panel1_NVR_ch2_jpg_20230329091700.jpg',
 'panel1_NVR_ch2_jpg_20230329092100.jpg',
 'panel1_NVR_ch2_jpg_20230329092500.jpg',
 'panel1_NVR_ch2_jpg_20230329092900.jpg',
 'panel1_NVR_ch2_jpg_20230329093300.jpg']

In [12]:
indexs = []

for i in df.index :
    date = df.loc[i]['일시'].strftime('%Y%m%d%H%M%S')
    panel = str(df.loc[i]['panel number']) 
    
    if glob.glob(dataset_folders["soiling"]["origin"]+f"panel{panel}*{date}*") == [] :
        print(i, panel, date)
        indexs.append(i)
        
df.drop(index=indexs, inplace=True)

### cloud 이미지와 비교해서 없는 줄 지우기
#### seg


    "cloud" :{
        "seg" : "./segmentationModel/results/20230605_ch1_crop_mask/FCN/",
        "origin" : "./dataset/image/20230605_ch1_crop/test/Image/"

In [13]:
# 이름 확인
os.listdir(dataset_folders["cloud"]["seg"])[0:10]

['panel1_NVR_ch1_jpg_20230322164400.jpg_62.9308.jpg',
 'panel1_NVR_ch1_jpg_20230322164800.jpg_79.6429.jpg',
 'panel1_NVR_ch1_jpg_20230322165200.jpg_95.1866.jpg',
 'panel1_NVR_ch1_jpg_20230322165600.jpg_95.0747.jpg',
 'panel1_NVR_ch1_jpg_20230322170200.jpg_92.5118.jpg',
 'panel1_NVR_ch1_jpg_20230329091700.jpg_13.1237.jpg',
 'panel1_NVR_ch1_jpg_20230329092100.jpg_9.8265.jpg',
 'panel1_NVR_ch1_jpg_20230329092500.jpg_11.9565.jpg',
 'panel1_NVR_ch1_jpg_20230329092900.jpg_7.5293.jpg',
 'panel1_NVR_ch1_jpg_20230329093300.jpg_10.9067.jpg']

In [14]:
indexs = []

for i in df.index :
    date = df.loc[i]['일시'].strftime('%Y%m%d%H%M%S')
    panel = str(df.loc[i]['panel number']) 

    if glob.glob(dataset_folders["cloud"]["seg"]+f"*{date}*") == [] :
        print(i, panel, date)
        indexs.append(i)
        
df.drop(index=indexs, inplace=True)

#### origin

In [15]:
# 이름 확인
os.listdir(dataset_folders["cloud"]["origin"])[0:10]

['panel1_NVR_ch1_jpg_20230322164400.jpg',
 'panel1_NVR_ch1_jpg_20230322164800.jpg',
 'panel1_NVR_ch1_jpg_20230322165200.jpg',
 'panel1_NVR_ch1_jpg_20230322165600.jpg',
 'panel1_NVR_ch1_jpg_20230322170200.jpg',
 'panel1_NVR_ch1_jpg_20230329091700.jpg',
 'panel1_NVR_ch1_jpg_20230329092100.jpg',
 'panel1_NVR_ch1_jpg_20230329092500.jpg',
 'panel1_NVR_ch1_jpg_20230329092900.jpg',
 'panel1_NVR_ch1_jpg_20230329093300.jpg']

In [16]:
indexs = []

for i in df.index :
    date = df.loc[i]['일시'].strftime('%Y%m%d%H%M%S')
    panel = str(df.loc[i]['panel number']) 

    if glob.glob(dataset_folders["cloud"]["origin"]+f"*{date}*") == [] :
        print(i, panel, date)
        indexs.append(i)
        
df.drop(index=indexs, inplace=True)

In [17]:
df = df.reset_index(drop =True)
df

                      일시  기온(°C)  풍속(m/s)  습도(%)  일사(MJ/m^2)  \
0    2023-03-22 16:44:00    24.8      0.6   35.1        0.01
1    2023-03-22 16:48:00    24.8      0.3   35.5        0.02
2    2023-03-22 16:52:00    25.1      1.6   35.4        0.03
3    2023-03-22 16:56:00    24.7      1.9   35.6        0.02
4    2023-03-22 17:02:00    24.6      2.2   36.0        0.00
5    2023-03-29 09:17:00     8.8      0.4   55.2        0.03
6    2023-03-29 09:25:00     9.2      0.2   55.4        0.03
7    2023-03-29 09:29:00     9.4      0.7   55.9        0.03
8    2023-03-29 09:42:00    10.0      0.4   51.2        0.03
9    2023-03-29 14:14:00    20.1      0.8   16.1        0.05
10   2023-03-29 14:18:00    19.7      1.5   15.4        0.04
11   2023-03-29 14:22:00    19.8      0.8   17.2        0.05
12   2023-03-29 14:26:00    19.7      1.5   15.0        0.05
13   2023-03-29 14:30:00    19.9      1.3   16.5        0.06
14   2023-03-29 14:34:00    19.6      0.3   16.9        0.06
15   2023-03-29 14:38:00    19.4      0.4   17.5        0.05
16   2023-03-29 14:42:00    19.7      0.6   16.9        0.05
17   2023-03-29 14:46:00    20.2      1.2   18.0        0.05
18   2023-03-29 14:50:00    20.0      0.9   19.8        0.05
19   2023-03-29 14:54:00    20.0      1.7   17.5        0.04
20   2023-03-29 14:58:00    19.7      0.9   17.0        0.05
21   2023-03-29 15:07:00    19.8      1.3   18.5        0.03
22   2023-03-29 16:41:00    20.7      1.7   12.8        0.02
23   2023-03-29 16:45:00    20.5      1.2   12.4        0.02
24   2023-03-29 16:49:00    20.7      1.2   12.8        0.02
25   2023-03-29 16:53:00    20.7      2.2   13.0        0.01
26   2023-03-29 16:57:00    20.7      0.5   14.2        0.01
27   2023-03-29 17:00:00    20.7      0.8   14.4        0.00
28   2023-03-29 17:05:00    20.6      0.4   13.9        0.00
29   2023-03-29 17:10:00    20.3      1.8   15.0        0.01
30   2023-03-29 17:15:00    20.1      1.1   15.2        0.01
31   2023-04-03 09:36:00    16.0      1.9   24.1        0.02
32   2023-04-03 09:40:00    16.3      2.2   24.5        0.04
33   2023-04-03 09:45:00    16.3      1.9   24.1        0.04
34   2023-04-03 09:49:00    16.2      0.6   24.8        0.03
35   2023-04-03 09:53:00    16.4      2.2   24.3        0.04
36   2023-04-03 09:57:00    16.5      2.7   24.2        0.04
37   2023-04-03 10:01:00    16.4      1.9   24.4        0.04
38   2023-04-03 10:06:00    16.7      1.2   24.2        0.04
39   2023-04-03 10:11:00    16.9      1.9   24.1        0.04
40   2023-04-03 10:15:00    17.2      1.8   23.5        0.04
41   2023-04-03 13:50:00    22.1      3.0   21.4        0.04
42   2023-04-03 13:54:00    22.7      5.2   21.4        0.04
43   2023-04-03 13:58:00    22.5      3.3   22.2        0.05
44   2023-04-03 14:02:00    22.9      5.5   21.2        0.05
45   2023-04-03 14:06:00    22.6      4.2   21.9        0.04
46   2023-04-03 14:10:00    22.6      3.9   21.2        0.05
47   2023-04-03 14:14:00    22.8      3.8   21.9        0.06
48   2023-04-03 14:18:00    22.8      2.7   22.5        0.04
49   2023-04-03 14:22:00    23.0      6.7   20.8        0.06
50   2023-04-03 14:26:00    22.7      3.8   20.5        0.04
51   2023-04-03 14:44:00    22.2      5.3   23.5        0.03
52   2023-04-03 14:48:00    22.7      7.7   23.1        0.03
53   2023-04-03 14:52:00    22.7      3.3   23.3        0.05
54   2023-04-03 14:56:00    22.9      3.3   23.3        0.05
55   2023-04-03 15:00:00    22.7      3.4   22.4        0.06
56   2023-04-03 15:04:00    22.8      4.1   22.0        0.05
57   2023-04-03 15:08:00    23.0      3.2   22.1        0.05
58   2023-04-03 15:12:00    23.2      2.2   22.2        0.05
59   2023-04-03 15:16:00    22.8      2.5   22.6        0.05
60   2023-04-03 15:20:00    22.8      4.4   22.2        0.05
61   2023-04-03 16:47:00    23.6      1.2   19.7        0.01
62   2023-04-03 16:51:00    23.7      3.2   19.4        0.01
63   2023-04-03 16:55:00    23.7      3.0   19.1        0.01
64   2023-04-03 16:59:00    23.5      3.4   19.1        0.02
65   2023-04-03 17:03:00    23.3      2.1   19.3        0.02
66   2023-04-03 17:07:00    23.3      3.2   19.4        0.03
67   2023-04-03 17:12:00    23.1      2.7   19.8        0.01
68   2023-04-03 17:18:00    23.1      3.0   20.3        0.01
69   2023-04-03 17:23:00    23.2      2.1   20.1        0.01
70   2023-04-03 17:27:00    23.1      2.5   20.1        0.01
71   2023-04-03 17:31:00    23.2      2.0   20.2        0.01
72   2023-04-10 09:18:00    11.9      1.1   34.6        0.04
73   2023-04-10 09:19:00    12.0      1.4   34.8        0.03
74   2023-04-10 09:20:00    12.1      1.3   34.3        0.03
75   2023-04-10 09:22:00    12.2      0.2   34.7        0.03
76   2023-04-10 09:23:00    12.3      0.0   34.5        0.04
77   2023-04-10 09:24:00    12.5      0.3   34.7        0.04
78   2023-04-10 09:26:00    12.6      0.7   34.6        0.03
79   2023-04-10 09:27:00    12.6      1.4   34.2        0.03
80   2023-04-10 09:28:00    12.5      1.4   34.0        0.03
81   2023-04-10 09:30:00    12.4      0.9   35.1        0.04
82   2023-04-10 09:31:00    12.5      0.7   34.3        0.04
83   2023-04-10 09:32:00    12.5      0.4   34.0        0.04
84   2023-04-10 09:34:00    12.5      0.6   34.0        0.03
85   2023-04-10 09:35:00    12.6      0.5   34.3        0.04
86   2023-04-10 09:36:00    12.6      0.7   34.1        0.03
87   2023-04-10 09:38:00    12.7      0.3   34.6        0.05
88   2023-04-10 09:39:00    12.8      0.1   33.6        0.03
89   2023-04-10 09:40:00    12.9      1.1   33.7        0.04
90   2023-04-10 09:42:00    13.3      0.2   34.3        0.04
91   2023-04-10 09:43:00    13.7      0.3   33.6        0.04
92   2023-04-10 09:44:00    13.9      1.2   33.2        0.05
93   2023-04-10 09:46:00    13.6      0.6   32.1        0.04
94   2023-04-10 09:47:00    13.6      1.2   31.7        0.04
95   2023-04-10 09:48:00    13.6      1.1   32.0        0.03
96   2023-04-10 09:50:00    13.3      1.6   31.2        0.04
97   2023-04-10 09:51:00    13.3      1.6   31.4        0.05
98   2023-04-10 09:52:00    13.3      1.1   32.2        0.04
99   2023-04-10 09:54:00    13.7      2.4   31.7        0.04
100  2023-04-10 09:55:00    13.4      1.3   31.3        0.04
101  2023-04-10 09:56:00    13.2      1.0   32.3        0.04
102  2023-04-10 13:43:00    20.1      3.1   22.4        0.04
103  2023-04-10 13:44:00    20.1      5.1   21.7        0.07
104  2023-04-10 13:45:00    19.9      2.8   21.6        0.05
105  2023-04-10 13:47:00    19.7      3.1   21.9        0.04
106  2023-04-10 13:48:00    19.7      2.8   22.8        0.07
107  2023-04-10 13:49:00    19.8      2.3   22.6        0.05
108  2023-04-10 13:51:00    20.1      3.5   21.9        0.04
109  2023-04-10 13:52:00    20.1      2.4   22.6        0.06
110  2023-04-10 13:53:00    20.4      3.0   22.0        0.05
111  2023-04-10 13:55:00    20.2      3.0   21.7        0.06
112  2023-04-10 13:56:00    20.2      4.1   21.9        0.04
113  2023-04-10 13:57:00    20.1      3.9   21.2        0.05
114  2023-04-10 13:59:00    20.2      2.4   21.9        0.04
115  2023-04-10 14:00:00    20.4      2.1   22.2        0.06
116  2023-04-10 14:01:00    20.5      4.0   21.4        0.04
117  2023-04-10 14:03:00    20.3      3.0   22.0        0.06
118  2023-04-10 14:04:00    20.3      4.1   22.0        0.04
119  2023-04-10 14:05:00    20.2      3.1   22.4        0.06
120  2023-04-10 14:07:00    20.4      2.3   22.3        0.04
121  2023-04-10 14:08:00    20.7      1.8   23.6        0.06
122  2023-04-10 14:09:00    20.9      2.1   21.5        0.04
123  2023-04-10 14:11:00    20.7      1.4   21.1        0.05
124  2023-04-10 14:12:00    20.9      2.2   21.2        0.04
125  2023-04-10 14:13:00    20.8      1.2   21.1        0.06
126  2023-04-10 14:15:00    21.0      2.2   19.5        0.06
127  2023-04-10 14:16:00    20.8      2.9   19.5        0.03
128  2023-04-10 14:17:00    20.7      1.8   19.1        0.05
129  2023-04-10 14:19:00    20.7      2.6   19.6        0.04
130  2023-04-10 14:20:00    20.7      1.5   19.5        0.06
131  2023-04-10 14:21:00    20.9      3.5   20.2        0.04
132  2023-04-10 14:23:00    21.0      1.9   21.6        0.06
133  2023-04-10 14:24:00    21.0      2.2   20.1        0.03
134  2023-04-10 14:25:00    20.7      2.2   20.4        0.06
135  2023-04-10 14:27:00    20.4      5.0   21.0        0.06
136  2023-04-10 14:28:00    20.4      2.7   21.2        0.05
137  2023-04-10 14:29:00    20.3      2.0   21.3        0.03
138  2023-04-10 14:31:00    20.7      2.0   22.8        0.04
139  2023-04-10 14:32:00    20.9      3.1   22.5        0.06
140  2023-04-10 14:33:00    20.9      2.5   21.4        0.03
141  2023-04-10 16:48:00    21.2      2.6   22.4        0.02
142  2023-04-10 16:49:00    21.2      1.3   22.0        0.01
143  2023-04-10 16:50:00    21.2      2.5   22.0        0.02
144  2023-04-10 16:52:00    21.0      2.4   21.8        0.02
145  2023-04-10 16:53:00    20.9      2.3   21.9        0.02
146  2023-04-10 16:54:00    20.9      2.7   22.8        0.02
147  2023-04-10 16:57:00    20.9      1.3   23.0        0.01
148  2023-04-10 16:58:00    21.0      2.6   22.0        0.02
149  2023-04-10 16:59:00    21.0      3.0   21.5        0.03
150  2023-04-10 17:01:00    20.9      1.7   21.5        0.00
151  2023-04-10 17:02:00    20.8      2.7   21.8        0.02
152  2023-04-10 17:03:00    20.8      2.2   22.3        0.03
153  2023-04-10 17:05:00    20.8      2.8   23.1        0.02
154  2023-04-10 17:06:00    20.8      1.6   23.0        0.01
155  2023-04-10 17:07:00    20.8      3.0   22.9        0.01
156  2023-04-10 17:09:00    20.9      0.8   23.4        0.02
157  2023-04-10 17:10:00    21.0      0.9   23.6        0.01
158  2023-04-10 17:11:00    21.0      2.4   23.4        0.01
159  2023-04-10 17:13:00    21.0      3.6   23.2        0.02
160  2023-04-10 17:14:00    20.8      2.8   23.2        0.02
161  2023-04-10 17:15:00    20.7      3.1   23.1        0.01
162  2023-04-10 17:17:00    20.6      2.7   23.2        0.02
163  2023-04-10 17:18:00    20.6      2.9   23.6        0.02
164  2023-04-10 17:19:00    20.6      1.6   23.7        0.02
165  2023-04-10 17:21:00    20.7      1.3   23.2        0.01
166  2023-04-10 17:22:00    20.7      1.1   23.4        0.01
167  2023-04-10 17:23:00    20.7      1.4   23.2        0.01
168  2023-04-10 17:25:00    20.8      1.5   23.4        0.01
169  2023-04-10 17:26:00    20.8      2.0   23.4        0.02
170  2023-04-10 17:27:00    20.8      2.3   22.9        0.00
171  2023-04-10 17:29:00    20.6      3.3   23.7        0.01
172  2023-04-10 17:30:00    20.6      3.0   23.9        0.03
173  2023-04-10 17:31:00    20.5      2.4   24.3        0.01
174  2023-04-17 09:21:00    12.1      0.7   63.3        0.03
175  2023-04-17 09:22:00    12.1      1.5   62.8        0.04
176  2023-04-17 09:23:00    12.0      0.9   62.2        0.04
177  2023-04-17 09:25:00    12.1      0.7   62.6        0.04
178  2023-04-17 09:26:00    12.4      1.3   63.4        0.04
179  2023-04-17 09:27:00    12.7      1.2   62.3        0.04
180  2023-04-17 09:29:00    12.9      2.3   59.8        0.04
181  2023-04-17 09:30:00    13.0      1.4   59.5        0.03
182  2023-04-17 09:31:00    13.1      2.5   58.8        0.03
183  2023-04-17 09:33:00    12.5      1.7   56.9        0.04
184  2023-04-17 09:34:00    12.2      1.3   58.1        0.05
185  2023-04-17 09:35:00    12.2      1.7   60.3        0.04
186  2023-04-17 09:37:00    12.4      1.2   58.9        0.03
187  2023-04-17 09:38:00    12.3      0.9   58.8        0.04
188  2023-04-17 09:39:00    12.3      0.4   59.2        0.04
189  2023-04-17 09:41:00    12.5      0.8   59.9        0.04
190  2023-04-17 09:42:00    12.6      1.3   59.7        0.03
191  2023-04-17 09:43:00    12.6      1.2   58.8        0.04
192  2023-04-17 09:45:00    12.8      0.7   57.6        0.04
193  2023-04-17 09:46:00    12.7      1.3   58.1        0.04
194  2023-04-17 09:47:00    12.6      0.8   58.1        0.04
195  2023-04-17 09:49:00    12.8      1.4   58.5        0.04
196  2023-04-17 09:50:00    12.9      1.6   57.5        0.05
197  2023-04-17 09:51:00    13.0      1.7   57.5        0.04
198  2023-04-17 09:53:00    12.8      1.0   57.1        0.04
199  2023-04-17 09:54:00    13.1      0.8   58.2        0.04
200  2023-04-17 09:55:00    13.3      0.8   56.6        0.04
201  2023-04-17 09:57:00    13.3      0.4   53.8        0.04
202  2023-04-17 09:58:00    13.2      0.6   56.4        0.04
203  2023-04-17 09:59:00    13.3      0.7   57.1        0.04
204  2023-04-17 13:42:00    18.8      1.8   26.6        0.07
205  2023-04-17 13:43:00    18.8      2.8   26.9        0.05
206  2023-04-17 13:44:00    18.8      2.6   26.3        0.04
207  2023-04-17 13:46:00    18.7      2.2   27.6        0.04
208  2023-04-17 13:47:00    18.6      2.7   27.6        0.06
209  2023-04-17 13:48:00    18.7      2.0   27.8        0.06
210  2023-04-17 13:50:00    18.6      1.9   28.8        0.06
211  2023-04-17 13:51:00    18.5      2.4   28.5        0.05
212  2023-04-17 13:52:00    18.7      2.1   29.4        0.04
213  2023-04-17 13:58:00    18.6      0.5   28.2        0.05
214  2023-04-17 13:59:00    18.6      0.6   29.3        0.04
215  2023-04-17 14:00:00    18.7      1.0   28.2        0.06
216  2023-04-17 14:02:00    18.8      1.5   29.0        0.06
217  2023-04-17 14:03:00    18.9      1.4   29.2        0.03
218  2023-04-17 14:04:00    19.1      1.2   28.7        0.05
219  2023-04-17 14:06:00    18.9      1.6   27.2        0.04
220  2023-04-17 14:07:00    18.7      1.2   28.6        0.05
221  2023-04-17 14:08:00    18.6      1.8   29.2        0.04
222  2023-04-17 14:10:00    18.7      2.0   27.6        0.05
223  2023-04-17 14:11:00    18.8      0.7   27.8        0.04
224  2023-04-17 14:12:00    19.1      0.3   29.9        0.05
225  2023-04-17 14:14:00    19.2      1.4   27.5        0.06
226  2023-04-17 14:15:00    19.2      1.5   27.8        0.04
227  2023-04-17 14:16:00    19.2      1.3   27.5        0.05
228  2023-04-17 16:51:00    20.0      0.4   27.6        0.02
229  2023-04-17 16:52:00    20.1      0.5   26.9        0.01
230  2023-04-17 16:53:00    20.2      0.7   27.0        0.01
231  2023-04-17 16:56:00    20.5      1.8   26.6        0.01
232  2023-04-17 16:57:00    20.4      1.8   25.5        0.02
233  2023-04-17 16:58:00    20.3      1.3   25.4        0.03
234  2023-04-17 17:00:00    20.2      1.3   25.7        0.01
235  2023-04-17 17:01:00    20.2      1.1   25.9        0.01
236  2023-04-17 17:02:00    20.2      1.1   26.2        0.02
237  2023-04-17 17:04:00    20.1      0.6   25.9        0.02
238  2023-04-17 17:05:00    20.1      0.9   25.5        0.02
239  2023-04-17 17:06:00    20.0      0.4   25.4        0.01
240  2023-04-17 17:08:00    19.8      0.2   25.8        0.01
241  2023-04-17 17:09:00    19.9      0.3   25.6        0.03
242  2023-04-17 17:10:00    20.0      0.2   26.0        0.01
243  2023-04-17 17:12:00    20.2      0.9   26.8        0.01
244  2023-04-17 17:13:00    20.2      1.7   26.3        0.01
245  2023-04-17 17:14:00    20.2      2.1   26.4        0.01
246  2023-04-17 17:16:00    20.1      1.7   26.6        0.02
247  2023-04-17 17:17:00    20.1      0.9   27.4        0.02
248  2023-04-17 17:18:00    20.2      0.8   26.7        0.01
249  2023-04-17 17:20:00    20.3      1.4   27.5        0.01
250  2023-04-17 17:21:00    20.3      1.7   25.6        0.01
251  2023-04-17 17:22:00    20.2      0.7   25.9        0.01
252  2023-04-17 17:24:00    20.1      1.1   25.7        0.02
253  2023-04-17 17:26:00    20.1      0.9   25.9        0.00
254  2023-04-17 17:28:00    20.2      1.2   27.0        0.01
255  2023-04-17 17:29:00    20.2      1.6   26.5        0.02
256  2023-04-17 17:30:00    20.2      1.5   25.7        0.02
257  2023-04-17 17:33:00    20.2      1.5   26.6        0.01
258  2023-04-17 17:34:00    20.2      1.1   26.0        0.01
259  2023-04-17 17:35:00    20.2      1.2   26.1        0.01
260  2023-04-24 09:23:00    15.3      2.4   37.9        0.03
261  2023-04-24 09:24:00    15.4      3.5   38.4        0.03
262  2023-04-24 09:25:00    15.5      3.0   37.7        0.03
263  2023-04-24 09:27:00    15.5      2.2   38.3        0.04
264  2023-04-24 09:28:00    15.4      3.1   38.7        0.02
265  2023-04-24 09:29:00    15.5      1.9   38.5        0.03
266  2023-04-24 09:31:00    15.8      4.2   38.0        0.03
267  2023-04-24 09:32:00    15.7      3.2   37.6        0.02
268  2023-04-24 09:33:00    15.6      3.8   37.6        0.04
269  2023-04-24 09:35:00    15.7      3.6   37.2        0.05
270  2023-04-24 09:36:00    15.8      3.9   37.4        0.04
271  2023-04-24 09:37:00    15.8      2.5   37.2        0.03
272  2023-04-24 09:39:00    15.9      4.1   36.9        0.03
273  2023-04-24 09:40:00    16.0      3.2   36.5        0.04
274  2023-04-24 09:41:00    16.0      3.0   36.9        0.03
275  2023-04-24 09:43:00    16.1      4.2   37.1        0.05
276  2023-04-24 09:44:00    16.2      3.9   37.0        0.03
277  2023-04-24 09:45:00    16.1      2.8   36.9        0.03
278  2023-04-24 09:47:00    15.8      3.3   37.3        0.03
279  2023-04-24 09:48:00    16.0      2.7   36.9        0.03
280  2023-04-24 09:49:00    16.1      2.7   37.0        0.03
281  2023-04-24 09:51:00    16.2      0.5   37.5        0.03
282  2023-04-24 09:52:00    16.1      2.0   37.6        0.03
283  2023-04-24 09:53:00    16.1      3.6   37.5        0.04
284  2023-04-24 09:55:00    16.5      1.4   38.3        0.03
285  2023-04-24 09:56:00    16.6      2.1   37.2        0.03
286  2023-04-24 09:57:00    16.6      2.0   36.8        0.03
287  2023-04-24 09:59:00    16.8      2.0   36.6        0.03
288  2023-04-24 10:00:00    16.7      2.9   35.9        0.03
289  2023-04-24 10:01:00    16.5      4.2   36.2        0.03
290  2023-04-24 10:03:00    16.3      3.7   37.2        0.02
291  2023-04-24 10:04:00    16.4      3.9   37.0        0.04
292  2023-04-24 10:05:00    16.4      3.4   36.5        0.04
293  2023-04-24 10:07:00    16.4      3.8   37.2        0.04
294  2023-04-24 10:08:00    16.5      4.1   37.5        0.04
295  2023-04-24 10:09:00    16.3      3.3   35.2        0.03
296  2023-04-24 10:11:00    16.1      3.6   35.8        0.03
297  2023-04-24 10:12:00    16.2      5.0   35.2        0.03
298  2023-04-24 10:13:00    16.2      4.0   35.1        0.05
299  2023-04-24 10:15:00    16.5      3.4   35.2        0.03
300  2023-04-24 10:16:00    16.6      3.6   34.8        0.04
301  2023-04-24 10:17:00    16.5      4.1   34.5        0.04
302  2023-04-24 10:19:00    16.6      4.1   34.9        0.04
303  2023-04-24 10:20:00    16.5      2.6   34.8        0.04
304  2023-04-24 10:21:00    16.4      3.0   35.7        0.04
305  2023-04-24 10:23:00    16.6      3.1   36.3        0.05
306  2023-04-24 10:24:00    16.8      3.1   36.3        0.04
307  2023-04-24 10:25:00    16.6      3.4   35.6        0.04
308  2023-04-24 10:27:00    16.3      2.9   36.8        0.02
309  2023-04-24 10:28:00    16.6      3.4   36.3        0.04
310  2023-04-24 10:29:00    16.7      2.7   35.8        0.03
311  2023-04-24 10:31:00    17.0      4.9   35.6        0.02
312  2023-04-24 10:32:00    16.7      3.7   35.2        0.04
313  2023-04-24 10:33:00    16.4      1.2   35.4        0.04
314  2023-04-24 10:35:00    16.8      2.4   36.3        0.04
315  2023-04-24 10:36:00    17.1      1.8   36.3        0.05
316  2023-04-24 10:37:00    17.1      1.9   34.9        0.04
317  2023-04-24 10:39:00    16.9      1.9   34.5        0.04
318  2023-04-24 10:40:00    16.9      1.8   33.9        0.02
319  2023-04-24 10:41:00    16.9      1.4   35.1        0.04
320  2023-04-24 13:46:00    18.1      2.6   35.2        0.07
321  2023-04-24 13:47:00    18.5      2.8   34.9        0.07
322  2023-04-24 13:48:00    18.7      3.2   31.8        0.05
323  2023-04-24 13:51:00    19.6      2.0   31.0        0.08
324  2023-04-24 13:52:00    19.3      3.4   31.7        0.05
325  2023-04-24 13:54:00    19.3      3.4   30.3        0.05


### <div class="mark">new dataset folder 설정</div>

In [18]:
new = "./dataset/preprocessed_20230912/"

new_dataset_folders = {
    "soiling" : {
        "seg":f"{new}soiling/seg/",
        "origin" : f"{new}soiling/origin/"
    },
    "cloud" :{
        "seg" : f"{new}cloud/seg/",
        "origin" : f"{new}cloud/origin/",
        "classification" : f"{new}cloud/classification/"
    },
    "table" : f"{new}table/",
}

os.makedirs(new_dataset_folders["soiling"]["seg"], exist_ok=True)
os.makedirs(new_dataset_folders["soiling"]["origin"], exist_ok=True)
os.makedirs(new_dataset_folders["cloud"]["seg"], exist_ok=True)
os.makedirs(new_dataset_folders["cloud"]["origin"], exist_ok=True)
os.makedirs(new_dataset_folders["cloud"]["classification"], exist_ok=True)
os.makedirs(new_dataset_folders["table"], exist_ok=True)

In [19]:
import yaml

with open(os.path.join(new, 'config.yaml'), 'w') as f:
    yaml.safe_dump(
        {"old_dataset_folders" : dataset_folders,
        "new_dataset_folders" : new_dataset_folders
        }, f, default_flow_style=False)

### df 저장하기

In [20]:
df.to_csv(f'{new_dataset_folders["table"]}weather-addSoilingType_examine_1_upload_preprocessed.csv')

### df(table)를 기반으로 있는 파일만 카피하기

#### soiling

In [21]:
os.listdir(dataset_folders["soiling"]["seg"])[-1]

'panel3_NVR_ch2_jpg_20230524150800.png'

In [22]:
os.listdir(dataset_folders["soiling"]["seg"])[-1][19:-4]

'20230524150800'

In [23]:
import shutil

for f in os.listdir(dataset_folders["soiling"]["seg"]):
    panel=int(f[5]) 
    date = datetime.datetime.strptime(f[19:-4],'%Y%m%d%H%M%S' ) 
    
    if len(df.loc[(df["일시"]==date) & (df["panel number"]==panel)]) != 0 :
        shutil.copy2(dataset_folders["soiling"]["seg"]+f,new_dataset_folders["soiling"]["seg"]+f ) 
    else :
        print(f)

panel4_NVR_ch2_jpg_20230329172100.png
panel4_NVR_ch2_jpg_20230329172800.png
panel4_NVR_ch2_jpg_20230424143300.png
panel1_NVR_ch2_jpg_20230424143300.png
panel2_NVR_ch2_jpg_20230329172800.png
panel2_NVR_ch2_jpg_20230424143300.png

In [24]:
import pandas as pd 


class_names = [        
        'panel',
        'bird dropping',
        'pine pollen',
        'plastic bag',
        'sand',
        'shadow']

s_df = pd.DataFrame(columns=["일시", "panel number"]+class_names)
s_df

Empty DataFrame
Columns: [일시, panel number, panel, bird dropping, pine pollen, plastic bag, sand, shadow]
Index: []

In [25]:
from PIL import Image
from tqdm.notebook import tqdm
import numpy as np

cmap = [
    [0,0,0],
    [128,0,0],
    [0,128,0],
    [128,128,0],
    [0,0,128],
    [128,0,128]
]

for file_name in tqdm(os.listdir(new_dataset_folders["soiling"]["seg"])):

    img = Image.open(f'{new_dataset_folders["soiling"]["seg"]}{file_name}')
    
    panel_number = int(file_name[5])
    date = file_name[19:-4]
    
    
    img = np.array(img)
    
    height, width = len(img), len(img[0])
    total = height*width
    
    class_scores = [0 for _ in range(len(class_names))]
    
    for h in range(height):
        for w in range(width):
            class_num = cmap.index(list(img[h][w]))
            
            class_scores[class_num] += 1
            
            
    row = {"일시":date, "panel number":panel_number}
    for i, score in enumerate(class_scores):
        row[class_names[i]] = score/total*100
            
    s_df= s_df.append(row, ignore_index=True)
s_df['일시']=pd.to_datetime(s_df['일시'])
s_df

  0%|          | 0/2317 [00:00<?, ?it/s]

,일시,panel number,panel,bird dropping,pine pollen,plastic bag,sand,shadow
0,2023-03-22 16:44:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,2023-03-22 16:48:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,2023-03-22 16:52:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,2023-03-22 16:56:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,2023-03-22 17:02:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
5,2023-03-29 09:17:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
6,2023-03-29 09:21:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
7,2023-03-29 09:25:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
8,2023-03-29 09:29:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
9,2023-03-29 09:33:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
10,2023-03-29 09:37:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
11,2023-03-29 09:42:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
12,2023-03-29 14:14:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
13,2023-03-29 14:18:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
14,2023-03-29 14:22:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
15,2023-03-29 14:26:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
16,2023-03-29 14:30:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
17,2023-03-29 14:34:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
18,2023-03-29 14:38:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
19,2023-03-29 14:42:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
20,2023-03-29 14:46:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
21,2023-03-29 14:50:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
22,2023-03-29 14:54:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
23,2023-03-29 14:58:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
24,2023-03-29 15:07:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25,2023-03-29 16:41:00,4,58.621841,0.000000,0.000000,0.000000,0.000000,41.378159
26,2023-03-29 16:45:00,4,42.855554,0.000000,0.000000,0.000000,0.000000,57.144446
27,2023-03-29 16:49:00,4,69.464222,0.000000,0.000000,0.000000,0.000000,30.535778
28,2023-03-29 16:53:00,4,52.318441,0.000000,0.000000,0.000000,0.000000,47.681559
29,2023-03-29 16:57:00,4,45.972766,0.000000,0.000000,0.000000,0.000000,54.027234
30,2023-03-29 17:00:00,4,71.391064,0.000000,0.000000,0.000000,0.000000,28.608936
31,2023-03-29 17:05:00,4,67.421680,0.000000,0.000000,0.000000,0.000000,32.578320
32,2023-03-29 17:10:00,4,74.799751,0.000000,0.000000,0.000000,0.000000,25.200249
33,2023-03-29 17:15:00,4,76.363920,0.000000,0.000000,0.000000,0.000000,23.636080
34,2023-04-03 09:36:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
35,2023-04-03 09:40:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
36,2023-04-03 09:45:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
37,2023-04-03 09:49:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
38,2023-04-03 09:53:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
39,2023-04-03 09:57:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
40,2023-04-03 10:01:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
41,2023-04-03 10:06:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
42,2023-04-03 10:11:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
43,2023-04-03 10:15:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
44,2023-04-03 13:50:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
45,2023-04-03 13:54:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
46,2023-04-03 13:58:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
47,2023-04-03 14:02:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
48,2023-04-03 14:06:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
49,2023-04-03 14:10:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50,2023-04-03 14:14:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
51,2023-04-03 14:18:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
52,2023-04-03 14:22:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
53,2023-04-03 14:26:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
54,2023-04-03 14:44:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
55,2023-04-03 14:48:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
56,2023-04-03 14:52:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
57,2023-04-03 14:56:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
58,2023-04-03 15:00:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
59,2023-04-03 15:04:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
60,2023-04-03 15:08:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
61,2023-04-03 15:12:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
62,2023-04-03 15:16:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
63,2023-04-03 15:20:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
64,2023-04-03 16:47:00,4,34.400587,0.000000,0.000000,0.000000,0.000000,65.599413
65,2023-04-03 16:51:00,4,62.070577,0.000000,0.000000,0.000000,0.000000,37.929423
66,2023-04-03 16:55:00,4,25.271449,0.000000,0.000000,0.000000,0.000000,74.728551
67,2023-04-03 16:59:00,4,31.296725,0.000000,0.000000,0.000000,0.000000,68.703275
68,2023-04-03 17:03:00,4,52.563190,0.000000,0.000000,0.000000,0.000000,47.436810
69,2023-04-03 17:07:00,4,35.397383,0.000000,0.000000,0.000000,0.000000,64.602617
70,2023-04-03 17:12:00,4,17.722054,0.000000,0.000000,0.000000,0.000000,82.277946
71,2023-04-03 17:18:00,4,6.305625,0.000000,0.000000,0.000000,0.000000,93.694375
72,2023-04-03 17:23:00,4,8.072268,0.000000,0.000000,0.000000,0.000000,91.927732
73,2023-04-03 17:27:00,4,4.846031,0.000000,0.000000,0.000000,0.000000,95.153969
74,2023-04-03 17:31:00,4,19.455322,0.000000,0.000000,0.000000,0.000000,80.544678
75,2023-04-10 09:18:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
76,2023-04-10 09:19:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
77,2023-04-10 09:20:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
78,2023-04-10 09:22:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
79,2023-04-10 09:23:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
80,2023-04-10 09:24:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
81,2023-04-10 09:26:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
82,2023-04-10 09:27:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
83,2023-04-10 09:28:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
84,2023-04-10 09:30:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
85,2023-04-10 09:31:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
86,2023-04-10 09:32:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
87,2023-04-10 09:34:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
88,2023-04-10 09:35:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
89,2023-04-10 09:36:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
90,2023-04-10 09:38:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
91,2023-04-10 09:39:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
92,2023-04-10 09:40:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
93,2023-04-10 09:42:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
94,2023-04-10 09:43:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
95,2023-04-10 09:44:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
96,2023-04-10 09:46:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
97,2023-04-10 09:47:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
98,2023-04-10 09:48:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
99,2023-04-10 09:50:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
100,2023-04-10 09:51:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
101,2023-04-10 09:52:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
102,2023-04-10 09:54:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
103,2023-04-10 09:55:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
104,2023-04-10 09:56:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
105,2023-04-10 13:43:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
106,2023-04-10 13:44:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
107,2023-04-10 13:45:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
108,2023-04-10 13:47:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
109,2023-04-10 13:48:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
110,2023-04-10 13:49:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
111,2023-04-10 13:51:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
112,2023-04-10 13:52:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
113,2023-04-10 13:53:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
114,2023-04-10 13:55:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
115,2023-04-10 13:56:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
116,2023-04-10 13:57:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
117,2023-04-10 13:59:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
118,2023-04-10 14:00:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
119,2023-04-10 14:01:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
120,2023-04-10 14:03:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
121,2023-04-10 14:04:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
122,2023-04-10 14:05:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
123,2023-04-10 14:07:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
124,2023-04-10 14:08:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
125,2023-04-10 14:09:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
126,2023-04-10 14:11:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
127,2023-04-10 14:12:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
128,2023-04-10 14:13:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
129,2023-04-10 14:15:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
130,2023-04-10 14:16:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
131,2023-04-10 14:17:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
132,2023-04-10 14:19:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
133,2023-04-10 14:20:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
134,2023-04-10 14:21:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
135,2023-04-10 14:23:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
136,2023-04-10 14:24:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
137,2023-04-10 14:25:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
138,2023-04-10 14:27:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
139,2023-04-10 14:28:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
140,2023-04-10 14:29:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
141,2023-04-10 14:31:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
142,2023-04-10 14:32:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
143,2023-04-10 14:33:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
144,2023-04-10 16:48:00,4,60.537558,0.000000,0.000000,0.000000,0.000000,39.462442
145,2023-04-10 16:49:00,4,49.908775,0.000000,0.000000,0.000000,0.000000,50.091225
146,2023-04-10 16:50:00,4,40.755162,0.000000,0.000000,0.000000,0.000000,59.244838
147,2023-04-10 16:52:00,4,40.632787,0.000000,0.000000,0.000000,0.000000,59.367213
148,2023-04-10 16:53:00,4,46.262015,0.000000,0.000000,0.000000,0.000000,53.737985
149,2023-04-10 16:54:00,4,33.283642,0.000000,0.000000,0.000000,0.000000,66.716358
150,2023-04-10 16:57:00,4,20.191794,0.000000,0.000000,0.000000,0.000000,79.808206
151,2023-04-10 16:58:00,4,17.021182,0.000000,0.000000,0.000000,0.000000,82.978818
152,2023-04-10 16:59:00,4,15.245639,0.000000,0.000000,0.000000,0.000000,84.754361
153,2023-04-10 17:01:00,4,16.351460,0.000000,0.000000,0.000000,0.000000,83.648540
154,2023-04-10 17:02:00,4,11.994927,0.000000,0.000000,0.000000,0.000000,88.005073
155,2023-04-10 17:03:00,4,13.434496,0.000000,0.000000,0.000000,0.000000,86.565504
156,2023-04-10 17:05:00,4,11.954877,0.000000,0.000000,0.000000,0.000000,88.045123
157,2023-04-10 17:06:00,4,10.036935,0.000000,0.000000,0.000000,0.000000,89.963065
158,2023-04-10 17:07:00,4,5.653702,0.000000,0.000000,0.000000,0.000000,94.346298
159,2023-04-10 17:09:00,4,9.093539,0.000000,0.000000,0.000000,0.000000,90.906461
160,2023-04-10 17:10:00,4,6.928622,0.000000,0.000000,0.000000,0.000000,93.071378
161,2023-04-10 17:11:00,4,6.161000,0.000000,0.000000,0.000000,0.000000,93.839000
162,2023-04-10 17:13:00,4,6.712798,0.000000,0.000000,0.000000,0.000000,93.287202
163,2023-04-10 17:14:00,4,7.605020,0.000000,0.000000,0.000000,0.000000,92.394980
164,2023-04-10 17:15:00,4,5.506853,0.000000,0.000000,0.000000,0.000000,94.493147
165,2023-04-10 17:17:00,4,6.801798,0.000000,0.000000,0.000000,0.000000,93.198202
166,2023-04-10 17:18:00,4,6.928622,0.000000,0.000000,0.000000,0.000000,93.071378
167,2023-04-10 17:19:00,4,7.952118,0.000000,0.000000,0.000000,0.000000,92.047882
168,2023-04-10 17:21:00,4,5.335529,0.000000,0.000000,0.000000,0.000000,94.664471
169,2023-04-10 17:22:00,4,4.674706,0.000000,0.000000,0.000000,0.000000,95.325294
170,2023-04-10 17:23:00,4,3.261837,0.000000,0.000000,0.000000,0.000000,96.738163
171,2023-04-10 17:25:00,4,5.248754,0.000000,0.000000,0.000000,0.000000,94.751246
172,2023-04-10 17:26:00,4,3.689035,0.000000,0.000000,0.000000,0.000000,96.310965
173,2023-04-10 17:27:00,4,4.465557,0.000000,0.000000,0.000000,0.000000,95.534443
174,2023-04-10 17:29:00,4,3.940459,0.000000,0.000000,0.000000,0.000000,96.059541
175,2023-04-10 17:30:00,4,2.770114,0.000000,0.000000,0.000000,0.000000,97.229886
176,2023-04-10 17:31:00,4,1.920167,0.000000,0.000000,0.000000,0.000000,98.079833
177,2023-04-17 09:21:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
178,2023-04-17 09:22:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
179,2023-04-17 09:23:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
180,2023-04-17 09:25:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
181,2023-04-17 09:26:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
182,2023-04-17 09:27:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
183,2023-04-17 09:29:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
184,2023-04-17 09:30:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
185,2023-04-17 09:31:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
186,2023-04-17 09:33:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
187,2023-04-17 09:34:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
188,2023-04-17 09:35:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
189,2023-04-17 09:37:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
190,2023-04-17 09:38:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
191,2023-04-17 09:39:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
192,2023-04-17 09:41:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
193,2023-04-17 09:42:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
194,2023-04-17 09:43:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
195,2023-04-17 09:45:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
196,2023-04-17 09:46:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
197,2023-04-17 09:47:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
198,2023-04-17 09:49:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
199,2023-04-17 09:50:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
200,2023-04-17 09:51:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
201,2023-04-17 09:53:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
202,2023-04-17 09:54:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
203,2023-04-17 09:55:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
204,2023-04-17 09:57:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
205,2023-04-17 09:58:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
206,2023-04-17 09:59:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
207,2023-04-17 13:42:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
208,2023-04-17 13:43:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
209,2023-04-17 13:44:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
210,2023-04-17 13:46:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
211,2023-04-17 13:47:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
212,2023-04-17 13:48:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
213,2023-04-17 13:50:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
214,2023-04-17 13:51:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
215,2023-04-17 13:52:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
216,2023-04-17 13:58:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
217,2023-04-17 13:59:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
218,2023-04-17 14:00:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
219,2023-04-17 14:02:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
220,2023-04-17 14:03:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
221,2023-04-17 14:04:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
222,2023-04-17 14:06:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
223,2023-04-17 14:07:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
224,2023-04-17 14:08:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
225,2023-04-17 14:10:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
226,2023-04-17 14:11:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
227,2023-04-17 14:12:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
228,2023-04-17 14:14:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
229,2023-04-17 14:15:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
230,2023-04-17 14:16:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
231,2023-04-17 16:51:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
232,2023-04-17 16:52:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
233,2023-04-17 16:53:00,4,99.955500,0.000000,0.000000,0.000000,0.000000,0.044500
234,2023-04-17 16:56:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
235,2023-04-17 16:57:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
236,2023-04-17 16:58:00,4,99.853151,0.000000,0.000000,0.000000,0.000000,0.146849
237,2023-04-17 17:00:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
238,2023-04-17 17:01:00,4,97.710484,0.000000,0.000000,0.000000,0.000000,2.289516
239,2023-04-17 17:02:00,4,97.358936,0.000000,0.000000,0.000000,0.000000,2.641064
240,2023-04-17 17:04:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
241,2023-04-17 17:05:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
242,2023-04-17 17:06:00,4,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
243,2023-04-17 17:08:00,4,70.020470,0.000000,0.000000,0.000000,0.000000,29.979530

In [26]:
s_df = s_df.reset_index(drop =True)
s_df.to_csv(f'{new_dataset_folders["soiling"]["seg"]}segPercentScore.csv')

---

In [27]:
os.listdir(dataset_folders["soiling"]["origin"])[-1]

'panel4_NVR_ch2_jpg_20230329172800.jpg'

In [28]:
os.listdir(dataset_folders["soiling"]["origin"])[-1][19:-4]

'20230329172800'

In [29]:
for f in os.listdir(dataset_folders["soiling"]["origin"]):
    panel=int(f[5]) 
    date = datetime.datetime.strptime(f[19:-4],'%Y%m%d%H%M%S' ) 
    
    if len(df.loc[(df["일시"]==date) & (df["panel number"]==panel)]) != 0 :
        shutil.copy2(dataset_folders["soiling"]["origin"]+f,new_dataset_folders["soiling"]["origin"]+f ) 
    else :
        print(f)

panel1_NVR_ch2_jpg_20230329092100.jpg
panel1_NVR_ch2_jpg_20230329093300.jpg
panel1_NVR_ch2_jpg_20230329093700.jpg
panel1_NVR_ch2_jpg_20230329172100.jpg
panel1_NVR_ch2_jpg_20230329172800.jpg
panel1_NVR_ch2_jpg_20230424135000.jpg
panel1_NVR_ch2_jpg_20230424141900.jpg
panel1_NVR_ch2_jpg_20230424143300.jpg
panel2_NVR_ch2_jpg_20230329172100.jpg
panel2_NVR_ch2_jpg_20230329172800.jpg
panel2_NVR_ch2_jpg_20230403135000.jpg
panel2_NVR_ch2_jpg_20230403164700.jpg
panel2_NVR_ch2_jpg_20230403165100.jpg
panel2_NVR_ch2_jpg_20230403165500.jpg
panel2_NVR_ch2_jpg_20230403165900.jpg
panel2_NVR_ch2_jpg_20230403170300.jpg
panel2_NVR_ch2_jpg_20230403170700.jpg
panel2_NVR_ch2_jpg_20230403171200.jpg
panel2_NVR_ch2_jpg_20230403171800.jpg
panel2_NVR_ch2_jpg_20230403172300.jpg
panel2_NVR_ch2_jpg_20230403172700.jpg
panel2_NVR_ch2_jpg_20230403173100.jpg
panel2_NVR_ch2_jpg_20230417173300.jpg
panel2_NVR_ch2_jpg_20230417173400.jpg
panel2_NVR_ch2_jpg_20230417173500.jpg
panel3_NVR_ch2_jpg_20230322164400.jpg
panel3_NVR_ch2_jpg_20230322164800.jpg
panel3_NVR_ch2_jpg_20230322165200.jpg
panel3_NVR_ch2_jpg_20230322165600.jpg
panel3_NVR_ch2_jpg_20230322170200.jpg
panel3_NVR_ch2_jpg_20230329145800.jpg
panel3_NVR_ch2_jpg_20230329150700.jpg
panel3_NVR_ch2_jpg_20230329164100.jpg
panel3_NVR_ch2_jpg_20230329164500.jpg
panel3_NVR_ch2_jpg_20230329164900.jpg
panel3_NVR_ch2_jpg_20230329165300.jpg
panel3_NVR_ch2_jpg_20230329165700.jpg
panel3_NVR_ch2_jpg_20230329170000.jpg
panel3_NVR_ch2_jpg_20230329170500.jpg
panel3_NVR_ch2_jpg_20230329171000.jpg
panel3_NVR_ch2_jpg_20230329171500.jpg
panel3_NVR_ch2_jpg_20230329172100.jpg
panel3_NVR_ch2_jpg_20230329172800.jpg
panel2_NVR_ch2_jpg_20230424143300.jpg
panel3_NVR_ch2_jpg_20230403142600.jpg
panel3_NVR_ch2_jpg_20230417095800.jpg
panel3_NVR_ch2_jpg_20230417095900.jpg
panel3_NVR_ch2_jpg_20230403164700.jpg
panel3_NVR_ch2_jpg_20230403165100.jpg
panel3_NVR_ch2_jpg_20230403165500.jpg
panel3_NVR_ch2_jpg_20230403165900.jpg
panel3_NVR_ch2_jpg_20230403170300.jpg
panel3_NVR_ch2_jpg_20230403170700.jpg
panel3_NVR_ch2_jpg_20230410164800.jpg
panel3_NVR_ch2_jpg_20230410164900.jpg
panel3_NVR_ch2_jpg_20230410165000.jpg
panel3_NVR_ch2_jpg_20230410165200.jpg
panel3_NVR_ch2_jpg_20230410165300.jpg
panel3_NVR_ch2_jpg_20230410165400.jpg
panel3_NVR_ch2_jpg_20230410165700.jpg
panel3_NVR_ch2_jpg_20230410165800.jpg
panel3_NVR_ch2_jpg_20230410165900.jpg
panel3_NVR_ch2_jpg_20230410170100.jpg
panel3_NVR_ch2_jpg_20230410170200.jpg
panel3_NVR_ch2_jpg_20230410170300.jpg
panel3_NVR_ch2_jpg_20230410170500.jpg
panel3_NVR_ch2_jpg_20230410170600.jpg
panel3_NVR_ch2_jpg_20230410170700.jpg
panel3_NVR_ch2_jpg_20230410170900.jpg
panel3_NVR_ch2_jpg_20230410171000.jpg
panel3_NVR_ch2_jpg_20230410171100.jpg
panel3_NVR_ch2_jpg_20230410171300.jpg
panel3_NVR_ch2_jpg_20230410171400.jpg
panel3_NVR_ch2_jpg_20230410171500.jpg
panel3_NVR_ch2_jpg_20230410171700.jpg
panel3_NVR_ch2_jpg_20230410171800.jpg
panel3_NVR_ch2_jpg_20230410171900.jpg
panel3_NVR_ch2_jpg_20230410172100.jpg
panel3_NVR_ch2_jpg_20230410172200.jpg
panel3_NVR_ch2_jpg_20230410172300.jpg
panel3_NVR_ch2_jpg_20230410172500.jpg
panel3_NVR_ch2_jpg_20230410172600.jpg
panel3_NVR_ch2_jpg_20230410172700.jpg
panel3_NVR_ch2_jpg_20230410172900.jpg
panel3_NVR_ch2_jpg_20230410173000.jpg
panel3_NVR_ch2_jpg_20230410173100.jpg
panel3_NVR_ch2_jpg_20230417092100.jpg
panel3_NVR_ch2_jpg_20230417092200.jpg
panel3_NVR_ch2_jpg_20230417092300.jpg
panel3_NVR_ch2_jpg_20230417092500.jpg
panel3_NVR_ch2_jpg_20230417092600.jpg
panel3_NVR_ch2_jpg_20230417092700.jpg
panel3_NVR_ch2_jpg_20230417092900.jpg
panel3_NVR_ch2_jpg_20230417093000.jpg
panel3_NVR_ch2_jpg_20230417093100.jpg
panel3_NVR_ch2_jpg_20230417093300.jpg
panel3_NVR_ch2_jpg_20230417093400.jpg
panel3_NVR_ch2_jpg_20230417093500.jpg
panel3_NVR_ch2_jpg_20230417093700.jpg
panel3_NVR_ch2_jpg_20230417093800.jpg
panel3_NVR_ch2_jpg_20230417093900.jpg
panel3_NVR_ch2_jpg_20230417094100.jpg
panel3_NVR_ch2_jpg_20230417094200.jpg
panel3_NVR_ch2_jpg_20230417094300.jpg
panel3_NVR_ch2_jpg_20230417094500.jpg
panel3_NVR_ch2_jpg_20230417094600.jpg
panel3_NVR_ch2_jpg_20230417094700.jpg
panel3_NVR_ch2_jpg_20230417094900.jpg
panel3_NVR_ch2_jpg_20230417095000.jpg
panel3_NVR_ch2_jpg_20230417095100.jpg
panel3_NVR_ch2_jpg_20230417095300.jpg
panel3_NVR_ch2_jpg_20230417095400.jpg
panel3_NVR_ch2_jpg_20230417095500.jpg
panel3_NVR_ch2_jpg_20230417095700.jpg
panel3_NVR_ch2_jpg_20230403171200.jpg
panel3_NVR_ch2_jpg_20230403171800.jpg
panel3_NVR_ch2_jpg_20230424134700.jpg
panel3_NVR_ch2_jpg_20230424134800.jpg
panel3_NVR_ch2_jpg_20230424140300.jpg
panel3_NVR_ch2_jpg_20230424141400.jpg
panel3_NVR_ch2_jpg_20230424141500.jpg
panel3_NVR_ch2_jpg_20230424141600.jpg
panel3_NVR_ch2_jpg_20230424142100.jpg
panel3_NVR_ch2_jpg_20230424142500.jpg
panel3_NVR_ch2_jpg_20230424142700.jpg
panel3_NVR_ch2_jpg_20230424142800.jpg
panel3_NVR_ch2_jpg_20230424142900.jpg
panel3_NVR_ch2_jpg_20230424143100.jpg
panel3_NVR_ch2_jpg_20230424143200.jpg
panel3_NVR_ch2_jpg_20230424143300.jpg
panel3_NVR_ch2_jpg_20230424143400.jpg
panel3_NVR_ch2_jpg_20230424143500.jpg
panel3_NVR_ch2_jpg_20230424143600.jpg
panel3_NVR_ch2_jpg_20230424143800.jpg
panel3_NVR_ch2_jpg_20230424143900.jpg
panel3_NVR_ch2_jpg_20230424144000.jpg
panel3_NVR_ch2_jpg_20230424144200.jpg
panel3_NVR_ch2_jpg_20230424144300.jpg
panel3_NVR_ch2_jpg_20230424144400.jpg
panel3_NVR_ch2_jpg_20230424144600.jpg
panel3_NVR_ch2_jpg_20230424144700.jpg
panel3_NVR_ch2_jpg_20230424144800.jpg
panel3_NVR_ch2_jpg_20230424145000.jpg
panel3_NVR_ch2_jpg_20230424145100.jpg
panel3_NVR_ch2_jpg_20230424145200.jpg
panel3_NVR_ch2_jpg_20230424145400.jpg
panel3_NVR_ch2_jpg_20230424145500.jpg
panel3_NVR_ch2_jpg_20230424145600.jpg
panel3_NVR_ch2_jpg_20230424145800.jpg
panel3_NVR_ch2_jpg_20230424145900.jpg
panel3_NVR_ch2_jpg_20230424150000.jpg
panel3_NVR_ch2_jpg_20230424150200.jpg
panel3_NVR_ch2_jpg_20230424150300.jpg
panel3_NVR_ch2_jpg_20230424150400.jpg
panel3_NVR_ch2_jpg_20230501145300.jpg
panel4_NVR_ch2_jpg_20230424135000.jpg
panel4_NVR_ch2_jpg_20230424143300.jpg
panel4_NVR_ch2_jpg_20230329172100.jpg
panel4_NVR_ch2_jpg_20230329172800.jpg

#### cloud

In [30]:
os.listdir(dataset_folders["cloud"]["seg"])

['panel1_NVR_ch1_jpg_20230322164400.jpg_62.9308.jpg',
 'panel1_NVR_ch1_jpg_20230322164800.jpg_79.6429.jpg',
 'panel1_NVR_ch1_jpg_20230322165200.jpg_95.1866.jpg',
 'panel1_NVR_ch1_jpg_20230322165600.jpg_95.0747.jpg',
 'panel1_NVR_ch1_jpg_20230322170200.jpg_92.5118.jpg',
 'panel1_NVR_ch1_jpg_20230329091700.jpg_13.1237.jpg',
 'panel1_NVR_ch1_jpg_20230329092100.jpg_9.8265.jpg',
 'panel1_NVR_ch1_jpg_20230329092500.jpg_11.9565.jpg',
 'panel1_NVR_ch1_jpg_20230329092900.jpg_7.5293.jpg',
 'panel1_NVR_ch1_jpg_20230329093300.jpg_10.9067.jpg',
 'panel1_NVR_ch1_jpg_20230329093700.jpg_16.3292.jpg',
 'panel1_NVR_ch1_jpg_20230329094200.jpg_15.4985.jpg',
 'panel1_NVR_ch1_jpg_20230329141400.jpg_15.8567.jpg',
 'panel1_NVR_ch1_jpg_20230329141800.jpg_15.2128.jpg',
 'panel1_NVR_ch1_jpg_20230329142200.jpg_16.9754.jpg',
 'panel1_NVR_ch1_jpg_20230329142600.jpg_18.0986.jpg',
 'panel1_NVR_ch1_jpg_20230329143000.jpg_17.912.jpg',
 'panel1_NVR_ch1_jpg_20230329143400.jpg_19.4052.jpg',
 'panel1_NVR_ch1_jpg_20230329144200.jpg_25.9305.jpg',
 'panel1_NVR_ch1_jpg_20230329143800.jpg_22.9047.jpg',
 'panel1_NVR_ch1_jpg_20230329144600.jpg_26.1234.jpg',
 'panel1_NVR_ch1_jpg_20230329145000.jpg_27.7669.jpg',
 'panel1_NVR_ch1_jpg_20230329145400.jpg_31.1707.jpg',
 'panel1_NVR_ch1_jpg_20230329145800.jpg_32.8407.jpg',
 'panel1_NVR_ch1_jpg_20230329164100.jpg_63.0633.jpg',
 'panel1_NVR_ch1_jpg_20230329150700.jpg_36.3078.jpg',
 'panel1_NVR_ch1_jpg_20230329164500.jpg_64.1198.jpg',
 'panel1_NVR_ch1_jpg_20230329164900.jpg_63.565.jpg',
 'panel1_NVR_ch1_jpg_20230329165300.jpg_59.7311.jpg',
 'panel1_NVR_ch1_jpg_20230329165700.jpg_62.1587.jpg',
 'panel1_NVR_ch1_jpg_20230329170000.jpg_62.6085.jpg',
 'panel1_NVR_ch1_jpg_20230329170500.jpg_64.6931.jpg',
 'panel1_NVR_ch1_jpg_20230329171000.jpg_65.9391.jpg',
 'panel1_NVR_ch1_jpg_20230329171500.jpg_71.5487.jpg',
 'panel1_NVR_ch1_jpg_20230329172100.jpg_64.941.jpg',
 'panel1_NVR_ch1_jpg_20230329172800.jpg_68.6664.jpg',
 'panel1_NVR_ch1_jpg_20230403093600.jpg_6.7256.jpg',
 'panel1_NVR_ch1_jpg_20230403094000.jpg_7.0966.jpg',
 'panel1_NVR_ch1_jpg_20230403094500.jpg_10.183.jpg',
 'panel1_NVR_ch1_jpg_20230403094900.jpg_12.1827.jpg',
 'panel1_NVR_ch1_jpg_20230403095300.jpg_12.9871.jpg',
 'panel1_NVR_ch1_jpg_20230403095700.jpg_14.5271.jpg',
 'panel1_NVR_ch1_jpg_20230403100100.jpg_14.9042.jpg',
 'panel1_NVR_ch1_jpg_20230403100600.jpg_13.853.jpg',
 'panel1_NVR_ch1_jpg_20230403101100.jpg_16.4109.jpg',
 'panel1_NVR_ch1_jpg_20230403101500.jpg_18.0561.jpg',
 'panel1_NVR_ch1_jpg_20230403135000.jpg_13.2533.jpg',
 'panel1_NVR_ch1_jpg_20230403135400.jpg_12.4826.jpg',
 'panel1_NVR_ch1_jpg_20230403135800.jpg_13.1417.jpg',
 'panel1_NVR_ch1_jpg_20230403140200.jpg_12.9366.jpg',
 'panel1_NVR_ch1_jpg_20230403140600.jpg_13.2316.jpg',
 'panel1_NVR_ch1_jpg_20230403141000.jpg_12.7281.jpg',
 'panel1_NVR_ch1_jpg_20230403141400.jpg_13.2628.jpg',
 'panel1_NVR_ch1_jpg_20230403141800.jpg_13.8248.jpg',
 'panel1_NVR_ch1_jpg_20230403142200.jpg_13.3923.jpg',
 'panel1_NVR_ch1_jpg_20230403142600.jpg_13.5098.jpg',
 'panel1_NVR_ch1_jpg_20230403144400.jpg_14.8174.jpg',
 'panel1_NVR_ch1_jpg_20230403144800.jpg_15.4166.jpg',
 'panel1_NVR_ch1_jpg_20230403145200.jpg_16.0941.jpg',
 'panel1_NVR_ch1_jpg_20230403145600.jpg_16.9366.jpg',
 'panel1_NVR_ch1_jpg_20230403150000.jpg_15.6339.jpg',
 'panel1_NVR_ch1_jpg_20230403150400.jpg_17.4947.jpg',
 'panel1_NVR_ch1_jpg_20230403150800.jpg_17.524.jpg',
 'panel1_NVR_ch1_jpg_20230403151200.jpg_19.1539.jpg',
 'panel1_NVR_ch1_jpg_20230403151600.jpg_19.4884.jpg',
 'panel1_NVR_ch1_jpg_20230403152000.jpg_20.9103.jpg',
 'panel1_NVR_ch1_jpg_20230403164700.jpg_44.0804.jpg',
 'panel1_NVR_ch1_jpg_20230403165100.jpg_49.239.jpg',
 'panel1_NVR_ch1_jpg_20230403165500.jpg_46.0957.jpg',
 'panel1_NVR_ch1_jpg_20230403165900.jpg_48.5403.jpg',
 'panel1_NVR_ch1_jpg_20230403170300.jpg_46.7291.jpg',
 'panel1_NVR_ch1_jpg_20230403170700.jpg_47.8073.jpg',
 'panel1_NVR_ch1_jpg_20230403171200.jpg_49.8764.jpg',
 'panel1_NVR_ch1_jpg_20230403171800.jpg_48.373.jpg',
 'panel1_NVR_ch1_jpg_20230403172300.jpg_47.0004.jpg',
 'panel1_NVR_ch1_jpg_20230403172700.jpg_49.9934.jpg',
 'panel1_NVR_ch1_jpg_20230403173100.jpg_52.6461.jpg',
 'panel1_NVR_ch1_jpg_20230410091800.jpg_8.1231.jpg',
 'panel1_NVR_ch1_jpg_20230410091900.jpg_8.2784.jpg',
 'panel1_NVR_ch1_jpg_20230410092000.jpg_8.1374.jpg',
 'panel1_NVR_ch1_jpg_20230410092200.jpg_7.4097.jpg',
 'panel1_NVR_ch1_jpg_20230410092400.jpg_7.4444.jpg',
 'panel1_NVR_ch1_jpg_20230410092300.jpg_7.6157.jpg',
 'panel1_NVR_ch1_jpg_20230410092600.jpg_8.1724.jpg',
 'panel1_NVR_ch1_jpg_20230410092700.jpg_7.5927.jpg',
 'panel1_NVR_ch1_jpg_20230410092800.jpg_7.9183.jpg',
 'panel1_NVR_ch1_jpg_20230410093000.jpg_7.5393.jpg',
 'panel1_NVR_ch1_jpg_20230410093100.jpg_8.5377.jpg',
 'panel1_NVR_ch1_jpg_20230410093200.jpg_8.2182.jpg',
 'panel1_NVR_ch1_jpg_20230410093400.jpg_7.7694.jpg',
 'panel1_NVR_ch1_jpg_20230410093500.jpg_7.8162.jpg',
 'panel1_NVR_ch1_jpg_20230410093600.jpg_8.0434.jpg',
 'panel1_NVR_ch1_jpg_20230410093800.jpg_7.3134.jpg',
 'panel1_NVR_ch1_jpg_20230410093900.jpg_7.3069.jpg',
 'panel1_NVR_ch1_jpg_20230410094000.jpg_7.8532.jpg',
 'panel1_NVR_ch1_jpg_20230410094200.jpg_7.7232.jpg',
 'panel1_NVR_ch1_jpg_20230410094300.jpg_7.766.jpg',
 'panel1_NVR_ch1_jpg_20230410094400.jpg_7.5887.jpg',
 'panel1_NVR_ch1_jpg_20230410094600.jpg_7.349.jpg',
 'panel1_NVR_ch1_jpg_20230410094700.jpg_6.6552.jpg',
 'panel1_NVR_ch1_jpg_20230410094800.jpg_7.1866.jpg',
 'panel1_NVR_ch1_jpg_20230410095000.jpg_7.825.jpg',
 'panel1_NVR_ch1_jpg_20230410095100.jpg_7.6583.jpg',
 'panel1_NVR_ch1_jpg_20230410095200.jpg_8.0935.jpg',
 'panel1_NVR_ch1_jpg_20230410095400.jpg_7.4207.jpg',
 'panel1_NVR_ch1_jpg_20230410095500.jpg_7.6656.jpg',
 'panel1_NVR_ch1_jpg_20230410095600.jpg_7.7644.jpg',
 'panel1_NVR_ch1_jpg_20230410134300.jpg_12.1894.jpg',
 'panel1_NVR_ch1_jpg_20230410134400.jpg_13.1193.jpg',
 'panel1_NVR_ch1_jpg_20230410134500.jpg_12.3439.jpg',
 'panel1_NVR_ch1_jpg_20230410134700.jpg_13.8442.jpg',
 'panel1_NVR_ch1_jpg_20230410134800.jpg_11.2394.jpg',
 'panel1_NVR_ch1_jpg_20230410134900.jpg_13.3956.jpg',
 'panel1_NVR_ch1_jpg_20230410135100.jpg_13.6351.jpg',
 'panel1_NVR_ch1_jpg_20230410135200.jpg_13.3812.jpg',
 'panel1_NVR_ch1_jpg_20230410135300.jpg_13.6109.jpg',
 'panel1_NVR_ch1_jpg_20230410135500.jpg_11.8381.jpg',
 'panel1_NVR_ch1_jpg_20230410135600.jpg_13.4655.jpg',
 'panel1_NVR_ch1_jpg_20230410135700.jpg_13.6056.jpg',
 'panel1_NVR_ch1_jpg_20230410135900.jpg_14.4136.jpg',
 'panel1_NVR_ch1_jpg_20230410140000.jpg_14.7935.jpg',
 'panel1_NVR_ch1_jpg_20230410140100.jpg_13.7142.jpg',
 'panel1_NVR_ch1_jpg_20230410140300.jpg_13.9895.jpg',
 'panel1_NVR_ch1_jpg_20230410140400.jpg_14.0395.jpg',
 'panel1_NVR_ch1_jpg_20230410140500.jpg_14.1696.jpg',
 'panel1_NVR_ch1_jpg_20230410140700.jpg_14.1151.jpg',
 'panel1_NVR_ch1_jpg_20230410140800.jpg_13.8322.jpg',
 'panel1_NVR_ch1_jpg_20230410140900.jpg_14.1504.jpg',
 'panel1_NVR_ch1_jpg_20230410141100.jpg_16.1331.jpg',
 'panel1_NVR_ch1_jpg_20230410141200.jpg_15.5811.jpg',
 'panel1_NVR_ch1_jpg_20230410141300.jpg_15.3021.jpg',
 'panel1_NVR_ch1_jpg_20230410141500.jpg_16.0933.jpg',
 'panel1_NVR_ch1_jpg_20230410141600.jpg_15.5359.jpg',
 'panel1_NVR_ch1_jpg_20230410141700.jpg_14.6667.jpg',
 'panel1_NVR_ch1_jpg_20230410141900.jpg_15.878.jpg',
 'panel1_NVR_ch1_jpg_20230410142000.jpg_15.9691.jpg',
 'panel1_NVR_ch1_jpg_20230410142100.jpg_15.2622.jpg',
 'panel1_NVR_ch1_jpg_20230410142300.jpg_17.0233.jpg',
 'panel1_NVR_ch1_jpg_20230410142400.jpg_16.0953.jpg',
 'panel1_NVR_ch1_jpg_20230410142500.jpg_16.2804.jpg',
 'panel1_NVR_ch1_jpg_20230410142700.jpg_15.6152.jpg',
 'panel1_NVR_ch1_jpg_20230410142800.jpg_16.6563.jpg',
 'panel1_NVR_ch1_jpg_20230410142900.jpg_17.6972.jpg',
 'panel1_NVR_ch1_jpg_20230410143100.jpg_17.5333.jpg',
 'panel1_NVR_ch1_jpg_20230410143200.jpg_16.5305.jpg',
 'panel1_NVR_ch1_jpg_20230410143300.jpg_16.5547.jpg',
 'panel1_NVR_ch1_jpg_20230410164800.jpg_66.0985.jpg',
 'panel1_NVR_ch1_jpg_20230410164900.jpg_65.2806.jpg',
 'panel1_NVR_ch1_jpg_20230410165200.jpg_61.1499.jpg',
 'panel1_NVR_ch1_jpg_20230410165300.jpg_62.0152.jpg',
 'panel1_NVR_ch1_jpg_20230410165000.jpg_66.8438.jpg',
 'panel1_NVR_ch1_jpg_20230410165400.jpg_60.7198.jpg',
 'panel1_NVR_ch1_jpg_20230410165700.jpg_59.5171.jpg',
 'panel1_NVR_ch1_jpg_20230410165800.jpg_60.8602.jpg',
 'panel1_NVR_ch1_jpg_20230410165900.jpg_57.8863.jpg',
 'panel1_NVR_ch1_jpg_20230410170100.jpg_59.6687.jpg',
 'panel1_NVR_ch1_jpg_20230410170200.jpg_58.1669.jpg',
 'panel1_NVR_ch1_jpg_20230410170300.jpg_61.2532.jpg',
 'panel1_NVR_ch1_jpg_20230410170500.jpg_61.6162.jpg',
 'panel1_NVR_ch1_jpg_20230410170600.jpg_61.3325.jpg',
 'panel1_NVR_ch1_jpg_20230410170700.jpg_59.6771.jpg',
 'panel1_NVR_ch1_jpg_20230410170900.jpg_57.8106.jpg',
 'panel1_NVR_ch1_jpg_20230410171000.jpg_59.0541.jpg',
 'panel1_NVR_ch1_jpg_20230410171100.jpg_59.9658.jpg',
 'panel1_NVR_ch1_jpg_20230410171300.jpg_58.7302.jpg',
 'panel1_NVR_ch1_jpg_20230410171400.jpg_58.2057.jpg',
 'panel1_NVR_ch1_jpg_20230410171500.jpg_58.5421.jpg',
 'panel1_NVR_ch1_jpg_20230410171700.jpg_59.2849.jpg',
 'panel1_NVR_ch1_jpg_20230410171800.jpg_58.037.jpg',
 'panel1_NVR_ch1_jpg_20230410171900.jpg_58.7289.jpg',
 'panel1_NVR_ch1_jpg_20230410172100.jpg_56.3295.jpg',
 'panel1_NVR_ch1_jpg_20230410172200.jpg_54.9083.jpg',
 'panel1_NVR_ch1_jpg_20230410172300.jpg_56.3794.jpg',
 'panel1_NVR_ch1_jpg_20230410172500.jpg_54.4567.jpg',
 'panel1_NVR_ch1_jpg_20230410172600.jpg_54.2841.jpg',
 'panel1_NVR_ch1_jpg_20230410172700.jpg_56.0518.jpg',
 'panel1_NVR_ch1_jpg_20230410172900.jpg_54.913.jpg',
 'panel1_NVR_ch1_jpg_20230410173000.jpg_53.3409.jpg',
 'panel1_NVR_ch1_jpg_20230410173100.jpg_53.2992.jpg',
 'panel1_NVR_ch1_jpg_20230417092100.jpg_9.0926.jpg',
 'panel1_NVR_ch1_jpg_20230417092200.jpg_8.3592.jpg',
 'panel1_NVR_ch1_jpg_20230417092300.jpg_8.8287.jpg',
 'panel1_NVR_ch1_jpg_20230417092500.jpg_9.2157.jpg',
 'panel1_NVR_ch1_jpg_20230417092600.jpg_8.806.jpg',
 'panel1_NVR_ch1_jpg_20230417092700.jpg_8.3366.jpg',
 'panel1_NVR_ch1_jpg_20230417092900.jpg_9.2036.jpg',
 'panel1_NVR_ch1_jpg_20230417093000.jpg_9.0723.jpg',
 'panel1_NVR_ch1_jpg_20230417093100.jpg_8.8393.jpg',
 'panel1_NVR_ch1_jpg_20230417093300.jpg_9.6128.jpg',
 'panel1_NVR_ch1_jpg_20230417093400.jpg_9.7036.jpg',
 'panel1_NVR_ch1_jpg_20230417093500.jpg_9.8971.jpg',
 'panel1_NVR_ch1_jpg_20230417093700.jpg_8.7448.jpg',
 'panel1_NVR_ch1_jpg_20230417093800.jpg_8.8539.jpg',
 'panel1_NVR_ch1_jpg_20230417093900.jpg_8.4891.jpg',
 'panel1_NVR_ch1_jpg_20230417094100.jpg_8.4825.jpg',
 'panel1_NVR_ch1_jpg_20230417094200.jpg_8.5186.jpg',
 'panel1_NVR_ch1_jpg_20230417094300.jpg_8.6787.jpg',
 'panel1_NVR_ch1_jpg_20230417094500.jpg_9.5862.jpg',
 'panel1_NVR_ch1_jpg_20230417094600.jpg_8.9828.jpg',
 'panel1_NVR_ch1_jpg_20230417094700.jpg_8.7752.jpg',
 'panel1_NVR_ch1_jpg_20230417095000.jpg_8.8004.jpg',
 'panel1_NVR_ch1_jpg_20230417094900.jpg_9.0062.jpg',
 'panel1_NVR_ch1_jpg_20230417095100.jpg_8.8468.jpg',
 'panel1_NVR_ch1_jpg_20230417095300.jpg_8.8683.jpg',
 'panel1_NVR_ch1_jpg_20230417095400.jpg_8.7597.jpg',
 'panel1_NVR_ch1_jpg_20230417095500.jpg_9.1017.jpg',
 'panel1_NVR_ch1_jpg_20230417095700.jpg_9.1609.jpg',
 'panel1_NVR_ch1_jpg_20230417095800.jpg_9.2562.jpg',
 'panel1_NVR_ch1_jpg_20230417095900.jpg_8.6918.jpg',
 'panel1_NVR_ch1_jpg_20230417134200.jpg_22.5268.jpg',
 'panel1_NVR_ch1_jpg_20230417134300.jpg_20.0109.jpg',
 'panel1_NVR_ch1_jpg_20230417134400.jpg_20.0008.jpg',
 'panel1_NVR_ch1_jpg_20230417134600.jpg_23.6795.jpg',
 'panel1_NVR_ch1_jpg_20230417134700.jpg_24.9506.jpg',
 'panel1_NVR_ch1_jpg_20230417134800.jpg_24.4407.jpg',
 'panel1_NVR_ch1_jpg_20230417135000.jpg_22.5368.jpg',
 'panel1_NVR_ch1_jpg_20230417135100.jpg_31.1619.jpg',
 'panel1_NVR_ch1_jpg_20230417135200.jpg_27.3043.jpg',
 'panel1_NVR_ch1_jpg_20230417135400.jpg_24.2556.jpg',
 'panel1_NVR_ch1_jpg_20230417135500.jpg_25.5012.jpg',
 'panel1_NVR_ch1_jpg_20230417135600.jpg_24.9529.jpg',
 'panel1_NVR_ch1_jpg_20230417135800.jpg_25.2085.jpg',
 'panel1_NVR_ch1_jpg_20230417135900.jpg_26.1069.jpg',
 'panel1_NVR_ch1_jpg_20230417140000.jpg_22.1303.jpg',
 'panel1_NVR_ch1_jpg_20230417140200.jpg_36.2234.jpg',
 'panel1_NVR_ch1_jpg_20230417140300.jpg_39.2823.jpg',
 'panel1_NVR_ch1_jpg_20230417140400.jpg_37.414.jpg',
 'panel1_NVR_ch1_jpg_20230417140600.jpg_34.9235.jpg',
 'panel1_NVR_ch1_jpg_20230417140700.jpg_31.1632.jpg',
 'panel1_NVR_ch1_jpg_20230417140800.jpg_31.9808.jpg',
 'panel1_NVR_ch1_jpg_20230417141000.jpg_29.356.jpg',
 'panel1_NVR_ch1_jpg_20230417141100.jpg_27.3196.jpg',
 'panel1_NVR_ch1_jpg_20230417141200.jpg_23.8903.jpg',
 'panel1_NVR_ch1_jpg_20230417141400.jpg_23.7657.jpg',
 'panel1_NVR_ch1_jpg_20230417141500.jpg_25.912.jpg',
 'panel1_NVR_ch1_jpg_20230417141600.jpg_25.2844.jpg',
 'panel1_NVR_ch1_jpg_20230417165100.jpg_81.5266.jpg',
 'panel1_NVR_ch1_jpg_20230417165200.jpg_86.8824.jpg',
 'panel1_NVR_ch1_jpg_20230417165300.jpg_90.1712.jpg',
 'panel1_NVR_ch1_jpg_20230417165600.jpg_79.2045.jpg',
 'panel1_NVR_ch1_jpg_20230417165700.jpg_78.6094.jpg',
 'panel1_NVR_ch1_jpg_20230417165800.jpg_74.9839.jpg',
 'panel1_NVR_ch1_jpg_20230417170000.jpg_72.2004.jpg',
 'panel1_NVR_ch1_jpg_20230417170100.jpg_68.0613.jpg',
 'panel1_NVR_ch1_jpg_20230417170400.jpg_68.6841.jpg',
 'panel1_NVR_ch1_jpg_20230417170200.jpg_65.1523.jpg',
 'panel1_NVR_ch1_jpg_20230417170500.jpg_70.241.jpg',
 'panel1_NVR_ch1_jpg_20230417170600.jpg_65.1537.jpg',
 'panel1_NVR_ch1_jpg_20230417170800.jpg_71.9889.jpg',
 'panel1_NVR_ch1_jpg_20230417170900.jpg_71.9344.jpg',
 'panel1_NVR_ch1_jpg_20230417171000.jpg_74.4393.jpg',
 'panel1_NVR_ch1_jpg_20230417171200.jpg_77.5141.jpg',
 'panel1_NVR_ch1_jpg_20230417171300.jpg_78.9008.jpg',
 'panel1_NVR_ch1_jpg_20230417171400.jpg_76.5088.jpg',
 'panel1_NVR_ch1_jpg_20230417171600.jpg_74.9385.jpg',
 'panel1_NVR_ch1_jpg_20230417171700.jpg_77.6419.jpg',
 'panel1_NVR_ch1_jpg_20230417171800.jpg_83.4426.jpg',
 'panel1_NVR_ch1_jpg_20230417172000.jpg_90.7744.jpg',
 'panel1_NVR_ch1_jpg_20230417172100.jpg_86.2899.jpg',
 'panel1_NVR_ch1_jpg_20230417172200.jpg_81.1229.jpg',
 'panel1_NVR_ch1_jpg_20230417172500.jpg_77.8961.jpg',
 'panel1_NVR_ch1_jpg_20230417172400.jpg_75.5644.jpg',
 'panel1_NVR_ch1_jpg_20230417172600.jpg_81.3415.jpg',
 'panel1_NVR_ch1_jpg_20230417172800.jpg_75.8143.jpg',
 'panel1_NVR_ch1_jpg_20230417172900.jpg_76.3966.jpg',
 'panel1_NVR_ch1_jpg_20230417173000.jpg_77.3255.jpg',
 'panel1_NVR_ch1_jpg_20230417173300.jpg_74.94.jpg',
 'panel1_NVR_ch1_jpg_20230417173400.jpg_69.9332.jpg',
 'panel1_NVR_ch1_jpg_20230417173500.jpg_68.4712.jpg',
 'panel1_NVR_ch1_jpg_20230424092300.jpg_37.1395.jpg',
 'panel1_NVR_ch1_jpg_20230424092400.jpg_36.8818.jpg',
 'panel1_NVR_ch1_jpg_20230424092500.jpg_38.2845.jpg',
 'panel1_NVR_ch1_jpg_20230424092700.jpg_38.8144.jpg',
 'panel1_NVR_ch1_jpg_20230424092800.jpg_41.1574.jpg',
 'panel1_NVR_ch1_jpg_20230424092900.jpg_54.077.jpg',
 'panel1_NVR_ch1_jpg_20230424093100.jpg_55.086.jpg',
 'panel1_NVR_ch1_jpg_20230424093200.jpg_48.253.jpg',
 'panel1_NVR_ch1_jpg_20230424093300.jpg_45.7999.jpg',
 'panel1_NVR_ch1_jpg_20230424093500.jpg_47.9312.jpg',
 'panel1_NVR_ch1_jpg_20230424093600.jpg_47.1487.jpg',
 'panel1_NVR_ch1_jpg_20230424093700.jpg_43.6375.jpg',
 'panel1_NVR_ch1_jpg_20230424093900.jpg_43.2445.jpg',
 'panel1_NVR_ch1_jpg_20230424094000.jpg_53.7711.jpg',
 'panel1_NVR_ch1_jpg_20230424094100.jpg_41.8592.jpg',
 'panel1_NVR_ch1_jpg_20230424094300.jpg_37.0238.jpg',
 'panel1_NVR_ch1_jpg_20230424094400.jpg_38.6478.jpg',
 'panel1_NVR_ch1_jpg_20230424094700.jpg_42.3141.jpg',
 'panel1_NVR_ch1_jpg_20230424094800.jpg_36.7215.jpg',
 'panel1_NVR_ch1_jpg_20230424094500.jpg_44.8016.jpg',
 'panel1_NVR_ch1_jpg_20230424094900.jpg_38.1887.jpg',
 'panel1_NVR_ch1_jpg_20230424095100.jpg_32.1388.jpg',
 'panel1_NVR_ch1_jpg_20230424095200.jpg_41.202.jpg',
 'panel1_NVR_ch1_jpg_20230424095300.jpg_34.4742.jpg',
 'panel1_NVR_ch1_jpg_20230424095500.jpg_36.3229.jpg',
 'panel1_NVR_ch1_jpg_20230424095600.jpg_32.0405.jpg',
 'panel1_NVR_ch1_jpg_20230424095700.jpg_32.8403.jpg',
 'panel1_NVR_ch1_jpg_20230424095900.jpg_32.7529.jpg',
 'panel1_NVR_ch1_jpg_20230424100000.jpg_37.1085.jpg',
 'panel1_NVR_ch1_jpg_20230424100100.jpg_36.5541.jpg',
 'panel1_NVR_ch1_jpg_20230424100300.jpg_36.923.jpg',
 'panel1_NVR_ch1_jpg_20230424100400.jpg_31.9654.jpg',
 'panel1_NVR_ch1_jpg_20230424100500.jpg_33.6365.jpg',
 'panel1_NVR_ch1_jpg_20230424100700.jpg_33.9417.jpg',
 'panel1_NVR_ch1_jpg_20230424100800.jpg_32.8381.jpg',
 'panel1_NVR_ch1_jpg_20230424100900.jpg_35.0872.jpg',
 'panel1_NVR_ch1_jpg_20230424101100.jpg_48.2131.jpg',
 'panel1_NVR_ch1_jpg_20230424101200.jpg_44.0744.jpg',
 'panel1_NVR_ch1_jpg_20230424101500.jpg_51.0807.jpg',
 'panel1_NVR_ch1_jpg_20230424101300.jpg_49.9069.jpg',
 'panel1_NVR_ch1_jpg_20230424101600.jpg_59.2867.jpg',
 'panel1_NVR_ch1_jpg_20230424101700.jpg_38.9247.jpg',
 'panel1_NVR_ch1_jpg_20230424101900.jpg_32.4519.jpg',
 'panel1_NVR_ch1_jpg_20230424102000.jpg_32.4037.jpg',
 'panel1_NVR_ch1_jpg_20230424102100.jpg_35.5632.jpg',
 'panel1_NVR_ch1_jpg_20230424102300.jpg_37.2247.jpg',
 'panel1_NVR_ch1_jpg_20230424102400.jpg_41.9187.jpg',
 'panel1_NVR_ch1_jpg_20230424102500.jpg_38.6247.jpg',
 'panel1_NVR_ch1_jpg_20230424102700.jpg_43.5546.jpg',
 'panel1_NVR_ch1_jpg_20230424102800.jpg_47.1624.jpg',
 'panel1_NVR_ch1_jpg_20230424102900.jpg_51.3088.jpg',
 'panel1_NVR_ch1_jpg_20230424103100.jpg_62.3767.jpg',
 'panel1_NVR_ch1_jpg_20230424103200.jpg_66.8555.jpg',
 'panel1_NVR_ch1_jpg_20230424103300.jpg_66.2538.jpg',
 'panel1_NVR_ch1_jpg_20230424103500.jpg_69.5292.jpg',
 'panel1_NVR_ch1_jpg_20230424103600.jpg_52.6713.jpg',
 'panel1_NVR_ch1_jpg_20230424103700.jpg_54.5684.jpg',
 'panel1_NVR_ch1_jpg_20230424103900.jpg_60.7205.jpg',
 'panel1_NVR_ch1_jpg_20230424104000.jpg_64.6035.jpg',
 'panel1_NVR_ch1_jpg_20230424104100.jpg_59.4658.jpg',
 'panel1_NVR_ch1_jpg_20230424134600.jpg_77.0421.jpg',
 'panel1_NVR_ch1_jpg_20230424134700.jpg_86.3263.jpg',
 'panel1_NVR_ch1_jpg_20230424134800.jpg_86.8491.jpg',
 'panel1_NVR_ch1_jpg_20230424135000.jpg_81.8225.jpg',
 'panel1_NVR_ch1_jpg_20230424135100.jpg_87.6232.jpg',
 'panel1_NVR_ch1_jpg_20230424135200.jpg_75.3008.jpg',
 'panel1_NVR_ch1_jpg_20230424135400.jpg_78.6172.jpg',
 'panel1_NVR_ch1_jpg_20230424135500.jpg_82.9841.jpg',
 'panel1_NVR_ch1_jpg_20230424135600.jpg_81.0447.jpg',
 'panel1_NVR_ch1_jpg_20230424135800.jpg_83.5178.jpg',
 'panel1_NVR_ch1_jpg_20230424135900.jpg_81.5701.jpg',
 'panel1_NVR_ch1_jpg_20230424140000.jpg_75.0872.jpg',
 'panel1_NVR_ch1_jpg_20230424140200.jpg_67.9541.jpg',
 'panel1_NVR_ch1_jpg_20230424140300.jpg_77.908.jpg',
 'panel1_NVR_ch1_jpg_20230424140400.jpg_78.5081.jpg',
 'panel1_NVR_ch1_jpg_20230424140600.jpg_76.8141.jpg',
 'panel1_NVR_ch1_jpg_20230424140700.jpg_76.0181.jpg',
 'panel1_NVR_ch1_jpg_20230424140800.jpg_79.1914.jpg',
 'panel1_NVR_ch1_jpg_20230424141000.jpg_67.1664.jpg',
 'panel1_NVR_ch1_jpg_20230424141100.jpg_79.0692.jpg',
 'panel1_NVR_ch1_jpg_20230424141200.jpg_74.9305.jpg',
 'panel1_NVR_ch1_jpg_20230424141400.jpg_82.1364.jpg',
 'panel1_NVR_ch1_jpg_20230424141500.jpg_83.8385.jpg',
 'panel1_NVR_ch1_jpg_20230424141600.jpg_80.4499.jpg',
 'panel1_NVR_ch1_jpg_20230424141900.jpg_73.0594.jpg',
 'panel1_NVR_ch1_jpg_20230424142100.jpg_79.5462.jpg',
 'panel1_NVR_ch1_jpg_20230424142000.jpg_75.2496.jpg',
 'panel1_NVR_ch1_jpg_20230424142300.jpg_80.882.jpg',
 'panel1_NVR_ch1_jpg_20230424142400.jpg_82.5019.jpg',
 'panel1_NVR_ch1_jpg_20230424142500.jpg_87.6351.jpg',
 'panel1_NVR_ch1_jpg_20230424142700.jpg_90.6574.jpg',
 'panel1_NVR_ch1_jpg_20230424142800.jpg_92.2617.jpg',
 'panel1_NVR_ch1_jpg_20230424142900.jpg_94.3938.jpg',
 'panel1_NVR_ch1_jpg_20230424143100.jpg_95.7785.jpg',
 'panel1_NVR_ch1_jpg_20230424143200.jpg_95.4285.jpg',
 'panel1_NVR_ch1_jpg_20230424143300.jpg_96.0749.jpg',
 'panel1_NVR_ch1_jpg_20230424143400.jpg_95.211.jpg',
 'panel1_NVR_ch1_jpg_20230424143500.jpg_93.6436.jpg',
 'panel1_NVR_ch1_jpg_20230424143600.jpg_91.8752.jpg',
 'panel1_NVR_ch1_jpg_20230424143800.jpg_94.741.jpg',
 'panel1_NVR_ch1_jpg_20230424143900.jpg_97.3662.jpg',
 'panel1_NVR_ch1_jpg_20230424144000.jpg_98.8538.jpg',
 'panel1_NVR_ch1_jpg_20230424144200.jpg_97.9102.jpg',

In [31]:
os.listdir(dataset_folders["cloud"]["seg"])[-2][19:33]

'20230524150800'

In [32]:
os.listdir(dataset_folders["cloud"]["seg"])[-1][-3:]

'csv'

In [33]:
for f in os.listdir(dataset_folders["cloud"]["seg"]):
    if f[-3:] == "csv":
        continue 
        
    date = datetime.datetime.strptime(f[19:33],'%Y%m%d%H%M%S' ) 
     
    if len(df.loc[(df["일시"]==date)]) != 0 :
        shutil.copy2(dataset_folders["cloud"]["seg"]+f,new_dataset_folders["cloud"]["seg"]+f )  
    else : 
        print(f)

panel1_NVR_ch1_jpg_20230329172100.jpg_64.941.jpg
panel1_NVR_ch1_jpg_20230329172800.jpg_68.6664.jpg
panel1_NVR_ch1_jpg_20230417135400.jpg_24.2556.jpg
panel1_NVR_ch1_jpg_20230417135500.jpg_25.5012.jpg
panel1_NVR_ch1_jpg_20230417135600.jpg_24.9529.jpg
panel1_NVR_ch1_jpg_20230417172500.jpg_77.8961.jpg
panel1_NVR_ch1_jpg_20230424143300.jpg_96.0749.jpg

In [34]:
df_cloud = pd.read_csv(f'{dataset_folders["cloud"]["seg"]}segScore.csv')
df_cloud

     Unnamed: 0                                   name    score
0             0  panel1_NVR_ch1_jpg_20230322164400.jpg  62.9308
1             1  panel1_NVR_ch1_jpg_20230322164800.jpg  79.6429
2             2  panel1_NVR_ch1_jpg_20230322165200.jpg  95.1866
3             3  panel1_NVR_ch1_jpg_20230322165600.jpg  95.0747
4             4  panel1_NVR_ch1_jpg_20230322170200.jpg  92.5118
5             5  panel1_NVR_ch1_jpg_20230329091700.jpg  13.1237
6             6  panel1_NVR_ch1_jpg_20230329092100.jpg   9.8265
7             7  panel1_NVR_ch1_jpg_20230329092500.jpg  11.9565
8             8  panel1_NVR_ch1_jpg_20230329092900.jpg   7.5293
9             9  panel1_NVR_ch1_jpg_20230329093300.jpg  10.9067
10           10  panel1_NVR_ch1_jpg_20230329093700.jpg  16.3292
11           11  panel1_NVR_ch1_jpg_20230329094200.jpg  15.4985
12           12  panel1_NVR_ch1_jpg_20230329141400.jpg  15.8567
13           13  panel1_NVR_ch1_jpg_20230329141800.jpg  15.2128
14           14  panel1_NVR_ch1_jpg_20230329142200.jpg  16.9754
15           15  panel1_NVR_ch1_jpg_20230329142600.jpg  18.0986
16           16  panel1_NVR_ch1_jpg_20230329143000.jpg  17.9120
17           17  panel1_NVR_ch1_jpg_20230329143400.jpg  19.4052
18           18  panel1_NVR_ch1_jpg_20230329144200.jpg  25.9305
19           19  panel1_NVR_ch1_jpg_20230329143800.jpg  22.9047
20           20  panel1_NVR_ch1_jpg_20230329144600.jpg  26.1234
21           21  panel1_NVR_ch1_jpg_20230329145000.jpg  27.7669
22           22  panel1_NVR_ch1_jpg_20230329145400.jpg  31.1707
23           23  panel1_NVR_ch1_jpg_20230329145800.jpg  32.8407
24           24  panel1_NVR_ch1_jpg_20230329164100.jpg  63.0633
25           25  panel1_NVR_ch1_jpg_20230329150700.jpg  36.3078
26           26  panel1_NVR_ch1_jpg_20230329164500.jpg  64.1198
27           27  panel1_NVR_ch1_jpg_20230329164900.jpg  63.5650
28           28  panel1_NVR_ch1_jpg_20230329165300.jpg  59.7311
29           29  panel1_NVR_ch1_jpg_20230329165700.jpg  62.1587
30           30  panel1_NVR_ch1_jpg_20230329170000.jpg  62.6085
31           31  panel1_NVR_ch1_jpg_20230329170500.jpg  64.6931
32           32  panel1_NVR_ch1_jpg_20230329171000.jpg  65.9391
33           33  panel1_NVR_ch1_jpg_20230329171500.jpg  71.5487
34           34  panel1_NVR_ch1_jpg_20230329172100.jpg  64.9410
35           35  panel1_NVR_ch1_jpg_20230329172800.jpg  68.6664
36           36  panel1_NVR_ch1_jpg_20230403093600.jpg   6.7256
37           37  panel1_NVR_ch1_jpg_20230403094000.jpg   7.0966
38           38  panel1_NVR_ch1_jpg_20230403094500.jpg  10.1830
39           39  panel1_NVR_ch1_jpg_20230403094900.jpg  12.1827
40           40  panel1_NVR_ch1_jpg_20230403095300.jpg  12.9871
41           41  panel1_NVR_ch1_jpg_20230403095700.jpg  14.5271
42           42  panel1_NVR_ch1_jpg_20230403100100.jpg  14.9042
43           43  panel1_NVR_ch1_jpg_20230403100600.jpg  13.8530
44           44  panel1_NVR_ch1_jpg_20230403101100.jpg  16.4109
45           45  panel1_NVR_ch1_jpg_20230403101500.jpg  18.0561
46           46  panel1_NVR_ch1_jpg_20230403135000.jpg  13.2533
47           47  panel1_NVR_ch1_jpg_20230403135400.jpg  12.4826
48           48  panel1_NVR_ch1_jpg_20230403135800.jpg  13.1417
49           49  panel1_NVR_ch1_jpg_20230403140200.jpg  12.9366
50           50  panel1_NVR_ch1_jpg_20230403140600.jpg  13.2316
51           51  panel1_NVR_ch1_jpg_20230403141000.jpg  12.7281
52           52  panel1_NVR_ch1_jpg_20230403141400.jpg  13.2628
53           53  panel1_NVR_ch1_jpg_20230403141800.jpg  13.8248
54           54  panel1_NVR_ch1_jpg_20230403142200.jpg  13.3923
55           55  panel1_NVR_ch1_jpg_20230403142600.jpg  13.5098
56           56  panel1_NVR_ch1_jpg_20230403144400.jpg  14.8174
57           57  panel1_NVR_ch1_jpg_20230403144800.jpg  15.4166
58           58  panel1_NVR_ch1_jpg_20230403145200.jpg  16.0941
59           59  panel1_NVR_ch1_jpg_20230403145600.jpg  16.9366
60           60  panel1_NVR_ch1_jpg_20230403150000.jpg  15.6339
61           61  panel1_NVR_ch1_jpg_20230403150400.jpg  17.4947
62           62  panel1_NVR_ch1_jpg_20230403150800.jpg  17.5240
63           63  panel1_NVR_ch1_jpg_20230403151200.jpg  19.1539
64           64  panel1_NVR_ch1_jpg_20230403151600.jpg  19.4884
65           65  panel1_NVR_ch1_jpg_20230403152000.jpg  20.9103
66           66  panel1_NVR_ch1_jpg_20230403164700.jpg  44.0804
67           67  panel1_NVR_ch1_jpg_20230403165100.jpg  49.2390
68           68  panel1_NVR_ch1_jpg_20230403165500.jpg  46.0957
69           69  panel1_NVR_ch1_jpg_20230403165900.jpg  48.5403
70           70  panel1_NVR_ch1_jpg_20230403170300.jpg  46.7291
71           71  panel1_NVR_ch1_jpg_20230403170700.jpg  47.8073
72           72  panel1_NVR_ch1_jpg_20230403171200.jpg  49.8764
73           73  panel1_NVR_ch1_jpg_20230403171800.jpg  48.3730
74           74  panel1_NVR_ch1_jpg_20230403172300.jpg  47.0004
75           75  panel1_NVR_ch1_jpg_20230403172700.jpg  49.9934
76           76  panel1_NVR_ch1_jpg_20230403173100.jpg  52.6461
77           77  panel1_NVR_ch1_jpg_20230410091800.jpg   8.1231
78           78  panel1_NVR_ch1_jpg_20230410091900.jpg   8.2784
79           79  panel1_NVR_ch1_jpg_20230410092000.jpg   8.1374
80           80  panel1_NVR_ch1_jpg_20230410092200.jpg   7.4097
81           81  panel1_NVR_ch1_jpg_20230410092400.jpg   7.4444
82           82  panel1_NVR_ch1_jpg_20230410092300.jpg   7.6157
83           83  panel1_NVR_ch1_jpg_20230410092600.jpg   8.1724
84           84  panel1_NVR_ch1_jpg_20230410092700.jpg   7.5927
85           85  panel1_NVR_ch1_jpg_20230410092800.jpg   7.9183
86           86  panel1_NVR_ch1_jpg_20230410093000.jpg   7.5393
87           87  panel1_NVR_ch1_jpg_20230410093100.jpg   8.5377
88           88  panel1_NVR_ch1_jpg_20230410093200.jpg   8.2182
89           89  panel1_NVR_ch1_jpg_20230410093400.jpg   7.7694
90           90  panel1_NVR_ch1_jpg_20230410093500.jpg   7.8162
91           91  panel1_NVR_ch1_jpg_20230410093600.jpg   8.0434
92           92  panel1_NVR_ch1_jpg_20230410093800.jpg   7.3134
93           93  panel1_NVR_ch1_jpg_20230410093900.jpg   7.3069
94           94  panel1_NVR_ch1_jpg_20230410094000.jpg   7.8532
95           95  panel1_NVR_ch1_jpg_20230410094200.jpg   7.7232
96           96  panel1_NVR_ch1_jpg_20230410094300.jpg   7.7660
97           97  panel1_NVR_ch1_jpg_20230410094400.jpg   7.5887
98           98  panel1_NVR_ch1_jpg_20230410094600.jpg   7.3490
99           99  panel1_NVR_ch1_jpg_20230410094700.jpg   6.6552
100         100  panel1_NVR_ch1_jpg_20230410094800.jpg   7.1866
101         101  panel1_NVR_ch1_jpg_20230410095000.jpg   7.8250
102         102  panel1_NVR_ch1_jpg_20230410095100.jpg   7.6583
103         103  panel1_NVR_ch1_jpg_20230410095200.jpg   8.0935
104         104  panel1_NVR_ch1_jpg_20230410095400.jpg   7.4207
105         105  panel1_NVR_ch1_jpg_20230410095500.jpg   7.6656
106         106  panel1_NVR_ch1_jpg_20230410095600.jpg   7.7644
107         107  panel1_NVR_ch1_jpg_20230410134300.jpg  12.1894
108         108  panel1_NVR_ch1_jpg_20230410134400.jpg  13.1193
109         109  panel1_NVR_ch1_jpg_20230410134500.jpg  12.3439
110         110  panel1_NVR_ch1_jpg_20230410134700.jpg  13.8442
111         111  panel1_NVR_ch1_jpg_20230410134800.jpg  11.2394
112         112  panel1_NVR_ch1_jpg_20230410134900.jpg  13.3956
113         113  panel1_NVR_ch1_jpg_20230410135100.jpg  13.6351
114         114  panel1_NVR_ch1_jpg_20230410135200.jpg  13.3812
115         115  panel1_NVR_ch1_jpg_20230410135300.jpg  13.6109
116         116  panel1_NVR_ch1_jpg_20230410135500.jpg  11.8381
117         117  panel1_NVR_ch1_jpg_20230410135600.jpg  13.4655
118         118  panel1_NVR_ch1_jpg_20230410135700.jpg  13.6056
119         119  panel1_NVR_ch1_jpg_20230410135900.jpg  14.4136
120         120  panel1_NVR_ch1_jpg_20230410140000.jpg  14.7935
121         121  panel1_NVR_ch1_jpg_20230410140100.jpg  13.7142
122         122  panel1_NVR_ch1_jpg_20230410140300.jpg  13.9895
123         123  panel1_NVR_ch1_jpg_20230410140400.jpg  14.0395
124         124  panel1_NVR_ch1_jpg_20230410140500.jpg  14.1696
125         125  panel1_NVR_ch1_jpg_20230410140700.jpg  14.1151
126         126  panel1_NVR_ch1_jpg_20230410140800.jpg  13.8322
127         127  panel1_NVR_ch1_jpg_20230410140900.jpg  14.1504
128         128  panel1_NVR_ch1_jpg_20230410141100.jpg  16.1331
129         129  panel1_NVR_ch1_jpg_20230410141200.jpg  15.5811
130         130  panel1_NVR_ch1_jpg_20230410141300.jpg  15.3021
131         131  panel1_NVR_ch1_jpg_20230410141500.jpg  16.0933
132         132  panel1_NVR_ch1_jpg_20230410141600.jpg  15.5359
133         133  panel1_NVR_ch1_jpg_20230410141700.jpg  14.6667
134         134  panel1_NVR_ch1_jpg_20230410141900.jpg  15.8780
135         135  panel1_NVR_ch1_jpg_20230410142000.jpg  15.9691
136         136  panel1_NVR_ch1_jpg_20230410142100.jpg  15.2622
137         137  panel1_NVR_ch1_jpg_20230410142300.jpg  17.0233
138         138  panel1_NVR_ch1_jpg_20230410142400.jpg  16.0953
139         139  panel1_NVR_ch1_jpg_20230410142500.jpg  16.2804
140         140  panel1_NVR_ch1_jpg_20230410142700.jpg  15.6152
141         141  panel1_NVR_ch1_jpg_20230410142800.jpg  16.6563
142         142  panel1_NVR_ch1_jpg_20230410142900.jpg  17.6972
143         143  panel1_NVR_ch1_jpg_20230410143100.jpg  17.5333
144         144  panel1_NVR_ch1_jpg_20230410143200.jpg  16.5305
145         145  panel1_NVR_ch1_jpg_20230410143300.jpg  16.5547
146         146  panel1_NVR_ch1_jpg_20230410164800.jpg  66.0985
147         147  panel1_NVR_ch1_jpg_20230410164900.jpg  65.2806
148         148  panel1_NVR_ch1_jpg_20230410165200.jpg  61.1499
149         149  panel1_NVR_ch1_jpg_20230410165300.jpg  62.0152
150         150  panel1_NVR_ch1_jpg_20230410165000.jpg  66.8438
151         151  panel1_NVR_ch1_jpg_20230410165400.jpg  60.7198
152         152  panel1_NVR_ch1_jpg_20230410165700.jpg  59.5171
153         153  panel1_NVR_ch1_jpg_20230410165800.jpg  60.8602
154         154  panel1_NVR_ch1_jpg_20230410165900.jpg  57.8863
155         155  panel1_NVR_ch1_jpg_20230410170100.jpg  59.6687
156         156  panel1_NVR_ch1_jpg_20230410170200.jpg  58.1669
157         157  panel1_NVR_ch1_jpg_20230410170300.jpg  61.2532
158         158  panel1_NVR_ch1_jpg_20230410170500.jpg  61.6162
159         159  panel1_NVR_ch1_jpg_20230410170600.jpg  61.3325
160         160  panel1_NVR_ch1_jpg_20230410170700.jpg  59.6771
161         161  panel1_NVR_ch1_jpg_20230410170900.jpg  57.8106
162         162  panel1_NVR_ch1_jpg_20230410171000.jpg  59.0541
163         163  panel1_NVR_ch1_jpg_20230410171100.jpg  59.9658
164         164  panel1_NVR_ch1_jpg_20230410171300.jpg  58.7302
165         165  panel1_NVR_ch1_jpg_20230410171400.jpg  58.2057
166         166  panel1_NVR_ch1_jpg_20230410171500.jpg  58.5421
167         167  panel1_NVR_ch1_jpg_20230410171700.jpg  59.2849
168         168  panel1_NVR_ch1_jpg_20230410171800.jpg  58.0370
169         169  panel1_NVR_ch1_jpg_20230410171900.jpg  58.7289
170         170  panel1_NVR_ch1_jpg_20230410172100.jpg  56.3295
171         171  panel1_NVR_ch1_jpg_20230410172200.jpg  54.9083
172         172  panel1_NVR_ch1_jpg_20230410172300.jpg  56.3794
173         173  panel1_NVR_ch1_jpg_20230410172500.jpg  54.4567
174         174  panel1_NVR_ch1_jpg_20230410172600.jpg  54.2841
175         175  panel1_NVR_ch1_jpg_20230410172700.jpg  56.0518
176         176  panel1_NVR_ch1_jpg_20230410172900.jpg  54.9130
177         177  panel1_NVR_ch1_jpg_20230410173000.jpg  53.3409
178         178  panel1_NVR_ch1_jpg_20230410173100.jpg  53.2992
179         179  panel1_NVR_ch1_jpg_20230417092100.jpg   9.0926
180         180  panel1_NVR_ch1_jpg_20230417092200.jpg   8.3592
181         181  panel1_NVR_ch1_jpg_20230417092300.jpg   8.8287
182         182  panel1_NVR_ch1_jpg_20230417092500.jpg   9.2157
183         183  panel1_NVR_ch1_jpg_20230417092600.jpg   8.8060
184         184  panel1_NVR_ch1_jpg_20230417092700.jpg   8.3366
185         185  panel1_NVR_ch1_jpg_20230417092900.jpg   9.2036
186         186  panel1_NVR_ch1_jpg_20230417093000.jpg   9.0723
187         187  panel1_NVR_ch1_jpg_20230417093100.jpg   8.8393
188         188  panel1_NVR_ch1_jpg_20230417093300.jpg   9.6128
189         189  panel1_NVR_ch1_jpg_20230417093400.jpg   9.7036
190         190  panel1_NVR_ch1_jpg_20230417093500.jpg   9.8971
191         191  panel1_NVR_ch1_jpg_20230417093700.jpg   8.7448
192         192  panel1_NVR_ch1_jpg_20230417093800.jpg   8.8539
193         193  panel1_NVR_ch1_jpg_20230417093900.jpg   8.4891
194         194  panel1_NVR_ch1_jpg_20230417094100.jpg   8.4825
195         195  panel1_NVR_ch1_jpg_20230417094200.jpg   8.5186
196         196  panel1_NVR_ch1_jpg_20230417094300.jpg   8.6787
197         197  panel1_NVR_ch1_jpg_20230417094500.jpg   9.5862
198         198  panel1_NVR_ch1_jpg_20230417094600.jpg   8.9828
199         199  panel1_NVR_ch1_jpg_20230417094700.jpg   8.7752
200         200  panel1_NVR_ch1_jpg_20230417095000.jpg   8.8004
201         201  panel1_NVR_ch1_jpg_20230417094900.jpg   9.0062
202         202  panel1_NVR_ch1_jpg_20230417095100.jpg   8.8468
203         203  panel1_NVR_ch1_jpg_20230417095300.jpg   8.8683
204         204  panel1_NVR_ch1_jpg_20230417095400.jpg   8.7597
205         205  panel1_NVR_ch1_jpg_20230417095500.jpg   9.1017
206         206  panel1_NVR_ch1_jpg_20230417095700.jpg   9.1609
207         207  panel1_NVR_ch1_jpg_20230417095800.jpg   9.2562
208         208  panel1_NVR_ch1_jpg_20230417095900.jpg   8.6918
209         209  panel1_NVR_ch1_jpg_20230417134200.jpg  22.5268
210         210  panel1_NVR_ch1_jpg_20230417134300.jpg  20.0109
211         211  panel1_NVR_ch1_jpg_20230417134400.jpg  20.0008
212         212  panel1_NVR_ch1_jpg_20230417134600.jpg  23.6795
213         213  panel1_NVR_ch1_jpg_20230417134700.jpg  24.9506
214         214  panel1_NVR_ch1_jpg_20230417134800.jpg  24.4407
215         215  panel1_NVR_ch1_jpg_20230417135000.jpg  22.5368
216         216  panel1_NVR_ch1_jpg_20230417135100.jpg  31.1619
217         217  panel1_NVR_ch1_jpg_20230417135200.jpg  27.3043
218         218  panel1_NVR_ch1_jpg_20230417135400.jpg  24.2556
219         219  panel1_NVR_ch1_jpg_20230417135500.jpg  25.5012
220         220  panel1_NVR_ch1_jpg_20230417135600.jpg  24.9529
221         221  panel1_NVR_ch1_jpg_20230417135800.jpg  25.2085
222         222  panel1_NVR_ch1_jpg_20230417135900.jpg  26.1069
223         223  panel1_NVR_ch1_jpg_20230417140000.jpg  22.1303
224         224  panel1_NVR_ch1_jpg_20230417140200.jpg  36.2234
225         225  panel1_NVR_ch1_jpg_20230417140300.jpg  39.2823
226         226  panel1_NVR_ch1_jpg_20230417140400.jpg  37.4140
227         227  panel1_NVR_ch1_jpg_20230417140600.jpg  34.9235
228         228  panel1_NVR_ch1_jpg_20230417140700.jpg  31.1632
229         229  panel1_NVR_ch1_jpg_20230417140800.jpg  31.9808
230         230  panel1_NVR_ch1_jpg_20230417141000.jpg  29.3560
231         231  panel1_NVR_ch1_jpg_20230417141100.jpg  27.3196
232         232  panel1_NVR_ch1_jpg_20230417141200.jpg  23.8903
233         233  panel1_NVR_ch1_jpg_20230417141400.jpg  23.7657
234         234  panel1_NVR_ch1_jpg_20230417141500.jpg  25.9120
235         235  panel1_NVR_ch1_jpg_20230417141600.jpg  25.2844
236         236  panel1_NVR_ch1_jpg_20230417165100.jpg  81.5266
237         237  panel1_NVR_ch1_jpg_20230417165200.jpg  86.8824
238         238  panel1_NVR_ch1_jpg_20230417165300.jpg  90.1712
239         239  panel1_NVR_ch1_jpg_20230417165600.jpg  79.2045
240         240  panel1_NVR_ch1_jpg_20230417165700.jpg  78.6094
241         241  panel1_NVR_ch1_jpg_20230417165800.jpg  74.9839
242         242  panel1_NVR_ch1_jpg_20230417170000.jpg  72.2004
243         243  panel1_NVR_ch1_jpg_20230417170100.jpg  68.0613
244         244  panel1_NVR_ch1_jpg_20230417170400.jpg  68.6841
245         245  panel1_NVR_ch1_jpg_20230417170200.jpg  65.1523
246         246  panel1_NVR_ch1_jpg_20230417170500.jpg  70.2410
247         247  panel1_NVR_ch1_jpg_20230417170600.jpg  65.1537
248         248  panel1_NVR_ch1_jpg_20230417170800.jpg  71.9889
249         249  panel1_NVR_ch1_jpg_20230417170900.jpg  71.9344
250         250  panel1_NVR_ch1_jpg_20230417171000.jpg  74.4393
251         251  panel1_NVR_ch1_jpg_20230417171200.jpg  77.5141
252         252  panel1_NVR_ch1_jpg_20230417171300.jpg  78.9008
253         253  panel1_NVR_ch1_jpg_20230417171400.jpg  76.5088
254         254  panel1_NVR_ch1_jpg_20230417171600.jpg  74.9385
255         255  panel1_NVR_ch1_jpg_20230417171700.jpg  77.6419
256         256  panel1_NVR_ch1_jpg_20230417171800.jpg  83.4426
257         257  panel1_NVR_ch1_jpg_20230417172000.jpg  90.7744
258         258  panel1_NVR_ch1_jpg_20230417172100.jpg  86.2899
259         259  panel1_NVR_ch1_jpg_20230417172200.jpg  81.1229
260         260  panel1_NVR_ch1_jpg_20230417172500.jpg  77.8961
261         261  panel1_NVR_ch1_jpg_20230417172400.jpg  75.5644
262         262  panel1_NVR_ch1_jpg_20230417172600.jpg  81.3415
263         263  panel1_NVR_ch1_jpg_20230417172800.jpg  75.8143
264         264  panel1_NVR_ch1_jpg_20230417172900.jpg  76.3966
265         265  panel1_NVR_ch1_jpg_20230417173000.jpg  77.3255
266         266  panel1_NVR_ch1_jpg_20230417173300.jpg  74.9400
267         267  panel1_NVR_ch1_jpg_20230417173400.jpg  69.9332
268         268  panel1_NVR_ch1_jpg_20230417173500.jpg  68.4712
269         269  panel1_NVR_ch1_jpg_20230424092300.jpg  37.1395
270         270  panel1_NVR_ch1_jpg_20230424092400.jpg  36.8818
271         271  panel1_NVR_ch1_jpg_20230424092500.jpg  38.2845
272         272  panel1_NVR_ch1_jpg_20230424092700.jpg  38.8144
273         273  panel1_NVR_ch1_jpg_20230424092800.jpg  41.1574
274         274  panel1_NVR_ch1_jpg_20230424092900.jpg  54.0770
275         275  panel1_NVR_ch1_jpg_20230424093100.jpg  55.0860
276         276  panel1_NVR_ch1_jpg_20230424093200.jpg  48.2530
277         277  panel1_NVR_ch1_jpg_20230424093300.jpg  45.7999
278         278  panel1_NVR_ch1_jpg_20230424093500.jpg  47.9312
279         279  panel1_NVR_ch1_jpg_20230424093600.jpg  47.1487
280         280  panel1_NVR_ch1_jpg_20230424093700.jpg  43.6375
281         281  panel1_NVR_ch1_jpg_20230424093900.jpg  43.2445
282         282  panel1_NVR_ch1_jpg_20230424094000.jpg  53.7711
283         283  panel1_NVR_ch1_jpg_20230424094100.jpg  41.8592
284         284  panel1_NVR_ch1_jpg_20230424094300.jpg  37.0238
285         285  panel1_NVR_ch1_jpg_20230424094400.jpg  38.6478
286         286  panel1_NVR_ch1_jpg_20230424094700.jpg  42.3141
287         287  panel1_NVR_ch1_jpg_20230424094800.jpg  36.7215
288         288  panel1_NVR_ch1_jpg_20230424094500.jpg  44.8016
289         289  panel1_NVR_ch1_jpg_20230424094900.jpg  38.1887
290         290  panel1_NVR_ch1_jpg_20230424095100.jpg  32.1388
291         291  panel1_NVR_ch1_jpg_20230424095200.jpg  41.2020
292         292  panel1_NVR_ch1_jpg_20230424095300.jpg  34.4742
293         293  panel1_NVR_ch1_jpg_20230424095500.jpg  36.3229
294         294  panel1_NVR_ch1_jpg_20230424095600.jpg  32.0405
295         295  panel1_NVR_ch1_jpg_20230424095700.jpg  32.8403
296         296  panel1_NVR_ch1_jpg_20230424095900.jpg  32.7529
297         297  panel1_NVR_ch1_jpg_20230424100000.jpg  37.1085
298         298  panel1_NVR_ch1_jpg_20230424100100.jpg  36.5541
299         299  panel1_NVR_ch1_jpg_20230424100300.jpg  36.9230
300         300  panel1_NVR_ch1_jpg_20230424100400.jpg  31.9654
301         301  panel1_NVR_ch1_jpg_20230424100500.jpg  33.6365
302         302  panel1_NVR_ch1_jpg_20230424100700.jpg  33.9417
303         303  panel1_NVR_ch1_jpg_20230424100800.jpg  32.8381
304         304  panel1_NVR_ch1_jpg_20230424100900.jpg  35.0872
305         305  panel1_NVR_ch1_jpg_20230424101100.jpg  48.2131
306         306  panel1_NVR_ch1_jpg_20230424101200.jpg  44.0744
307         307  panel1_NVR_ch1_jpg_20230424101500.jpg  51.0807
308         308  panel1_NVR_ch1_jpg_20230424101300.jpg  49.9069
309         309  panel1_NVR_ch1_jpg_20230424101600.jpg  59.2867
310         310  panel1_NVR_ch1_jpg_20230424101700.jpg  38.9247

In [35]:
datetime.datetime.strptime(df_cloud.loc[0]["name"][19:33],'%Y%m%d%H%M%S' )

datetime.datetime(2023, 3, 22, 16, 44)

In [36]:
indexs = []

for i in df_cloud.index :
    date = datetime.datetime.strptime(df_cloud.loc[i]["name"][19:33],'%Y%m%d%H%M%S') 

    if len(df.loc[(df["일시"]==date)]) == 0 :
        print(i, panel, date)
        indexs.append(i)
        
df_cloud.drop(index=indexs, inplace=True)

34 4 2023-03-29 17:21:00
35 4 2023-03-29 17:28:00
218 4 2023-04-17 13:54:00
219 4 2023-04-17 13:55:00
220 4 2023-04-17 13:56:00
260 4 2023-04-17 17:25:00
364 4 2023-04-24 14:33:00

In [37]:
df_cloud = df_cloud.reset_index(drop =True)
df_cloud.to_csv(f'{new_dataset_folders["cloud"]["seg"]}segScore.csv')

---

In [38]:
os.listdir(dataset_folders["cloud"]["origin"])

['panel1_NVR_ch1_jpg_20230322164400.jpg',
 'panel1_NVR_ch1_jpg_20230322164800.jpg',
 'panel1_NVR_ch1_jpg_20230322165200.jpg',
 'panel1_NVR_ch1_jpg_20230322165600.jpg',
 'panel1_NVR_ch1_jpg_20230322170200.jpg',
 'panel1_NVR_ch1_jpg_20230329091700.jpg',
 'panel1_NVR_ch1_jpg_20230329092100.jpg',
 'panel1_NVR_ch1_jpg_20230329092500.jpg',
 'panel1_NVR_ch1_jpg_20230329092900.jpg',
 'panel1_NVR_ch1_jpg_20230329093300.jpg',
 'panel1_NVR_ch1_jpg_20230329093700.jpg',
 'panel1_NVR_ch1_jpg_20230329094200.jpg',
 'panel1_NVR_ch1_jpg_20230329141400.jpg',
 'panel1_NVR_ch1_jpg_20230329141800.jpg',
 'panel1_NVR_ch1_jpg_20230329142200.jpg',
 'panel1_NVR_ch1_jpg_20230329142600.jpg',
 'panel1_NVR_ch1_jpg_20230329143000.jpg',
 'panel1_NVR_ch1_jpg_20230329143400.jpg',
 'panel1_NVR_ch1_jpg_20230329144200.jpg',
 'panel1_NVR_ch1_jpg_20230329143800.jpg',
 'panel1_NVR_ch1_jpg_20230329144600.jpg',
 'panel1_NVR_ch1_jpg_20230329145000.jpg',
 'panel1_NVR_ch1_jpg_20230329145400.jpg',
 'panel1_NVR_ch1_jpg_20230329145800.jpg',
 'panel1_NVR_ch1_jpg_20230329164100.jpg',
 'panel1_NVR_ch1_jpg_20230329150700.jpg',
 'panel1_NVR_ch1_jpg_20230329164500.jpg',
 'panel1_NVR_ch1_jpg_20230329164900.jpg',
 'panel1_NVR_ch1_jpg_20230329165300.jpg',
 'panel1_NVR_ch1_jpg_20230329165700.jpg',
 'panel1_NVR_ch1_jpg_20230329170000.jpg',
 'panel1_NVR_ch1_jpg_20230329170500.jpg',
 'panel1_NVR_ch1_jpg_20230329171000.jpg',
 'panel1_NVR_ch1_jpg_20230329171500.jpg',
 'panel1_NVR_ch1_jpg_20230329172100.jpg',
 'panel1_NVR_ch1_jpg_20230329172800.jpg',
 'panel1_NVR_ch1_jpg_20230403093600.jpg',
 'panel1_NVR_ch1_jpg_20230403094000.jpg',
 'panel1_NVR_ch1_jpg_20230403094500.jpg',
 'panel1_NVR_ch1_jpg_20230403094900.jpg',
 'panel1_NVR_ch1_jpg_20230403095300.jpg',
 'panel1_NVR_ch1_jpg_20230403095700.jpg',
 'panel1_NVR_ch1_jpg_20230403100100.jpg',
 'panel1_NVR_ch1_jpg_20230403100600.jpg',
 'panel1_NVR_ch1_jpg_20230403101100.jpg',
 'panel1_NVR_ch1_jpg_20230403101500.jpg',
 'panel1_NVR_ch1_jpg_20230403135000.jpg',
 'panel1_NVR_ch1_jpg_20230403135400.jpg',
 'panel1_NVR_ch1_jpg_20230403135800.jpg',
 'panel1_NVR_ch1_jpg_20230403140200.jpg',
 'panel1_NVR_ch1_jpg_20230403140600.jpg',
 'panel1_NVR_ch1_jpg_20230403141000.jpg',
 'panel1_NVR_ch1_jpg_20230403141400.jpg',
 'panel1_NVR_ch1_jpg_20230403141800.jpg',
 'panel1_NVR_ch1_jpg_20230403142200.jpg',
 'panel1_NVR_ch1_jpg_20230403142600.jpg',
 'panel1_NVR_ch1_jpg_20230403144400.jpg',
 'panel1_NVR_ch1_jpg_20230403144800.jpg',
 'panel1_NVR_ch1_jpg_20230403145200.jpg',
 'panel1_NVR_ch1_jpg_20230403145600.jpg',
 'panel1_NVR_ch1_jpg_20230403150000.jpg',
 'panel1_NVR_ch1_jpg_20230403150400.jpg',
 'panel1_NVR_ch1_jpg_20230403150800.jpg',
 'panel1_NVR_ch1_jpg_20230403151200.jpg',
 'panel1_NVR_ch1_jpg_20230403151600.jpg',
 'panel1_NVR_ch1_jpg_20230403152000.jpg',
 'panel1_NVR_ch1_jpg_20230403164700.jpg',
 'panel1_NVR_ch1_jpg_20230403165100.jpg',
 'panel1_NVR_ch1_jpg_20230403165500.jpg',
 'panel1_NVR_ch1_jpg_20230403165900.jpg',
 'panel1_NVR_ch1_jpg_20230403170300.jpg',
 'panel1_NVR_ch1_jpg_20230403170700.jpg',
 'panel1_NVR_ch1_jpg_20230403171200.jpg',
 'panel1_NVR_ch1_jpg_20230403171800.jpg',
 'panel1_NVR_ch1_jpg_20230403172300.jpg',
 'panel1_NVR_ch1_jpg_20230403172700.jpg',
 'panel1_NVR_ch1_jpg_20230403173100.jpg',
 'panel1_NVR_ch1_jpg_20230410091800.jpg',
 'panel1_NVR_ch1_jpg_20230410091900.jpg',
 'panel1_NVR_ch1_jpg_20230410092000.jpg',
 'panel1_NVR_ch1_jpg_20230410092200.jpg',
 'panel1_NVR_ch1_jpg_20230410092400.jpg',
 'panel1_NVR_ch1_jpg_20230410092300.jpg',
 'panel1_NVR_ch1_jpg_20230410092600.jpg',
 'panel1_NVR_ch1_jpg_20230410092700.jpg',
 'panel1_NVR_ch1_jpg_20230410092800.jpg',
 'panel1_NVR_ch1_jpg_20230410093000.jpg',
 'panel1_NVR_ch1_jpg_20230410093100.jpg',
 'panel1_NVR_ch1_jpg_20230410093200.jpg',
 'panel1_NVR_ch1_jpg_20230410093400.jpg',
 'panel1_NVR_ch1_jpg_20230410093500.jpg',
 'panel1_NVR_ch1_jpg_20230410093600.jpg',
 'panel1_NVR_ch1_jpg_20230410093800.jpg',
 'panel1_NVR_ch1_jpg_20230410093900.jpg',
 'panel1_NVR_ch1_jpg_20230410094000.jpg',
 'panel1_NVR_ch1_jpg_20230410094200.jpg',
 'panel1_NVR_ch1_jpg_20230410094300.jpg',
 'panel1_NVR_ch1_jpg_20230410094400.jpg',
 'panel1_NVR_ch1_jpg_20230410094600.jpg',
 'panel1_NVR_ch1_jpg_20230410094700.jpg',
 'panel1_NVR_ch1_jpg_20230410094800.jpg',
 'panel1_NVR_ch1_jpg_20230410095000.jpg',
 'panel1_NVR_ch1_jpg_20230410095100.jpg',
 'panel1_NVR_ch1_jpg_20230410095200.jpg',
 'panel1_NVR_ch1_jpg_20230410095400.jpg',
 'panel1_NVR_ch1_jpg_20230410095500.jpg',
 'panel1_NVR_ch1_jpg_20230410095600.jpg',
 'panel1_NVR_ch1_jpg_20230410134300.jpg',
 'panel1_NVR_ch1_jpg_20230410134400.jpg',
 'panel1_NVR_ch1_jpg_20230410134500.jpg',
 'panel1_NVR_ch1_jpg_20230410134700.jpg',
 'panel1_NVR_ch1_jpg_20230410134800.jpg',
 'panel1_NVR_ch1_jpg_20230410134900.jpg',
 'panel1_NVR_ch1_jpg_20230410135100.jpg',
 'panel1_NVR_ch1_jpg_20230410135200.jpg',
 'panel1_NVR_ch1_jpg_20230410135300.jpg',
 'panel1_NVR_ch1_jpg_20230410135500.jpg',
 'panel1_NVR_ch1_jpg_20230410135600.jpg',
 'panel1_NVR_ch1_jpg_20230410135700.jpg',
 'panel1_NVR_ch1_jpg_20230410135900.jpg',
 'panel1_NVR_ch1_jpg_20230410140000.jpg',
 'panel1_NVR_ch1_jpg_20230410140100.jpg',
 'panel1_NVR_ch1_jpg_20230410140300.jpg',
 'panel1_NVR_ch1_jpg_20230410140400.jpg',
 'panel1_NVR_ch1_jpg_20230410140500.jpg',
 'panel1_NVR_ch1_jpg_20230410140700.jpg',
 'panel1_NVR_ch1_jpg_20230410140800.jpg',
 'panel1_NVR_ch1_jpg_20230410140900.jpg',
 'panel1_NVR_ch1_jpg_20230410141100.jpg',
 'panel1_NVR_ch1_jpg_20230410141200.jpg',
 'panel1_NVR_ch1_jpg_20230410141300.jpg',
 'panel1_NVR_ch1_jpg_20230410141500.jpg',
 'panel1_NVR_ch1_jpg_20230410141600.jpg',
 'panel1_NVR_ch1_jpg_20230410141700.jpg',
 'panel1_NVR_ch1_jpg_20230410141900.jpg',
 'panel1_NVR_ch1_jpg_20230410142000.jpg',
 'panel1_NVR_ch1_jpg_20230410142100.jpg',
 'panel1_NVR_ch1_jpg_20230410142300.jpg',
 'panel1_NVR_ch1_jpg_20230410142400.jpg',
 'panel1_NVR_ch1_jpg_20230410142500.jpg',
 'panel1_NVR_ch1_jpg_20230410142700.jpg',
 'panel1_NVR_ch1_jpg_20230410142800.jpg',
 'panel1_NVR_ch1_jpg_20230410142900.jpg',
 'panel1_NVR_ch1_jpg_20230410143100.jpg',
 'panel1_NVR_ch1_jpg_20230410143200.jpg',
 'panel1_NVR_ch1_jpg_20230410143300.jpg',
 'panel1_NVR_ch1_jpg_20230410164800.jpg',
 'panel1_NVR_ch1_jpg_20230410164900.jpg',
 'panel1_NVR_ch1_jpg_20230410165200.jpg',
 'panel1_NVR_ch1_jpg_20230410165300.jpg',
 'panel1_NVR_ch1_jpg_20230410165000.jpg',
 'panel1_NVR_ch1_jpg_20230410165400.jpg',
 'panel1_NVR_ch1_jpg_20230410165700.jpg',
 'panel1_NVR_ch1_jpg_20230410165800.jpg',
 'panel1_NVR_ch1_jpg_20230410165900.jpg',
 'panel1_NVR_ch1_jpg_20230410170100.jpg',
 'panel1_NVR_ch1_jpg_20230410170200.jpg',
 'panel1_NVR_ch1_jpg_20230410170300.jpg',
 'panel1_NVR_ch1_jpg_20230410170500.jpg',
 'panel1_NVR_ch1_jpg_20230410170600.jpg',
 'panel1_NVR_ch1_jpg_20230410170700.jpg',
 'panel1_NVR_ch1_jpg_20230410170900.jpg',
 'panel1_NVR_ch1_jpg_20230410171000.jpg',
 'panel1_NVR_ch1_jpg_20230410171100.jpg',
 'panel1_NVR_ch1_jpg_20230410171300.jpg',
 'panel1_NVR_ch1_jpg_20230410171400.jpg',
 'panel1_NVR_ch1_jpg_20230410171500.jpg',
 'panel1_NVR_ch1_jpg_20230410171700.jpg',
 'panel1_NVR_ch1_jpg_20230410171800.jpg',
 'panel1_NVR_ch1_jpg_20230410171900.jpg',
 'panel1_NVR_ch1_jpg_20230410172100.jpg',
 'panel1_NVR_ch1_jpg_20230410172200.jpg',
 'panel1_NVR_ch1_jpg_20230410172300.jpg',
 'panel1_NVR_ch1_jpg_20230410172500.jpg',
 'panel1_NVR_ch1_jpg_20230410172600.jpg',
 'panel1_NVR_ch1_jpg_20230410172700.jpg',
 'panel1_NVR_ch1_jpg_20230410172900.jpg',
 'panel1_NVR_ch1_jpg_20230410173000.jpg',
 'panel1_NVR_ch1_jpg_20230410173100.jpg',
 'panel1_NVR_ch1_jpg_20230417092100.jpg',
 'panel1_NVR_ch1_jpg_20230417092200.jpg',
 'panel1_NVR_ch1_jpg_20230417092300.jpg',
 'panel1_NVR_ch1_jpg_20230417092500.jpg',
 'panel1_NVR_ch1_jpg_20230417092600.jpg',
 'panel1_NVR_ch1_jpg_20230417092700.jpg',
 'panel1_NVR_ch1_jpg_20230417092900.jpg',
 'panel1_NVR_ch1_jpg_20230417093000.jpg',
 'panel1_NVR_ch1_jpg_20230417093100.jpg',
 'panel1_NVR_ch1_jpg_20230417093300.jpg',
 'panel1_NVR_ch1_jpg_20230417093400.jpg',
 'panel1_NVR_ch1_jpg_20230417093500.jpg',
 'panel1_NVR_ch1_jpg_20230417093700.jpg',
 'panel1_NVR_ch1_jpg_20230417093800.jpg',
 'panel1_NVR_ch1_jpg_20230417093900.jpg',
 'panel1_NVR_ch1_jpg_20230417094100.jpg',
 'panel1_NVR_ch1_jpg_20230417094200.jpg',
 'panel1_NVR_ch1_jpg_20230417094300.jpg',
 'panel1_NVR_ch1_jpg_20230417094500.jpg',
 'panel1_NVR_ch1_jpg_20230417094600.jpg',
 'panel1_NVR_ch1_jpg_20230417094700.jpg',
 'panel1_NVR_ch1_jpg_20230417095000.jpg',
 'panel1_NVR_ch1_jpg_20230417094900.jpg',
 'panel1_NVR_ch1_jpg_20230417095100.jpg',
 'panel1_NVR_ch1_jpg_20230417095300.jpg',
 'panel1_NVR_ch1_jpg_20230417095400.jpg',
 'panel1_NVR_ch1_jpg_20230417095500.jpg',
 'panel1_NVR_ch1_jpg_20230417095700.jpg',
 'panel1_NVR_ch1_jpg_20230417095800.jpg',
 'panel1_NVR_ch1_jpg_20230417095900.jpg',
 'panel1_NVR_ch1_jpg_20230417134200.jpg',
 'panel1_NVR_ch1_jpg_20230417134300.jpg',
 'panel1_NVR_ch1_jpg_20230417134400.jpg',
 'panel1_NVR_ch1_jpg_20230417134600.jpg',
 'panel1_NVR_ch1_jpg_20230417134700.jpg',
 'panel1_NVR_ch1_jpg_20230417134800.jpg',
 'panel1_NVR_ch1_jpg_20230417135000.jpg',
 'panel1_NVR_ch1_jpg_20230417135100.jpg',
 'panel1_NVR_ch1_jpg_20230417135200.jpg',
 'panel1_NVR_ch1_jpg_20230417135400.jpg',
 'panel1_NVR_ch1_jpg_20230417135500.jpg',
 'panel1_NVR_ch1_jpg_20230417135600.jpg',
 'panel1_NVR_ch1_jpg_20230417135800.jpg',
 'panel1_NVR_ch1_jpg_20230417135900.jpg',
 'panel1_NVR_ch1_jpg_20230417140000.jpg',
 'panel1_NVR_ch1_jpg_20230417140200.jpg',
 'panel1_NVR_ch1_jpg_20230417140300.jpg',
 'panel1_NVR_ch1_jpg_20230417140400.jpg',
 'panel1_NVR_ch1_jpg_20230417140600.jpg',
 'panel1_NVR_ch1_jpg_20230417140700.jpg',
 'panel1_NVR_ch1_jpg_20230417140800.jpg',
 'panel1_NVR_ch1_jpg_20230417141000.jpg',
 'panel1_NVR_ch1_jpg_20230417141100.jpg',
 'panel1_NVR_ch1_jpg_20230417141200.jpg',
 'panel1_NVR_ch1_jpg_20230417141400.jpg',
 'panel1_NVR_ch1_jpg_20230417141500.jpg',
 'panel1_NVR_ch1_jpg_20230417141600.jpg',
 'panel1_NVR_ch1_jpg_20230417165100.jpg',
 'panel1_NVR_ch1_jpg_20230417165200.jpg',
 'panel1_NVR_ch1_jpg_20230417165300.jpg',
 'panel1_NVR_ch1_jpg_20230417165600.jpg',
 'panel1_NVR_ch1_jpg_20230417165700.jpg',
 'panel1_NVR_ch1_jpg_20230417165800.jpg',
 'panel1_NVR_ch1_jpg_20230417170000.jpg',
 'panel1_NVR_ch1_jpg_20230417170100.jpg',
 'panel1_NVR_ch1_jpg_20230417170400.jpg',
 'panel1_NVR_ch1_jpg_20230417170200.jpg',
 'panel1_NVR_ch1_jpg_20230417170500.jpg',
 'panel1_NVR_ch1_jpg_20230417170600.jpg',
 'panel1_NVR_ch1_jpg_20230417170800.jpg',
 'panel1_NVR_ch1_jpg_20230417170900.jpg',
 'panel1_NVR_ch1_jpg_20230417171000.jpg',
 'panel1_NVR_ch1_jpg_20230417171200.jpg',
 'panel1_NVR_ch1_jpg_20230417171300.jpg',
 'panel1_NVR_ch1_jpg_20230417171400.jpg',
 'panel1_NVR_ch1_jpg_20230417171600.jpg',
 'panel1_NVR_ch1_jpg_20230417171700.jpg',
 'panel1_NVR_ch1_jpg_20230417171800.jpg',
 'panel1_NVR_ch1_jpg_20230417172000.jpg',
 'panel1_NVR_ch1_jpg_20230417172100.jpg',
 'panel1_NVR_ch1_jpg_20230417172200.jpg',
 'panel1_NVR_ch1_jpg_20230417172500.jpg',
 'panel1_NVR_ch1_jpg_20230417172400.jpg',
 'panel1_NVR_ch1_jpg_20230417172600.jpg',
 'panel1_NVR_ch1_jpg_20230417172800.jpg',
 'panel1_NVR_ch1_jpg_20230417172900.jpg',
 'panel1_NVR_ch1_jpg_20230417173000.jpg',
 'panel1_NVR_ch1_jpg_20230417173300.jpg',
 'panel1_NVR_ch1_jpg_20230417173400.jpg',
 'panel1_NVR_ch1_jpg_20230417173500.jpg',
 'panel1_NVR_ch1_jpg_20230424092300.jpg',
 'panel1_NVR_ch1_jpg_20230424092400.jpg',
 'panel1_NVR_ch1_jpg_20230424092500.jpg',
 'panel1_NVR_ch1_jpg_20230424092700.jpg',
 'panel1_NVR_ch1_jpg_20230424092800.jpg',
 'panel1_NVR_ch1_jpg_20230424092900.jpg',
 'panel1_NVR_ch1_jpg_20230424093100.jpg',
 'panel1_NVR_ch1_jpg_20230424093200.jpg',
 'panel1_NVR_ch1_jpg_20230424093300.jpg',
 'panel1_NVR_ch1_jpg_20230424093500.jpg',
 'panel1_NVR_ch1_jpg_20230424093600.jpg',
 'panel1_NVR_ch1_jpg_20230424093700.jpg',
 'panel1_NVR_ch1_jpg_20230424093900.jpg',
 'panel1_NVR_ch1_jpg_20230424094000.jpg',
 'panel1_NVR_ch1_jpg_20230424094100.jpg',
 'panel1_NVR_ch1_jpg_20230424094300.jpg',
 'panel1_NVR_ch1_jpg_20230424094400.jpg',
 'panel1_NVR_ch1_jpg_20230424094700.jpg',
 'panel1_NVR_ch1_jpg_20230424094800.jpg',
 'panel1_NVR_ch1_jpg_20230424094500.jpg',
 'panel1_NVR_ch1_jpg_20230424094900.jpg',
 'panel1_NVR_ch1_jpg_20230424095100.jpg',
 'panel1_NVR_ch1_jpg_20230424095200.jpg',
 'panel1_NVR_ch1_jpg_20230424095300.jpg',
 'panel1_NVR_ch1_jpg_20230424095500.jpg',
 'panel1_NVR_ch1_jpg_20230424095600.jpg',
 'panel1_NVR_ch1_jpg_20230424095700.jpg',
 'panel1_NVR_ch1_jpg_20230424095900.jpg',
 'panel1_NVR_ch1_jpg_20230424100000.jpg',
 'panel1_NVR_ch1_jpg_20230424100100.jpg',
 'panel1_NVR_ch1_jpg_20230424100300.jpg',
 'panel1_NVR_ch1_jpg_20230424100400.jpg',
 'panel1_NVR_ch1_jpg_20230424100500.jpg',
 'panel1_NVR_ch1_jpg_20230424100700.jpg',
 'panel1_NVR_ch1_jpg_20230424100800.jpg',
 'panel1_NVR_ch1_jpg_20230424100900.jpg',
 'panel1_NVR_ch1_jpg_20230424101100.jpg',
 'panel1_NVR_ch1_jpg_20230424101200.jpg',
 'panel1_NVR_ch1_jpg_20230424101500.jpg',
 'panel1_NVR_ch1_jpg_20230424101300.jpg',
 'panel1_NVR_ch1_jpg_20230424101600.jpg',
 'panel1_NVR_ch1_jpg_20230424101700.jpg',
 'panel1_NVR_ch1_jpg_20230424101900.jpg',
 'panel1_NVR_ch1_jpg_20230424102000.jpg',
 'panel1_NVR_ch1_jpg_20230424102100.jpg',
 'panel1_NVR_ch1_jpg_20230424102300.jpg',
 'panel1_NVR_ch1_jpg_20230424102400.jpg',
 'panel1_NVR_ch1_jpg_20230424102500.jpg',
 'panel1_NVR_ch1_jpg_20230424102700.jpg',
 'panel1_NVR_ch1_jpg_20230424102800.jpg',
 'panel1_NVR_ch1_jpg_20230424102900.jpg',
 'panel1_NVR_ch1_jpg_20230424103100.jpg',
 'panel1_NVR_ch1_jpg_20230424103200.jpg',
 'panel1_NVR_ch1_jpg_20230424103300.jpg',
 'panel1_NVR_ch1_jpg_20230424103500.jpg',
 'panel1_NVR_ch1_jpg_20230424103600.jpg',
 'panel1_NVR_ch1_jpg_20230424103700.jpg',
 'panel1_NVR_ch1_jpg_20230424103900.jpg',
 'panel1_NVR_ch1_jpg_20230424104000.jpg',
 'panel1_NVR_ch1_jpg_20230424104100.jpg',
 'panel1_NVR_ch1_jpg_20230424134600.jpg',
 'panel1_NVR_ch1_jpg_20230424134700.jpg',
 'panel1_NVR_ch1_jpg_20230424134800.jpg',
 'panel1_NVR_ch1_jpg_20230424135000.jpg',
 'panel1_NVR_ch1_jpg_20230424135100.jpg',
 'panel1_NVR_ch1_jpg_20230424135200.jpg',
 'panel1_NVR_ch1_jpg_20230424135400.jpg',
 'panel1_NVR_ch1_jpg_20230424135500.jpg',
 'panel1_NVR_ch1_jpg_20230424135600.jpg',
 'panel1_NVR_ch1_jpg_20230424135800.jpg',
 'panel1_NVR_ch1_jpg_20230424135900.jpg',
 'panel1_NVR_ch1_jpg_20230424140000.jpg',
 'panel1_NVR_ch1_jpg_20230424140200.jpg',
 'panel1_NVR_ch1_jpg_20230424140300.jpg',
 'panel1_NVR_ch1_jpg_20230424140400.jpg',
 'panel1_NVR_ch1_jpg_20230424140600.jpg',
 'panel1_NVR_ch1_jpg_20230424140700.jpg',
 'panel1_NVR_ch1_jpg_20230424140800.jpg',
 'panel1_NVR_ch1_jpg_20230424141000.jpg',
 'panel1_NVR_ch1_jpg_20230424141100.jpg',
 'panel1_NVR_ch1_jpg_20230424141200.jpg',
 'panel1_NVR_ch1_jpg_20230424141400.jpg',
 'panel1_NVR_ch1_jpg_20230424141500.jpg',
 'panel1_NVR_ch1_jpg_20230424141600.jpg',
 'panel1_NVR_ch1_jpg_20230424141900.jpg',
 'panel1_NVR_ch1_jpg_20230424142100.jpg',
 'panel1_NVR_ch1_jpg_20230424142000.jpg',
 'panel1_NVR_ch1_jpg_20230424142300.jpg',
 'panel1_NVR_ch1_jpg_20230424142400.jpg',
 'panel1_NVR_ch1_jpg_20230424142500.jpg',
 'panel1_NVR_ch1_jpg_20230424142700.jpg',
 'panel1_NVR_ch1_jpg_20230424142800.jpg',
 'panel1_NVR_ch1_jpg_20230424142900.jpg',
 'panel1_NVR_ch1_jpg_20230424143100.jpg',
 'panel1_NVR_ch1_jpg_20230424143200.jpg',
 'panel1_NVR_ch1_jpg_20230424143300.jpg',
 'panel1_NVR_ch1_jpg_20230424143400.jpg',
 'panel1_NVR_ch1_jpg_20230424143500.jpg',
 'panel1_NVR_ch1_jpg_20230424143600.jpg',
 'panel1_NVR_ch1_jpg_20230424143800.jpg',
 'panel1_NVR_ch1_jpg_20230424143900.jpg',
 'panel1_NVR_ch1_jpg_20230424144000.jpg',
 'panel1_NVR_ch1_jpg_20230424144200.jpg',
 'panel1_NVR_ch1_jpg_20230424144300.jpg',
 'panel1_NVR_ch1_jpg_20230424144400.jpg',
 'panel1_NVR_ch1_jpg_20230424144600.jpg',
 'panel1_NVR_ch1_jpg_20230424144700.jpg',
 'panel1_NVR_ch1_jpg_20230424144800.jpg',
 'panel1_NVR_ch1_jpg_20230424145000.jpg',
 'panel1_NVR_ch1_jpg_20230424145100.jpg',
 'panel1_NVR_ch1_jpg_20230424145200.jpg',
 'panel1_NVR_ch1_jpg_20230424145400.jpg',
 'panel1_NVR_ch1_jpg_20230424145500.jpg',
 'panel1_NVR_ch1_jpg_20230424145600.jpg',
 'panel1_NVR_ch1_jpg_20230424145900.jpg',
 'panel1_NVR_ch1_jpg_20230424145800.jpg',
 'panel1_NVR_ch1_jpg_20230424150000.jpg',
 'panel1_NVR_ch1_jpg_20230424150200.jpg',
 'panel1_NVR_ch1_jpg_20230424150300.jpg',
 'panel1_NVR_ch1_jpg_20230424150400.jpg',
 'panel1_NVR_ch1_jpg_20230424163800.jpg',
 'panel1_NVR_ch1_jpg_20230424163900.jpg',
 'panel1_NVR_ch1_jpg_20230424164000.jpg',
 'panel1_NVR_ch1_jpg_20230424164200.jpg',
 'panel1_NVR_ch1_jpg_20230424164300.jpg',
 'panel1_NVR_ch1_jpg_20230424164400.jpg',
 'panel1_NVR_ch1_jpg_20230424164600.jpg',
 'panel1_NVR_ch1_jpg_20230424164700.jpg',
 'panel1_NVR_ch1_jpg_20230424164800.jpg',
 'panel1_NVR_ch1_jpg_20230424165000.jpg',
 'panel1_NVR_ch1_jpg_20230424165100.jpg',
 'panel1_NVR_ch1_jpg_20230424165200.jpg',
 'panel1_NVR_ch1_jpg_20230424165400.jpg',
 'panel1_NVR_ch1_jpg_20230424165500.jpg',
 'panel1_NVR_ch1_jpg_20230424165600.jpg',
 'panel1_NVR_ch1_jpg_20230424165800.jpg',
 'panel1_NVR_ch1_jpg_20230424165900.jpg',
 'panel1_NVR_ch1_jpg_20230424170000.jpg',
 'panel1_NVR_ch1_jpg_20230424170200.jpg',
 'panel1_NVR_ch1_jpg_20230424170300.jpg',
 'panel1_NVR_ch1_jpg_20230424170400.jpg',
 'panel1_NVR_ch1_jpg_20230424170600.jpg',
 'panel1_NVR_ch1_jpg_20230424170700.jpg',
 'panel1_NVR_ch1_jpg_20230424170800.jpg',
 'panel1_NVR_ch1_jpg_20230424171000.jpg',
 'panel1_NVR_ch1_jpg_20230424171100.jpg',
 'panel1_NVR_ch1_jpg_20230424171200.jpg',
 'panel1_NVR_ch1_jpg_20230424171400.jpg',
 'panel1_NVR_ch1_jpg_20230424171500.jpg',
 'panel1_NVR_ch1_jpg_20230424171600.jpg',
 'panel1_NVR_ch1_jpg_20230424171800.jpg',
 'panel1_NVR_ch1_jpg_20230424171900.jpg',
 'panel1_NVR_ch1_jpg_20230424172000.jpg',
 'panel1_NVR_ch1_jpg_20230424172200.jpg',
 'panel1_NVR_ch1_jpg_20230424172300.jpg',
 'panel1_NVR_ch1_jpg_20230424172400.jpg',
 'panel1_NVR_ch1_jpg_20230424172600.jpg',
 'panel1_NVR_ch1_jpg_20230424172700.jpg',
 'panel1_NVR_ch1_jpg_20230424172800.jpg',
 'panel1_NVR_ch1_jpg_20230424173000.jpg',
 'panel1_NVR_ch1_jpg_20230424173200.jpg',
 'panel1_NVR_ch1_jpg_20230424173100.jpg',
 'panel1_NVR_ch1_jpg_20230424173400.jpg',
 'panel1_NVR_ch1_jpg_20230424173500.jpg',
 'panel1_NVR_ch1_jpg_20230424173600.jpg',
 'panel1_NVR_ch1_jpg_20230424173800.jpg',
 'panel1_NVR_ch1_jpg_20230424173900.jpg',
 'panel1_NVR_ch1_jpg_20230424174000.jpg',
 'panel1_NVR_ch1_jpg_20230424174200.jpg',
 'panel1_NVR_ch1_jpg_20230424174300.jpg',
 'panel1_NVR_ch1_jpg_20230424174400.jpg',
 'panel1_NVR_ch1_jpg_20230424174700.jpg',
 'panel1_NVR_ch1_jpg_20230424174800.jpg',
 'panel1_NVR_ch1_jpg_20230424174900.jpg',
 'panel1_NVR_ch1_jpg_20230501091300.jpg',
 'panel1_NVR_ch1_jpg_20230501091400.jpg',
 'panel1_NVR_ch1_jpg_20230501091500.jpg',
 'panel1_NVR_ch1_jpg_20230501091700.jpg',
 'panel1_NVR_ch1_jpg_20230501091800.jpg',
 'panel1_NVR_ch1_jpg_20230501091900.jpg',
 'panel1_NVR_ch1_jpg_20230501092100.jpg',
 'panel1_NVR_ch1_jpg_20230501092200.jpg',
 'panel1_NVR_ch1_jpg_20230501092300.jpg',
 'panel1_NVR_ch1_jpg_20230501092500.jpg',
 'panel1_NVR_ch1_jpg_20230501092600.jpg',
 'panel1_NVR_ch1_jpg_20230501092700.jpg',
 'panel1_NVR_ch1_jpg_20230501092900.jpg',
 'panel1_NVR_ch1_jpg_20230501093000.jpg',
 'panel1_NVR_ch1_jpg_20230501093100.jpg',
 'panel1_NVR_ch1_jpg_20230501093300.jpg',
 'panel1_NVR_ch1_jpg_20230501093400.jpg',
 'panel1_NVR_ch1_jpg_20230501093500.jpg',
 'panel1_NVR_ch1_jpg_20230501093700.jpg',
 'panel1_NVR_ch1_jpg_20230501093800.jpg',
 'panel1_NVR_ch1_jpg_20230501093900.jpg',
 'panel1_NVR_ch1_jpg_20230501094100.jpg',
 'panel1_NVR_ch1_jpg_20230501094200.jpg',
 'panel1_NVR_ch1_jpg_20230501094300.jpg',
 'panel1_NVR_ch1_jpg_20230501094600.jpg',
 'panel1_NVR_ch1_jpg_20230501094700.jpg',
 'panel1_NVR_ch1_jpg_20230501094500.jpg',
 'panel1_NVR_ch1_jpg_20230501094900.jpg',
 'panel1_NVR_ch1_jpg_20230501095000.jpg',
 'panel1_NVR_ch1_jpg_20230501095100.jpg',
 'panel1_NVR_ch1_jpg_20230501095300.jpg',
 'panel1_NVR_ch1_jpg_20230501095400.jpg',
 'panel1_NVR_ch1_jpg_20230501095500.jpg',

In [39]:
os.listdir(dataset_folders["cloud"]["origin"])[-2][19:33]

'20230524150700'

In [40]:
for f in os.listdir(dataset_folders["cloud"]["origin"]):
    if f[-3:] == "csv":
        continue 
        
    date = datetime.datetime.strptime(f[19:33],'%Y%m%d%H%M%S' ) 
     
    if len(df.loc[(df["일시"]==date)]) != 0 :
        shutil.copy2(dataset_folders["cloud"]["origin"]+f,new_dataset_folders["cloud"]["origin"]+f )  
    else :    
        print(f)

panel1_NVR_ch1_jpg_20230329172100.jpg
panel1_NVR_ch1_jpg_20230329172800.jpg
panel1_NVR_ch1_jpg_20230417135400.jpg
panel1_NVR_ch1_jpg_20230417135500.jpg
panel1_NVR_ch1_jpg_20230417135600.jpg
panel1_NVR_ch1_jpg_20230417172500.jpg
panel1_NVR_ch1_jpg_20230424143300.jpg

---

In [41]:
df_cloud = pd.read_csv(f'{dataset_folders["cloud"]["classification"]}classificationScore.csv')
df_cloud

,Unnamed: 0,name,A-sky,B-pattern,C-thick-dark,D-thick-white,E-veil
0,0,panel1_NVR_ch1_jpg_20230322164400.jpg,4.424425e-06,1.453420e-03,12.288953,85.415357,2.294232
1,1,panel1_NVR_ch1_jpg_20230322164800.jpg,1.774776e-08,5.227813e-03,1.871882,97.819990,0.302909
2,2,panel1_NVR_ch1_jpg_20230322165200.jpg,1.740531e-09,3.397775e-02,39.807442,58.484578,1.673997
3,3,panel1_NVR_ch1_jpg_20230322165600.jpg,3.556563e-11,4.018900e-01,0.855924,98.492891,0.249288
4,4,panel1_NVR_ch1_jpg_20230322170200.jpg,2.254395e-18,3.120831e-02,52.248859,47.716528,0.003402
5,5,panel1_NVR_ch1_jpg_20230329091700.jpg,2.822049e-02,1.796948e-04,14.607355,0.442075,84.922165
6,6,panel1_NVR_ch1_jpg_20230329092100.jpg,2.369767e-03,3.498847e-05,20.090453,0.339599,79.567534
7,7,panel1_NVR_ch1_jpg_20230329092500.jpg,1.896276e-03,2.181109e-04,29.134721,0.314629,70.548540
8,8,panel1_NVR_ch1_jpg_20230329092900.jpg,6.471734e-05,1.116257e-04,49.240392,0.063785,50.695640
9,9,panel1_NVR_ch1_jpg_20230329093300.jpg,3.099385e-05,1.818397e-04,74.216068,0.032860,25.750858
10,10,panel1_NVR_ch1_jpg_20230329093700.jpg,9.338147e-06,1.163263e-03,86.476457,0.059971,13.462400
11,11,panel1_NVR_ch1_jpg_20230329094200.jpg,4.871554e-06,7.781656e-04,39.441219,0.033145,60.524851
12,12,panel1_NVR_ch1_jpg_20230329141400.jpg,3.838499e-03,1.216008e+00,15.698999,4.774864,78.306288
13,13,panel1_NVR_ch1_jpg_20230329141800.jpg,2.876131e-03,1.135739e+00,13.572277,3.274671,82.014436
14,14,panel1_NVR_ch1_jpg_20230329142200.jpg,6.751944e-03,1.182922e+00,15.731281,3.081800,79.997247
15,15,panel1_NVR_ch1_jpg_20230329142600.jpg,9.952065e-03,1.467593e+00,12.762883,3.229250,82.530314
16,16,panel1_NVR_ch1_jpg_20230329143000.jpg,4.263642e-02,2.935632e+00,10.866613,3.301825,82.853287
17,17,panel1_NVR_ch1_jpg_20230329143400.jpg,5.119003e-02,3.626727e+00,11.182767,2.817329,82.321990
18,18,panel1_NVR_ch1_jpg_20230329144200.jpg,5.187550e-01,4.000583e+00,14.370240,4.274743,76.835668
19,19,panel1_NVR_ch1_jpg_20230329143800.jpg,1.703914e-01,3.232540e+00,12.238962,2.874035,81.484067
20,20,panel1_NVR_ch1_jpg_20230329144600.jpg,3.598477e-01,5.864248e+00,8.056875,4.331289,81.387746
21,21,panel1_NVR_ch1_jpg_20230329145000.jpg,6.641469e-01,5.580687e+00,14.539328,6.038396,73.177433
22,22,panel1_NVR_ch1_jpg_20230329145400.jpg,2.190521e-01,4.836385e+00,20.210148,5.720355,69.014060
23,23,panel1_NVR_ch1_jpg_20230329145800.jpg,8.250570e-02,3.319587e+00,29.038036,5.844899,61.714971
24,24,panel1_NVR_ch1_jpg_20230329164100.jpg,3.519209e-03,1.105374e-01,54.112697,16.863148,28.910094
25,25,panel1_NVR_ch1_jpg_20230329150700.jpg,2.919647e-02,2.097867e+00,32.838190,6.272288,58.762461
26,26,panel1_NVR_ch1_jpg_20230329164500.jpg,1.594951e-03,7.594120e-02,52.216446,20.965084,26.740938
27,27,panel1_NVR_ch1_jpg_20230329164900.jpg,1.532679e-03,5.864067e-02,55.143827,20.902529,23.893471
28,28,panel1_NVR_ch1_jpg_20230329165300.jpg,1.444449e-03,4.859993e-02,52.134770,22.536141,25.279042
29,29,panel1_NVR_ch1_jpg_20230329165700.jpg,6.649193e-04,3.947956e-02,56.957668,21.182008,21.820180
30,30,panel1_NVR_ch1_jpg_20230329170000.jpg,3.946557e-04,3.046454e-02,57.557851,23.173979,19.237307
31,31,panel1_NVR_ch1_jpg_20230329170500.jpg,1.103302e-04,1.822172e-02,58.788228,23.754573,17.438869
32,32,panel1_NVR_ch1_jpg_20230329171000.jpg,6.610385e-05,1.245022e-02,50.003946,32.911584,17.071952
33,33,panel1_NVR_ch1_jpg_20230329171500.jpg,3.143502e-05,7.486861e-03,46.286893,38.984829,14.720757
34,34,panel1_NVR_ch1_jpg_20230329172100.jpg,1.905029e-05,4.212831e-03,47.322741,40.920568,11.752463
35,35,panel1_NVR_ch1_jpg_20230329172800.jpg,1.010764e-05,3.142183e-03,47.741035,42.857212,9.398597
36,36,panel1_NVR_ch1_jpg_20230403093600.jpg,1.791736e-02,5.780106e-04,5.633583,1.671441,92.676473
37,37,panel1_NVR_ch1_jpg_20230403094000.jpg,2.225627e-02,7.235465e-04,2.731198,1.491567,95.754254
38,38,panel1_NVR_ch1_jpg_20230403094500.jpg,6.768539e-02,3.651939e-03,3.993225,1.216308,94.719136
39,39,panel1_NVR_ch1_jpg_20230403094900.jpg,1.776557e-01,1.532343e-02,2.053736,1.007080,96.746206
40,40,panel1_NVR_ch1_jpg_20230403095300.jpg,2.602781e-02,5.130605e-02,1.416101,0.639042,97.867525
41,41,panel1_NVR_ch1_jpg_20230403095700.jpg,2.418870e-02,7.256549e-03,9.442911,1.148982,89.376670
42,42,panel1_NVR_ch1_jpg_20230403100100.jpg,5.857380e-02,1.531530e-02,4.791831,1.560253,93.574023
43,43,panel1_NVR_ch1_jpg_20230403100600.jpg,6.845430e-03,1.217546e-01,62.464148,1.556262,35.850996
44,44,panel1_NVR_ch1_jpg_20230403101100.jpg,8.742585e-03,1.410379e+00,47.415704,1.939661,49.225512
45,45,panel1_NVR_ch1_jpg_20230403101500.jpg,5.170496e-03,1.063354e+00,74.121261,6.877874,17.932339
46,46,panel1_NVR_ch1_jpg_20230403135000.jpg,3.083083e-04,2.112794e-01,19.256917,0.638821,79.892677
47,47,panel1_NVR_ch1_jpg_20230403135400.jpg,4.911980e-04,3.249156e-01,17.862567,0.754493,81.057537
48,48,panel1_NVR_ch1_jpg_20230403135800.jpg,4.400047e-04,2.613639e-01,19.705711,0.671070,79.361403
49,49,panel1_NVR_ch1_jpg_20230403140200.jpg,3.592013e-04,2.608912e-01,15.691625,0.619963,83.427161
50,50,panel1_NVR_ch1_jpg_20230403140600.jpg,5.600901e-04,4.748003e-01,16.647460,1.124523,81.752664
51,51,panel1_NVR_ch1_jpg_20230403141000.jpg,4.223438e-04,5.981638e-01,11.971211,1.482599,85.947609
52,52,panel1_NVR_ch1_jpg_20230403141400.jpg,6.361059e-04,7.630698e-01,13.093534,1.543350,84.599411
53,53,panel1_NVR_ch1_jpg_20230403141800.jpg,6.882036e-04,8.739987e-01,11.289545,2.106412,85.729355
54,54,panel1_NVR_ch1_jpg_20230403142200.jpg,4.596823e-04,7.572423e-01,14.941551,2.114229,82.186520
55,55,panel1_NVR_ch1_jpg_20230403142600.jpg,6.000389e-04,7.741673e-01,9.525012,1.818221,87.882006
56,56,panel1_NVR_ch1_jpg_20230403144400.jpg,1.461675e-03,1.509868e+00,9.099022,3.458317,85.931325
57,57,panel1_NVR_ch1_jpg_20230403144800.jpg,2.965355e-03,1.811991e+00,8.270880,3.116184,86.797976
58,58,panel1_NVR_ch1_jpg_20230403145200.jpg,2.450753e-03,1.688382e+00,11.669382,4.538660,82.101119
59,59,panel1_NVR_ch1_jpg_20230403145600.jpg,2.914597e-03,2.079710e+00,9.885771,5.127930,82.903671
60,60,panel1_NVR_ch1_jpg_20230403150000.jpg,1.968342e-03,2.231079e+00,8.927087,6.527214,82.312649
61,61,panel1_NVR_ch1_jpg_20230403150400.jpg,1.904530e-03,1.696621e+00,10.178253,5.894491,82.228738
62,62,panel1_NVR_ch1_jpg_20230403150800.jpg,4.326362e-03,2.542258e+00,7.794107,4.394719,85.264575
63,63,panel1_NVR_ch1_jpg_20230403151200.jpg,4.009394e-03,1.663582e+00,11.018854,4.833310,82.480240
64,64,panel1_NVR_ch1_jpg_20230403151600.jpg,7.189852e-03,1.911006e+00,8.551525,3.551120,85.979158
65,65,panel1_NVR_ch1_jpg_20230403152000.jpg,7.739892e-03,1.705130e+00,10.771186,4.441151,83.074790
66,66,panel1_NVR_ch1_jpg_20230403164700.jpg,1.639883e-01,1.325867e-01,14.544374,31.100151,54.058897
67,67,panel1_NVR_ch1_jpg_20230403165100.jpg,1.070737e-01,5.371594e-02,14.785816,42.428339,42.625058
68,68,panel1_NVR_ch1_jpg_20230403165500.jpg,6.832765e-02,2.359692e-02,16.293219,48.364031,35.250825
69,69,panel1_NVR_ch1_jpg_20230403165900.jpg,1.053826e-01,2.919897e-02,14.567219,54.204184,31.094015
70,70,panel1_NVR_ch1_jpg_20230403170300.jpg,7.364426e-02,1.597292e-02,10.999168,64.048642,24.862579
71,71,panel1_NVR_ch1_jpg_20230403170700.jpg,3.573952e-02,5.404059e-03,7.541744,77.347225,15.069886
72,72,panel1_NVR_ch1_jpg_20230403171200.jpg,4.708691e-02,6.463388e-03,6.921506,74.534184,18.490760
73,73,panel1_NVR_ch1_jpg_20230403171800.jpg,2.299533e-02,3.004873e-03,7.937783,77.091306,14.944910
74,74,panel1_NVR_ch1_jpg_20230403172300.jpg,2.699021e-02,4.006873e-03,6.265026,80.717373,12.986612
75,75,panel1_NVR_ch1_jpg_20230403172700.jpg,2.107287e-02,2.265674e-03,4.066035,86.321539,9.589091
76,76,panel1_NVR_ch1_jpg_20230403173100.jpg,8.905363e-03,1.239747e-03,3.565999,89.750397,6.673455
77,77,panel1_NVR_ch1_jpg_20230410091800.jpg,2.787152e-05,8.975111e-06,15.392289,0.067759,84.539920
78,78,panel1_NVR_ch1_jpg_20230410091900.jpg,3.369844e-05,1.126064e-05,13.496879,0.058244,86.444837
79,79,panel1_NVR_ch1_jpg_20230410092000.jpg,2.273913e-05,1.095795e-05,16.383708,0.057440,83.558816
80,80,panel1_NVR_ch1_jpg_20230410092200.jpg,1.570255e-04,5.008088e-05,5.655973,0.086672,94.257146
81,81,panel1_NVR_ch1_jpg_20230410092400.jpg,1.923528e-05,1.192577e-05,21.181010,0.052608,78.766346
82,82,panel1_NVR_ch1_jpg_20230410092300.jpg,2.011637e-05,1.235854e-05,19.649309,0.055339,80.295312
83,83,panel1_NVR_ch1_jpg_20230410092600.jpg,1.118217e-05,9.034185e-06,27.681848,0.066116,72.252023
84,84,panel1_NVR_ch1_jpg_20230410092700.jpg,1.745340e-04,4.069786e-05,4.462116,0.076143,95.461524
85,85,panel1_NVR_ch1_jpg_20230410092800.jpg,1.114521e-05,8.775362e-06,27.338046,0.046824,72.615117
86,86,panel1_NVR_ch1_jpg_20230410093000.jpg,9.890410e-05,3.477116e-05,12.081892,0.089728,87.828261
87,87,panel1_NVR_ch1_jpg_20230410093100.jpg,1.723800e-05,1.704627e-05,25.936046,0.054487,74.009430
88,88,panel1_NVR_ch1_jpg_20230410093200.jpg,1.359711e-04,3.392261e-05,9.020627,0.093982,90.885216
89,89,panel1_NVR_ch1_jpg_20230410093400.jpg,1.155244e-05,1.122008e-05,36.538357,0.047709,63.413906
90,90,panel1_NVR_ch1_jpg_20230410093500.jpg,1.054034e-05,1.077335e-05,38.518032,0.053296,61.428666
91,91,panel1_NVR_ch1_jpg_20230410093600.jpg,6.795920e-06,7.182400e-06,34.079725,0.049826,65.870434
92,92,panel1_NVR_ch1_jpg_20230410093800.jpg,1.635739e-05,1.342584e-05,27.942175,0.048861,72.008926
93,93,panel1_NVR_ch1_jpg_20230410093900.jpg,9.176249e-06,1.644142e-05,47.065741,0.037942,52.896297
94,94,panel1_NVR_ch1_jpg_20230410094000.jpg,1.561557e-05,1.251109e-05,31.887111,0.047372,68.065482
95,95,panel1_NVR_ch1_jpg_20230410094200.jpg,1.608052e-05,1.443476e-05,32.319564,0.058503,67.621911
96,96,panel1_NVR_ch1_jpg_20230410094300.jpg,8.812340e-06,1.166139e-05,54.588151,0.028902,45.382923
97,97,panel1_NVR_ch1_jpg_20230410094400.jpg,1.476358e-05,2.225549e-05,41.533598,0.037040,58.429331
98,98,panel1_NVR_ch1_jpg_20230410094600.jpg,2.229236e-05,2.097287e-05,46.142986,0.070527,53.786445
99,99,panel1_NVR_ch1_jpg_20230410094700.jpg,1.739259e-05,1.725684e-05,40.904599,0.053018,59.042352
100,100,panel1_NVR_ch1_jpg_20230410094800.jpg,2.414326e-05,1.761994e-05,58.080178,0.080087,41.839689
101,101,panel1_NVR_ch1_jpg_20230410095000.jpg,1.727138e-05,1.759538e-05,65.074331,0.065785,34.859842
102,102,panel1_NVR_ch1_jpg_20230410095100.jpg,1.574387e-05,3.529550e-05,68.664765,0.054779,31.280401
103,103,panel1_NVR_ch1_jpg_20230410095200.jpg,1.538699e-05,4.430265e-05,71.702397,0.054491,28.243059
104,104,panel1_NVR_ch1_jpg_20230410095400.jpg,6.434418e-06,3.909479e-05,69.490397,0.028961,30.480599
105,105,panel1_NVR_ch1_jpg_20230410095500.jpg,7.133691e-06,3.385719e-05,69.868034,0.021888,30.110034
106,106,panel1_NVR_ch1_jpg_20230410095600.jpg,4.412535e-06,2.908113e-05,86.435747,0.021982,13.542241
107,107,panel1_NVR_ch1_jpg_20230410134300.jpg,7.763706e-02,2.631747e+00,11.491217,1.933208,83.866185
108,108,panel1_NVR_ch1_jpg_20230410134400.jpg,4.126950e-02,1.437458e+00,9.689444,1.194669,87.637162
109,109,panel1_NVR_ch1_jpg_20230410134500.jpg,4.169288e-02,1.366444e+00,8.599284,1.079297,88.913274
110,110,panel1_NVR_ch1_jpg_20230410134700.jpg,3.405167e-02,1.592002e+00,8.799180,1.432150,88.142622
111,111,panel1_NVR_ch1_jpg_20230410134800.jpg,3.628306e-02,1.685452e+00,10.035538,1.628053,86.614674
112,112,panel1_NVR_ch1_jpg_20230410134900.jpg,4.026903e-02,1.469139e+00,8.189521,1.098789,89.202279
113,113,panel1_NVR_ch1_jpg_20230410135100.jpg,4.127917e-02,1.738282e+00,9.069590,1.375025,87.775820
114,114,panel1_NVR_ch1_jpg_20230410135200.jpg,4.863203e-02,1.801178e+00,7.226922,1.189641,89.733624
115,115,panel1_NVR_ch1_jpg_20230410135300.jpg,3.319642e-02,1.804859e+00,9.290229,1.497369,87.374353
116,116,panel1_NVR_ch1_jpg_20230410135500.jpg,3.313852e-02,1.767642e+00,7.993892,1.365658,88.839674
117,117,panel1_NVR_ch1_jpg_20230410135600.jpg,3.930766e-02,1.857742e+00,7.580578,1.413068,89.109302
118,118,panel1_NVR_ch1_jpg_20230410135700.jpg,4.563314e-02,1.769172e+00,6.795342,1.164869,90.224981
119,119,panel1_NVR_ch1_jpg_20230410135900.jpg,6.559048e-02,2.292997e+00,8.193190,1.591522,87.856692
120,120,panel1_NVR_ch1_jpg_20230410140000.jpg,6.968274e-02,2.510869e+00,8.408308,1.779691,87.231451
121,121,panel1_NVR_ch1_jpg_20230410140100.jpg,7.859954e-02,2.522289e+00,9.009389,1.738585,86.651134
122,122,panel1_NVR_ch1_jpg_20230410140300.jpg,8.368823e-02,2.798185e+00,12.630683,2.310535,82.176900
123,123,panel1_NVR_ch1_jpg_20230410140400.jpg,9.540973e-02,3.149823e+00,13.468838,2.845049,80.440879
124,124,panel1_NVR_ch1_jpg_20230410140500.jpg,8.884471e-02,3.101513e+00,12.806448,2.989034,81.014168
125,125,panel1_NVR_ch1_jpg_20230410140700.jpg,9.408890e-02,2.896564e+00,13.137130,2.757046,81.115168
126,126,panel1_NVR_ch1_jpg_20230410140800.jpg,1.126240e-01,3.057125e+00,13.767304,2.851900,80.211049
127,127,panel1_NVR_ch1_jpg_20230410140900.jpg,1.075300e-01,3.467121e+00,15.545081,3.197251,77.683014
128,128,panel1_NVR_ch1_jpg_20230410141100.jpg,1.588466e-01,3.377264e+00,18.259381,3.420267,74.784249
129,129,panel1_NVR_ch1_jpg_20230410141200.jpg,1.719958e-01,3.761055e+00,18.226188,3.818583,74.022174
130,130,panel1_NVR_ch1_jpg_20230410141300.jpg,1.841848e-01,3.560615e+00,18.567918,3.364401,74.322885
131,131,panel1_NVR_ch1_jpg_20230410141500.jpg,2.258330e-01,4.554579e+00,18.462087,4.254319,72.503179
132,132,panel1_NVR_ch1_jpg_20230410141600.jpg,2.417458e-01,4.346194e+00,19.194241,4.020225,72.197592
133,133,panel1_NVR_ch1_jpg_20230410141700.jpg,2.228340e-01,3.955650e+00,19.619705,3.787166,72.414643
134,134,panel1_NVR_ch1_jpg_20230410141900.jpg,2.680714e-01,4.227648e+00,19.741166,3.736722,72.026402
135,135,panel1_NVR_ch1_jpg_20230410142000.jpg,3.468114e-01,4.526630e+00,19.726448,3.653268,71.746844
136,136,panel1_NVR_ch1_jpg_20230410142100.jpg,2.756469e-01,4.926707e+00,17.825150,3.736508,73.235995
137,137,panel1_NVR_ch1_jpg_20230410142300.jpg,5.329127e-01,7.059247e+00,17.913549,5.638630,68.855661
138,138,panel1_NVR_ch1_jpg_20230410142400.jpg,4.835255e-01,6.987368e+00,16.501336,5.852120,70.175654
139,139,panel1_NVR_ch1_jpg_20230410142500.jpg,4.797779e-01,6.990974e+00,16.966841,5.631332,69.931078
140,140,panel1_NVR_ch1_jpg_20230410142700.jpg,4.587596e-01,6.642198e+00,18.435447,5.469006,68.994594
141,141,panel1_NVR_ch1_jpg_20230410142800.jpg,4.742520e-01,7.175308e+00,16.577865,5.634684,70.137888
142,142,panel1_NVR_ch1_jpg_20230410142900.jpg,5.055964e-01,6.741691e+00,17.721574,5.311909,69.719231
143,143,panel1_NVR_ch1_jpg_20230410143100.jpg,4.821172e-01,5.831650e+00,21.124253,4.149469,68.412519
144,144,panel1_NVR_ch1_jpg_20230410143200.jpg,3.621002e-01,4.643692e+00,21.258517,3.242002,70.493686
145,145,panel1_NVR_ch1_jpg_20230410143300.jpg,4.809887e-01,6.301842e+00,19.528635,4.429035,69.259501
146,146,panel1_NVR_ch1_jpg_20230410164800.jpg,2.720888e-03,3.399304e-03,44.636342,6.102423,49.255121
147,147,panel1_NVR_ch1_jpg_20230410164900.jpg,1.567867e-03,2.557297e-03,49.203625,6.165610,44.626641
148,148,panel1_NVR_ch1_jpg_20230410165200.jpg,3.902937e-03,1.289194e-03,48.624882,7.222971,44.146949
149,149,panel1_NVR_ch1_jpg_20230410165300.jpg,4.486883e-03,1.063645e-03,42.952618,11.318957,45.722866
150,150,panel1_NVR_ch1_jpg_20230410165000.jpg,1.525901e-03,1.739283e-03,51.920861,5.966140,42.109734
151,151,panel1_NVR_ch1_jpg_20230410165400.jpg,1.381996e-02,1.327218e-03,24.393405,17.826594,57.764858
152,152,panel1_NVR_ch1_jpg_20230410165700.jpg,4.220769e-03,1.850433e-03,32.300216,17.280662,50.413048
153,153,panel1_NVR_ch1_jpg_20230410165800.jpg,6.836222e-03,1.721200e-03,30.652842,15.731011,53.607589
154,154,panel1_NVR_ch1_jpg_20230410165900.jpg,5.192523e-03,1.753626e-03,34.120500,13.637243,52.235311
155,155,panel1_NVR_ch1_jpg_20230410170100.jpg,7.596779e-03,1.771823e-03,30.944350,14.652129,54.394144
156,156,panel1_NVR_ch1_jpg_20230410170200.jpg,9.385522e-03,1.783638e-03,29.463214,13.435686,57.089931
157,157,panel1_NVR_ch1_jpg_20230410170300.jpg,7.451421e-03,1.843572e-03,30.442896,14.950559,54.597247
158,158,panel1_NVR_ch1_jpg_20230410170500.jpg,5.545335e-03,1.913363e-03,34.887698,16.193829,48.911011
159,159,panel1_NVR_ch1_jpg_20230410170600.jpg,4.990013e-03,1.915207e-03,35.390624,16.518503,48.083964
160,160,panel1_NVR_ch1_jpg_20230410170700.jpg,6.736560e-03,2.058285e-03,32.567728,17.549075,49.874401
161,161,panel1_NVR_ch1_jpg_20230410170900.jpg,1.142657e-02,2.162022e-03,28.587022,18.372662,53.026724
162,162,panel1_NVR_ch1_jpg_20230410171000.jpg,1.126337e-02,2.053622e-03,27.334046,19.866012,52.786630
163,163,panel1_NVR_ch1_jpg_20230410171100.jpg,1.108692e-02,1.930999e-03,26.828766,20.900801,52.257413
164,164,panel1_NVR_ch1_jpg_20230410171300.jpg,1.786217e-02,2.200312e-03,25.121987,21.656464,53.201485
165,165,panel1_NVR_ch1_jpg_20230410171400.jpg,1.406122e-02,2.204748e-03,24.203900,25.172141,50.607693
166,166,panel1_NVR_ch1_jpg_20230410171500.jpg,1.324226e-02,2.391368e-03,24.150205,24.902396,50.931764
167,167,panel1_NVR_ch1_jpg_20230410171700.jpg,1.440284e-02,2.263974e-03,21.171084,31.800622,47.011626
168,168,panel1_NVR_ch1_jpg_20230410171800.jpg,1.223406e-02,2.273203e-03,20.355813,35.230660,44.399026
169,169,panel1_NVR_ch1_jpg_20230410171900.jpg,8.541473e-03,2.321752e-03,22.749703,35.729006,41.510436
170,170,panel1_NVR_ch1_jpg_20230410172100.jpg,7.439965e-03,2.328868e-03,20.354927,41.886300,37.749004
171,171,panel1_NVR_ch1_jpg_20230410172200.jpg,6.256060e-03,2.414170e-03,21.586828,43.758437,34.646055
172,172,panel1_NVR_ch1_jpg_20230410172300.jpg,7.787078e-03,2.314658e-03,21.031398,43.810251,35.148248
173,173,panel1_NVR_ch1_jpg_20230410172500.jpg,3.533492e-03,2.039532e-03,24.008714,47.948328,28.037375
174,174,panel1_NVR_ch1_jpg_20230410172600.jpg,2.613711e-03,2.176506e-03,25.072625,47.675753,27.246839
175,175,panel1_NVR_ch1_jpg_20230410172700.jpg,1.900854e-03,1.715537e-03,25.128755,50.356513,24.511105
176,176,panel1_NVR_ch1_jpg_20230410172900.jpg,1.895021e-03,1.357388e-03,24.473701,53.712726,21.810322
177,177,panel1_NVR_ch1_jpg_20230410173000.jpg,1.299343e-03,1.157042e-03,26.159167,54.609084,19.229300
178,178,panel1_NVR_ch1_jpg_20230410173100.jpg,1.105118e-03,1.238524e-03,26.742077,54.841489,18.414089
179,179,panel1_NVR_ch1_jpg_20230417092100.jpg,1.140832e-04,2.168754e-04,45.425990,0.193041,54.380631
180,180,panel1_NVR_ch1_jpg_20230417092200.jpg,1.861220e-04,2.288497e-04,34.198406,0.178713,65.622467
181,181,panel1_NVR_ch1_jpg_20230417092300.jpg,3.378884e-04,2.775289e-04,23.028643,0.184500,76.786238
182,182,panel1_NVR_ch1_jpg_20230417092500.jpg,1.222768e-04,3.123855e-04,43.310976,0.125666,56.562930
183,183,panel1_NVR_ch1_jpg_20230417092600.jpg,3.735075e-05,2.166973e-04,71.335536,0.069126,28.595084
184,184,panel1_NVR_ch1_jpg_20230417092700.jpg,8.700181e-05,5.721829e-04,53.093863,0.100618,46.804857
185,185,panel1_NVR_ch1_jpg_20230417092900.jpg,6.148397e-05,3.127134e-04,62.701905,0.093430,37.204298
186,186,panel1_NVR_ch1_jpg_20230417093000.jpg,8.566210e-05,3.262973e-04,59.139186,0.105751,40.754643
187,187,panel1_NVR_ch1_jpg_20230417093100.jpg,5.918027e-05,1.598474e-04,46.056128,0.094169,53.849488
188,188,panel1_NVR_ch1_jpg_20230417093300.jpg,3.695163e-05,1.929075e-04,62.702858,0.075619,37.221298
189,189,panel1_NVR_ch1_jpg_20230417093400.jpg,4.097476e-05,1.638401e-04,58.161283,0.077745,41.760767
190,190,panel1_NVR_ch1_jpg_20230417093500.jpg,4.989022e-05,2.582222e-04,51.612389,0.081975,48.305333
191,191,panel1_NVR_ch1_jpg_20230417093700.jpg,2.916368e-05,3.020197e-04,63.842982,0.052881,36.103806
192,192,panel1_NVR_ch1_jpg_20230417093800.jpg,2.953468e-05,2.845112e-04,62.551171,0.059341,37.389177
193,193,panel1_NVR_ch1_jpg_20230417093900.jpg,3.449283e-05,3.016678e-04,66.771406,0.052291,33.175972
194,194,panel1_NVR_ch1_jpg_20230417094100.jpg,1.117269e-05,1.094446e-04,83.066857,0.036115,16.896909
195,195,panel1_NVR_ch1_jpg_20230417094200.jpg,6.446479e-06,6.439299e-05,90.962619,0.022912,9.014403
196,196,panel1_NVR_ch1_jpg_20230417094300.jpg,8.619043e-06,9.683374e-05,88.063025,0.031254,11.905618
197,197,panel1_NVR_ch1_jpg_20230417094500.jpg,4.941639e-06,6.688279e-05,89.430302,0.023796,10.545833
198,198,panel1_NVR_ch1_jpg_20230417094600.jpg,4.806481e-06,4.865358e-05,89.860094,0.020257,10.119591

In [42]:
datetime.datetime.strptime(df_cloud.loc[0]["name"][19:33],'%Y%m%d%H%M%S' )

datetime.datetime(2023, 3, 22, 16, 44)

In [43]:
indexs = []

for i in df_cloud.index :
    date = datetime.datetime.strptime(df_cloud.loc[i]["name"][19:33],'%Y%m%d%H%M%S') 

    if len(df.loc[(df["일시"]==date)]) == 0 :
        print(i, panel, date)
        indexs.append(i)
        
df_cloud.drop(index=indexs, inplace=True)

34 4 2023-03-29 17:21:00
35 4 2023-03-29 17:28:00
218 4 2023-04-17 13:54:00
219 4 2023-04-17 13:55:00
220 4 2023-04-17 13:56:00
260 4 2023-04-17 17:25:00
364 4 2023-04-24 14:33:00

In [44]:
df_cloud = df_cloud.reset_index(drop =True)
df_cloud.to_csv(f'{new_dataset_folders["cloud"]["classification"]}classificationScore.csv')